#[allow(clippy::unreadable_literal)]
static SPECIALS: phf::Set<&'static str> =
::phf::Set { map: ::phf::Map {
    key: 7485420634051515786,
    disps: &[
        (7, 45),
        (0, 28),
        (0, 56),
        (0, 24),
        (0, 0),
        (0, 34),
        (2, 19),
        (10, 16),
        (0, 1),
        (2, 33),
        (43, 24),
        (0, 42),
    ],
    entries: &[
        ("explicit", ()),
        ("inline", ()),
        ("true", ()),
        ("uint_fast64_t", ()),
        ("int", ()),
        ("char", ()),
        ("uint_fast8_t", ()),
        ("int32_t", ()),
        ("uint_fast16_t", ()),
        ("int64_t", ()),
        ("charptr_t", ()),
        ("bool", ()),
        ("intptr_t", ()),
        ("int_fast8_t", ()),
        ("uint_least32_t", ()),
        ("uint_fast32_t", ()),
        ("size_t", ()),
        ("NULL", ()),
        ("uint_least8_t", ()),
        ("false", ()),
        ("static", ()),
        ("uintptr_t", ()),
        ("ssize_t", ()),
        ("int_least64_t", ()),
        ("max_align_t", ()),
        ("uint32_t", ()),
        ("float", ()),
        ("double", ()),
        ("uintmax_t", ()),
        ("int_fast16_t", ()),
        ("intmax_t", ()),
        ("short", ()),
        ("uint64_t", ()),
        ("const", ()),
        ("uint_least16_t", ()),
        ("int_least32_t", ()),
        ("uint_least64_t", ()),
        ("char32_t", ()),
        ("ptrdiff_t", ()),
        ("nullptr", ()),
        ("int_fast64_t", ()),
        ("int_least8_t", ()),
        ("restrict", ()),
        ("wchar_t", ()),
        ("uint16_t", ()),
        ("char16_t", ()),
        ("constexpr", ()),
        ("namespace", ()),
        ("char8_t", ()),
        ("unsigned", ()),
        ("int8_t", ()),
        ("char64_t", ()),
        ("int_least16_t", ()),
        ("signed", ()),
        ("int16_t", ()),
        ("long", ()),
        ("int_fast32_t", ()),
        ("uint8_t", ()),
        ("mutable", ()),
    ],
} };

pub fn is_specials(mac: &str) -> bool { SPECIALS.contains(mac) }

