// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum C {
    End = 0,
    Identifier = 1,
    Macro = 2,
    LF = 3,
    HASHinclude = 4,
    HASHdefine = 5,
    LPAREN = 6,
    PreprocParamsToken1 = 7,
    DOTDOTDOT = 8,
    COMMA = 9,
    RPAREN = 10,
    HASHif = 11,
    HASHendif = 12,
    HASHifdef = 13,
    HASHifndef = 14,
    HASHelse = 15,
    HASHelif = 16,
    PreprocDirective = 17,
    PreprocArg = 18,
    LPAREN2 = 19,
    Defined = 20,
    BANG = 21,
    TILDE = 22,
    DASH = 23,
    PLUS = 24,
    STAR = 25,
    SLASH = 26,
    PERCENT = 27,
    PIPEPIPE = 28,
    AMPAMP = 29,
    PIPE = 30,
    CARET = 31,
    AMP = 32,
    EQEQ = 33,
    BANGEQ = 34,
    GT = 35,
    GTEQ = 36,
    LTEQ = 37,
    LT = 38,
    LTLT = 39,
    GTGT = 40,
    Cdecl = 41,
    Clrcall = 42,
    Stdcall = 43,
    Fastcall = 44,
    Thiscall = 45,
    Vectorcall = 46,
    WINAPI = 47,
    CALLBACK = 48,
    SEMI = 49,
    Typedef = 50,
    Extern = 51,
    Attribute = 52,
    LBRACE = 53,
    RBRACE = 54,
    LBRACK = 55,
    RBRACK = 56,
    EQ = 57,
    Static = 58,
    Auto = 59,
    Register = 60,
    Inline = 61,
    Const = 62,
    CONST = 63,
    Volatile = 64,
    Restrict = 65,
    Vector = 66,
    Atomic = 67,
    Signed = 68,
    Unsigned = 69,
    Long = 70,
    Short = 71,
    PrimitiveType = 72,
    Enum = 73,
    Struct = 74,
    Union = 75,
    COLON = 76,
    If = 77,
    Else = 78,
    Switch = 79,
    Case = 80,
    Default = 81,
    While = 82,
    Do = 83,
    For = 84,
    Return = 85,
    Break = 86,
    Continue = 87,
    Goto = 88,
    QMARK = 89,
    STAREQ = 90,
    SLASHEQ = 91,
    PERCENTEQ = 92,
    PLUSEQ = 93,
    DASHEQ = 94,
    LTLTEQ = 95,
    GTGTEQ = 96,
    AMPEQ = 97,
    CARETEQ = 98,
    PIPEEQ = 99,
    DASHDASH = 100,
    PLUSPLUS = 101,
    Sizeof = 102,
    DOT = 103,
    DASHGT = 104,
    NumberLiteral = 105,
    LSQUOTE = 106,
    SQUOTE = 107,
    CharLiteralToken1 = 108,
    LDQUOTE = 109,
    DQUOTE = 110,
    StringLiteralToken1 = 111,
    EscapeSequence = 112,
    SystemLibString = 113,
    True = 114,
    False = 115,
    Null = 116,
    Comment = 117,
    TranslationUnit = 118,
    OnlyMacro = 119,
    MacroCall = 120,
    OnlyMacroCall = 121,
    PreprocInclude = 122,
    PreprocDef = 123,
    PreprocFunctionDef = 124,
    PreprocParams = 125,
    PreprocCall = 126,
    PreprocIf = 127,
    PreprocIfdef = 128,
    PreprocElse = 129,
    PreprocElif = 130,
    PreprocIf2 = 131,
    PreprocIfdef2 = 132,
    PreprocElse2 = 133,
    PreprocElif2 = 134,
    LineContinuation = 135,
    PreprocCondition = 136,
    PreprocExpression = 137,
    PreprocParenthesizedExpression = 138,
    PreprocDefined = 139,
    PreprocUnaryExpression = 140,
    PreprocBinaryExpression = 141,
    CallConvention = 142,
    FunctionDefinition = 143,
    Declaration = 144,
    TypeDefinition = 145,
    DeclarationSpecifiers = 146,
    DeclarationSpecifiersNoType = 147,
    LinkageSpecification = 148,
    AttributeSpecifier = 149,
    DeclarationList = 150,
    Declarator = 151,
    FieldDeclarator = 152,
    TypeDeclarator = 153,
    AbstractDeclarator = 154,
    ParenthesizedDeclarator = 155,
    ParenthesizedDeclarator2 = 156,
    ParenthesizedDeclarator3 = 157,
    AbstractParenthesizedDeclarator = 158,
    PointerDeclarator = 159,
    PointerDeclarator2 = 160,
    PointerDeclarator3 = 161,
    AbstractPointerDeclarator = 162,
    FunctionDeclarator = 163,
    FunctionDeclarator2 = 164,
    FunctionDeclarator3 = 165,
    AbstractFunctionDeclarator = 166,
    ArrayDeclarator = 167,
    ArrayDeclarator2 = 168,
    ArrayDeclarator3 = 169,
    AbstractArrayDeclarator = 170,
    InitDeclarator = 171,
    CompoundStatement = 172,
    StorageClassSpecifier = 173,
    TypeQualifier = 174,
    TypeSpecifier = 175,
    SizedTypeSpecifier = 176,
    EnumSpecifier = 177,
    EnumeratorList = 178,
    StructSpecifier = 179,
    UnionSpecifier = 180,
    FieldDeclarationList = 181,
    FieldDeclarationListItem = 182,
    FieldDeclaration = 183,
    BitfieldClause = 184,
    Enumerator = 185,
    ParameterList = 186,
    ParameterDeclaration = 187,
    LabeledStatement = 188,
    ExpressionStatement = 189,
    IfStatement = 190,
    SwitchStatement = 191,
    CompoundStatement2 = 192,
    CaseStatement = 193,
    WhileStatement = 194,
    DoStatement = 195,
    ForStatement = 196,
    ReturnStatement = 197,
    BreakStatement = 198,
    ContinueStatement = 199,
    GotoStatement = 200,
    Expression = 201,
    CommaExpression = 202,
    ConditionalExpression = 203,
    AssignmentExpression = 204,
    PointerExpression = 205,
    UnaryExpression = 206,
    BinaryExpression = 207,
    UpdateExpression = 208,
    CastExpression = 209,
    TypeDescriptor = 210,
    SizeofExpression = 211,
    SubscriptExpression = 212,
    CallExpression = 213,
    ArgumentList = 214,
    FieldExpression = 215,
    CompoundLiteralExpression = 216,
    ParenthesizedExpression = 217,
    InitializerList = 218,
    InitializerPair = 219,
    SubscriptDesignator = 220,
    FieldDesignator = 221,
    CharLiteral = 222,
    ConcatenatedString = 223,
    StringLiteral = 224,
    EmptyDeclaration = 225,
    TranslationUnitRepeat1 = 226,
    PreprocParamsRepeat1 = 227,
    PreprocIfInFieldDeclarationListRepeat1 = 228,
    PreprocExpressionRepeat1 = 229,
    DeclarationRepeat1 = 230,
    TypeDefinitionRepeat1 = 231,
    TypeDefinitionRepeat2 = 232,
    DeclarationSpecifiersRepeat1 = 233,
    DeclarationSpecifiersRepeat2 = 234,
    PointerDeclaratorRepeat1 = 235,
    FunctionDeclaratorRepeat1 = 236,
    SizedTypeSpecifierRepeat1 = 237,
    EnumeratorListRepeat1 = 238,
    FieldDeclarationRepeat1 = 239,
    ParameterListRepeat1 = 240,
    SwitchBodyRepeat1 = 241,
    CaseStatementRepeat1 = 242,
    ArgumentListRepeat1 = 243,
    InitializerListRepeat1 = 244,
    InitializerPairRepeat1 = 245,
    ConcatenatedStringRepeat1 = 246,
    StringLiteralRepeat1 = 247,
    StatementIdentifier = 248,
    FieldIdentifier = 249,
    TypeIdentifier = 250,
    Error = 251,
}

impl Into<&'static str> for C {
    fn into(self) -> &'static str {
        match self {
            C::End => "end",
            C::Identifier => "identifier",
            C::Macro => "macro",
            C::LF => "\n",
            C::HASHinclude => "#include",
            C::HASHdefine => "#define",
            C::LPAREN => "(",
            C::PreprocParamsToken1 => "preproc_params_token1",
            C::DOTDOTDOT => "...",
            C::COMMA => ",",
            C::RPAREN => ")",
            C::HASHif => "#if",
            C::HASHendif => "#endif",
            C::HASHifdef => "#ifdef",
            C::HASHifndef => "#ifndef",
            C::HASHelse => "#else",
            C::HASHelif => "#elif",
            C::PreprocDirective => "preproc_directive",
            C::PreprocArg => "preproc_arg",
            C::LPAREN2 => "(",
            C::Defined => "defined",
            C::BANG => "!",
            C::TILDE => "~",
            C::DASH => "-",
            C::PLUS => "+",
            C::STAR => "*",
            C::SLASH => "/",
            C::PERCENT => "%",
            C::PIPEPIPE => "||",
            C::AMPAMP => "&&",
            C::PIPE => "|",
            C::CARET => "^",
            C::AMP => "&",
            C::EQEQ => "==",
            C::BANGEQ => "!=",
            C::GT => ">",
            C::GTEQ => ">=",
            C::LTEQ => "<=",
            C::LT => "<",
            C::LTLT => "<<",
            C::GTGT => ">>",
            C::Cdecl => "__cdecl",
            C::Clrcall => "__clrcall",
            C::Stdcall => "__stdcall",
            C::Fastcall => "__fastcall",
            C::Thiscall => "__thiscall",
            C::Vectorcall => "__vectorcall",
            C::WINAPI => "WINAPI",
            C::CALLBACK => "CALLBACK",
            C::SEMI => ";",
            C::Typedef => "typedef",
            C::Extern => "extern",
            C::Attribute => "__attribute__",
            C::LBRACE => "{",
            C::RBRACE => "}",
            C::LBRACK => "[",
            C::RBRACK => "]",
            C::EQ => "=",
            C::Static => "static",
            C::Auto => "auto",
            C::Register => "register",
            C::Inline => "inline",
            C::Const => "const",
            C::CONST => "CONST",
            C::Volatile => "volatile",
            C::Restrict => "restrict",
            C::Vector => "vector",
            C::Atomic => "_Atomic",
            C::Signed => "signed",
            C::Unsigned => "unsigned",
            C::Long => "long",
            C::Short => "short",
            C::PrimitiveType => "primitive_type",
            C::Enum => "enum",
            C::Struct => "struct",
            C::Union => "union",
            C::COLON => ":",
            C::If => "if",
            C::Else => "else",
            C::Switch => "switch",
            C::Case => "case",
            C::Default => "default",
            C::While => "while",
            C::Do => "do",
            C::For => "for",
            C::Return => "return",
            C::Break => "break",
            C::Continue => "continue",
            C::Goto => "goto",
            C::QMARK => "?",
            C::STAREQ => "*=",
            C::SLASHEQ => "/=",
            C::PERCENTEQ => "%=",
            C::PLUSEQ => "+=",
            C::DASHEQ => "-=",
            C::LTLTEQ => "<<=",
            C::GTGTEQ => ">>=",
            C::AMPEQ => "&=",
            C::CARETEQ => "^=",
            C::PIPEEQ => "|=",
            C::DASHDASH => "--",
            C::PLUSPLUS => "++",
            C::Sizeof => "sizeof",
            C::DOT => ".",
            C::DASHGT => "->",
            C::NumberLiteral => "number_literal",
            C::LSQUOTE => "L'",
            C::SQUOTE => "'",
            C::CharLiteralToken1 => "char_literal_token1",
            C::LDQUOTE => "L\"",
            C::DQUOTE => "\"",
            C::StringLiteralToken1 => "string_literal_token1",
            C::EscapeSequence => "escape_sequence",
            C::SystemLibString => "system_lib_string",
            C::True => "true",
            C::False => "false",
            C::Null => "null",
            C::Comment => "comment",
            C::TranslationUnit => "translation_unit",
            C::OnlyMacro => "only_macro",
            C::MacroCall => "macro_call",
            C::OnlyMacroCall => "only_macro_call",
            C::PreprocInclude => "preproc_include",
            C::PreprocDef => "preproc_def",
            C::PreprocFunctionDef => "preproc_function_def",
            C::PreprocParams => "preproc_params",
            C::PreprocCall => "preproc_call",
            C::PreprocIf => "preproc_if",
            C::PreprocIfdef => "preproc_ifdef",
            C::PreprocElse => "preproc_else",
            C::PreprocElif => "preproc_elif",
            C::PreprocIf2 => "preproc_if",
            C::PreprocIfdef2 => "preproc_ifdef",
            C::PreprocElse2 => "preproc_else",
            C::PreprocElif2 => "preproc_elif",
            C::LineContinuation => "line_continuation",
            C::PreprocCondition => "preproc_condition",
            C::PreprocExpression => "preproc_expression",
            C::PreprocParenthesizedExpression => "preproc_parenthesized_expression",
            C::PreprocDefined => "preproc_defined",
            C::PreprocUnaryExpression => "preproc_unary_expression",
            C::PreprocBinaryExpression => "preproc_binary_expression",
            C::CallConvention => "call_convention",
            C::FunctionDefinition => "function_definition",
            C::Declaration => "declaration",
            C::TypeDefinition => "type_definition",
            C::DeclarationSpecifiers => "_declaration_specifiers",
            C::DeclarationSpecifiersNoType => "_declaration_specifiers_no_type",
            C::LinkageSpecification => "linkage_specification",
            C::AttributeSpecifier => "attribute_specifier",
            C::DeclarationList => "declaration_list",
            C::Declarator => "_declarator",
            C::FieldDeclarator => "_field_declarator",
            C::TypeDeclarator => "_type_declarator",
            C::AbstractDeclarator => "_abstract_declarator",
            C::ParenthesizedDeclarator => "parenthesized_declarator",
            C::ParenthesizedDeclarator2 => "parenthesized_declarator",
            C::ParenthesizedDeclarator3 => "parenthesized_declarator",
            C::AbstractParenthesizedDeclarator => "abstract_parenthesized_declarator",
            C::PointerDeclarator => "pointer_declarator",
            C::PointerDeclarator2 => "pointer_declarator",
            C::PointerDeclarator3 => "pointer_declarator",
            C::AbstractPointerDeclarator => "abstract_pointer_declarator",
            C::FunctionDeclarator => "function_declarator",
            C::FunctionDeclarator2 => "function_declarator",
            C::FunctionDeclarator3 => "function_declarator",
            C::AbstractFunctionDeclarator => "abstract_function_declarator",
            C::ArrayDeclarator => "array_declarator",
            C::ArrayDeclarator2 => "array_declarator",
            C::ArrayDeclarator3 => "array_declarator",
            C::AbstractArrayDeclarator => "abstract_array_declarator",
            C::InitDeclarator => "init_declarator",
            C::CompoundStatement => "compound_statement",
            C::StorageClassSpecifier => "storage_class_specifier",
            C::TypeQualifier => "type_qualifier",
            C::TypeSpecifier => "_type_specifier",
            C::SizedTypeSpecifier => "sized_type_specifier",
            C::EnumSpecifier => "enum_specifier",
            C::EnumeratorList => "enumerator_list",
            C::StructSpecifier => "struct_specifier",
            C::UnionSpecifier => "union_specifier",
            C::FieldDeclarationList => "field_declaration_list",
            C::FieldDeclarationListItem => "_field_declaration_list_item",
            C::FieldDeclaration => "field_declaration",
            C::BitfieldClause => "bitfield_clause",
            C::Enumerator => "enumerator",
            C::ParameterList => "parameter_list",
            C::ParameterDeclaration => "parameter_declaration",
            C::LabeledStatement => "labeled_statement",
            C::ExpressionStatement => "expression_statement",
            C::IfStatement => "if_statement",
            C::SwitchStatement => "switch_statement",
            C::CompoundStatement2 => "compound_statement",
            C::CaseStatement => "case_statement",
            C::WhileStatement => "while_statement",
            C::DoStatement => "do_statement",
            C::ForStatement => "for_statement",
            C::ReturnStatement => "return_statement",
            C::BreakStatement => "break_statement",
            C::ContinueStatement => "continue_statement",
            C::GotoStatement => "goto_statement",
            C::Expression => "_expression",
            C::CommaExpression => "comma_expression",
            C::ConditionalExpression => "conditional_expression",
            C::AssignmentExpression => "assignment_expression",
            C::PointerExpression => "pointer_expression",
            C::UnaryExpression => "unary_expression",
            C::BinaryExpression => "binary_expression",
            C::UpdateExpression => "update_expression",
            C::CastExpression => "cast_expression",
            C::TypeDescriptor => "type_descriptor",
            C::SizeofExpression => "sizeof_expression",
            C::SubscriptExpression => "subscript_expression",
            C::CallExpression => "call_expression",
            C::ArgumentList => "argument_list",
            C::FieldExpression => "field_expression",
            C::CompoundLiteralExpression => "compound_literal_expression",
            C::ParenthesizedExpression => "parenthesized_expression",
            C::InitializerList => "initializer_list",
            C::InitializerPair => "initializer_pair",
            C::SubscriptDesignator => "subscript_designator",
            C::FieldDesignator => "field_designator",
            C::CharLiteral => "char_literal",
            C::ConcatenatedString => "concatenated_string",
            C::StringLiteral => "string_literal",
            C::EmptyDeclaration => "_empty_declaration",
            C::TranslationUnitRepeat1 => "translation_unit_repeat1",
            C::PreprocParamsRepeat1 => "preproc_params_repeat1",
            C::PreprocIfInFieldDeclarationListRepeat1 => {
                "preproc_if_in_field_declaration_list_repeat1"
            }
            C::PreprocExpressionRepeat1 => "preproc_expression_repeat1",
            C::DeclarationRepeat1 => "declaration_repeat1",
            C::TypeDefinitionRepeat1 => "type_definition_repeat1",
            C::TypeDefinitionRepeat2 => "type_definition_repeat2",
            C::DeclarationSpecifiersRepeat1 => "_declaration_specifiers_repeat1",
            C::DeclarationSpecifiersRepeat2 => "_declaration_specifiers_repeat2",
            C::PointerDeclaratorRepeat1 => "pointer_declarator_repeat1",
            C::FunctionDeclaratorRepeat1 => "function_declarator_repeat1",
            C::SizedTypeSpecifierRepeat1 => "sized_type_specifier_repeat1",
            C::EnumeratorListRepeat1 => "enumerator_list_repeat1",
            C::FieldDeclarationRepeat1 => "field_declaration_repeat1",
            C::ParameterListRepeat1 => "parameter_list_repeat1",
            C::SwitchBodyRepeat1 => "switch_body_repeat1",
            C::CaseStatementRepeat1 => "case_statement_repeat1",
            C::ArgumentListRepeat1 => "argument_list_repeat1",
            C::InitializerListRepeat1 => "initializer_list_repeat1",
            C::InitializerPairRepeat1 => "initializer_pair_repeat1",
            C::ConcatenatedStringRepeat1 => "concatenated_string_repeat1",
            C::StringLiteralRepeat1 => "string_literal_repeat1",
            C::StatementIdentifier => "statement_identifier",
            C::FieldIdentifier => "field_identifier",
            C::TypeIdentifier => "type_identifier",
            C::Error => "ERROR",
        }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, C> = ::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (13, 165),
        (0, 30),
        (0, 11),
        (0, 4),
        (0, 1),
        (0, 1),
        (0, 6),
        (0, 3),
        (0, 106),
        (0, 0),
        (6, 237),
        (0, 168),
        (0, 0),
        (3, 217),
        (0, 64),
        (0, 3),
        (0, 209),
        (1, 166),
        (0, 68),
        (0, 1),
        (0, 2),
        (0, 26),
        (1, 220),
        (0, 134),
        (0, 170),
        (1, 6),
        (0, 59),
        (0, 137),
        (0, 1),
        (0, 137),
        (0, 83),
        (0, 51),
        (1, 35),
        (6, 121),
        (19, 67),
        (3, 66),
        (0, 31),
        (2, 90),
        (5, 97),
        (0, 56),
        (1, 55),
        (27, 133),
        (5, 23),
        (0, 174),
        (1, 205),
        (40, 123),
        (0, 36),
        (100, 88),
    ]),
    entries: ::phf::Slice::Static(&[
        ("preproc_params", C::PreprocParams),
        ("restrict", C::Restrict),
        ("subscript_designator", C::SubscriptDesignator),
        ("type_descriptor", C::TypeDescriptor),
        (
            "preproc_parenthesized_expression",
            C::PreprocParenthesizedExpression,
        ),
        ("_expression", C::Expression),
        (
            "preproc_if_in_field_declaration_list_repeat1",
            C::PreprocIfInFieldDeclarationListRepeat1,
        ),
        (
            "_declaration_specifiers_no_type",
            C::DeclarationSpecifiersNoType,
        ),
        ("while", C::While),
        ("update_expression", C::UpdateExpression),
        ("comment", C::Comment),
        (",", C::COMMA),
        ("#include", C::HASHinclude),
        ("sized_type_specifier", C::SizedTypeSpecifier),
        ("...", C::DOTDOTDOT),
        ("enumerator_list_repeat1", C::EnumeratorListRepeat1),
        ("case_statement_repeat1", C::CaseStatementRepeat1),
        ("{", C::LBRACE),
        ("while_statement", C::WhileStatement),
        ("continue_statement", C::ContinueStatement),
        ("^=", C::CARETEQ),
        ("switch_statement", C::SwitchStatement),
        ("<=", C::LTEQ),
        ("&=", C::AMPEQ),
        ("parameter_list", C::ParameterList),
        ("field_expression", C::FieldExpression),
        ("if_statement", C::IfStatement),
        ("field_identifier", C::FieldIdentifier),
        ("->", C::DASHGT),
        ("struct_specifier", C::StructSpecifier),
        ("break", C::Break),
        ("preproc_call", C::PreprocCall),
        ("<", C::LT),
        ("return", C::Return),
        ("pointer_declarator", C::PointerDeclarator),
        ("typedef", C::Typedef),
        ("null", C::Null),
        ("(", C::LPAREN),
        ("call_expression", C::CallExpression),
        ("attribute_specifier", C::AttributeSpecifier),
        ("preproc_defined", C::PreprocDefined),
        ("sized_type_specifier_repeat1", C::SizedTypeSpecifierRepeat1),
        ("field_designator", C::FieldDesignator),
        ("preproc_function_def", C::PreprocFunctionDef),
        ("field_declaration_list", C::FieldDeclarationList),
        ("preproc_binary_expression", C::PreprocBinaryExpression),
        ("defined", C::Defined),
        ("preproc_params_token1", C::PreprocParamsToken1),
        ("line_continuation", C::LineContinuation),
        ("__vectorcall", C::Vectorcall),
        ("inline", C::Inline),
        (">", C::GT),
        ("_declaration_specifiers", C::DeclarationSpecifiers),
        ("declaration_repeat1", C::DeclarationRepeat1),
        ("type_definition_repeat1", C::TypeDefinitionRepeat1),
        (">>", C::GTGT),
        ("_declarator", C::Declarator),
        ("field_declaration_repeat1", C::FieldDeclarationRepeat1),
        ("-=", C::DASHEQ),
        ("expression_statement", C::ExpressionStatement),
        ("preproc_include", C::PreprocInclude),
        ("statement_identifier", C::StatementIdentifier),
        ("compound_statement", C::CompoundStatement),
        ("!=", C::BANGEQ),
        ("register", C::Register),
        ("struct", C::Struct),
        ("primitive_type", C::PrimitiveType),
        ("preproc_condition", C::PreprocCondition),
        (">>=", C::GTGTEQ),
        ("abstract_pointer_declarator", C::AbstractPointerDeclarator),
        ("argument_list", C::ArgumentList),
        ("]", C::RBRACK),
        ("switch_body_repeat1", C::SwitchBodyRepeat1),
        ("macro_call", C::MacroCall),
        ("preproc_if", C::PreprocIf),
        ("_type_declarator", C::TypeDeclarator),
        ("comma_expression", C::CommaExpression),
        ("concatenated_string_repeat1", C::ConcatenatedStringRepeat1),
        ("\\\"", C::DQUOTE),
        ("bitfield_clause", C::BitfieldClause),
        ("initializer_list_repeat1", C::InitializerListRepeat1),
        ("<<", C::LTLT),
        ("linkage_specification", C::LinkageSpecification),
        ("return_statement", C::ReturnStatement),
        ("#else", C::HASHelse),
        ("static", C::Static),
        ("compound_literal_expression", C::CompoundLiteralExpression),
        ("enumerator_list", C::EnumeratorList),
        ("&&", C::AMPAMP),
        ("preproc_unary_expression", C::PreprocUnaryExpression),
        ("#ifdef", C::HASHifdef),
        ("&", C::AMP),
        (
            "abstract_parenthesized_declarator",
            C::AbstractParenthesizedDeclarator,
        ),
        ("switch", C::Switch),
        ("function_declarator_repeat1", C::FunctionDeclaratorRepeat1),
        ("signed", C::Signed),
        ("\'", C::SQUOTE),
        ("field_declaration", C::FieldDeclaration),
        ("preproc_elif", C::PreprocElif),
        ("const", C::Const),
        ("true", C::True),
        ("vector", C::Vector),
        ("CALLBACK", C::CALLBACK),
        ("__fastcall", C::Fastcall),
        ("identifier", C::Identifier),
        ("+", C::PLUS),
        ("argument_list_repeat1", C::ArgumentListRepeat1),
        ("declaration", C::Declaration),
        ("subscript_expression", C::SubscriptExpression),
        ("translation_unit", C::TranslationUnit),
        ("preproc_expression_repeat1", C::PreprocExpressionRepeat1),
        ("*", C::STAR),
        ("#ifndef", C::HASHifndef),
        ("initializer_pair_repeat1", C::InitializerPairRepeat1),
        ("enum_specifier", C::EnumSpecifier),
        (":", C::COLON),
        ("|=", C::PIPEEQ),
        ("preproc_def", C::PreprocDef),
        ("__thiscall", C::Thiscall),
        ("||", C::PIPEPIPE),
        ("}", C::RBRACE),
        ("char_literal_token1", C::CharLiteralToken1),
        ("\\n", C::LF),
        ("if", C::If),
        ("|", C::PIPE),
        ("macro", C::Macro),
        ("string_literal_token1", C::StringLiteralToken1),
        ("conditional_expression", C::ConditionalExpression),
        ("sizeof_expression", C::SizeofExpression),
        ("[", C::LBRACK),
        ("ERROR", C::Error),
        ("abstract_array_declarator", C::AbstractArrayDeclarator),
        ("sizeof", C::Sizeof),
        ("*=", C::STAREQ),
        ("preproc_else", C::PreprocElse),
        ("system_lib_string", C::SystemLibString),
        ("/=", C::SLASHEQ),
        ("declaration_list", C::DeclarationList),
        ("#if", C::HASHif),
        ("preproc_arg", C::PreprocArg),
        ("#endif", C::HASHendif),
        ("concatenated_string", C::ConcatenatedString),
        ("call_convention", C::CallConvention),
        (">=", C::GTEQ),
        ("escape_sequence", C::EscapeSequence),
        ("end", C::End),
        ("union_specifier", C::UnionSpecifier),
        ("unsigned", C::Unsigned),
        ("number_literal", C::NumberLiteral),
        (")", C::RPAREN),
        ("__stdcall", C::Stdcall),
        (";", C::SEMI),
        ("goto_statement", C::GotoStatement),
        ("default", C::Default),
        ("char_literal", C::CharLiteral),
        ("for_statement", C::ForStatement),
        ("type_identifier", C::TypeIdentifier),
        (
            "_declaration_specifiers_repeat1",
            C::DeclarationSpecifiersRepeat1,
        ),
        ("else", C::Else),
        ("L\'", C::LSQUOTE),
        ("cast_expression", C::CastExpression),
        ("-", C::DASH),
        ("false", C::False),
        ("#elif", C::HASHelif),
        ("pointer_declarator_repeat1", C::PointerDeclaratorRepeat1),
        ("case_statement", C::CaseStatement),
        ("function_declarator", C::FunctionDeclarator),
        ("unary_expression", C::UnaryExpression),
        ("%", C::PERCENT),
        ("__attribute__", C::Attribute),
        (
            "abstract_function_declarator",
            C::AbstractFunctionDeclarator,
        ),
        ("pointer_expression", C::PointerExpression),
        ("WINAPI", C::WINAPI),
        ("_empty_declaration", C::EmptyDeclaration),
        ("_field_declaration_list_item", C::FieldDeclarationListItem),
        ("binary_expression", C::BinaryExpression),
        ("parameter_declaration", C::ParameterDeclaration),
        ("^", C::CARET),
        ("extern", C::Extern),
        ("function_definition", C::FunctionDefinition),
        ("storage_class_specifier", C::StorageClassSpecifier),
        ("preproc_directive", C::PreprocDirective),
        ("do_statement", C::DoStatement),
        ("do", C::Do),
        ("CONST", C::CONST),
        ("=", C::EQ),
        ("--", C::DASHDASH),
        ("L\\\"", C::LDQUOTE),
        ("short", C::Short),
        (".", C::DOT),
        ("/", C::SLASH),
        ("only_macro_call", C::OnlyMacroCall),
        ("goto", C::Goto),
        ("long", C::Long),
        ("++", C::PLUSPLUS),
        ("break_statement", C::BreakStatement),
        ("union", C::Union),
        ("enumerator", C::Enumerator),
        ("preproc_expression", C::PreprocExpression),
        ("assignment_expression", C::AssignmentExpression),
        ("case", C::Case),
        ("type_qualifier", C::TypeQualifier),
        ("_Atomic", C::Atomic),
        (
            "_declaration_specifiers_repeat2",
            C::DeclarationSpecifiersRepeat2,
        ),
        ("~", C::TILDE),
        ("#define", C::HASHdefine),
        ("only_macro", C::OnlyMacro),
        ("volatile", C::Volatile),
        ("array_declarator", C::ArrayDeclarator),
        ("string_literal", C::StringLiteral),
        ("<<=", C::LTLTEQ),
        ("parenthesized_declarator", C::ParenthesizedDeclarator),
        ("preproc_params_repeat1", C::PreprocParamsRepeat1),
        ("type_definition", C::TypeDefinition),
        ("parameter_list_repeat1", C::ParameterListRepeat1),
        ("for", C::For),
        ("init_declarator", C::InitDeclarator),
        ("enum", C::Enum),
        ("__clrcall", C::Clrcall),
        ("%=", C::PERCENTEQ),
        ("preproc_ifdef", C::PreprocIfdef),
        ("initializer_list", C::InitializerList),
        ("!", C::BANG),
        ("?", C::QMARK),
        ("continue", C::Continue),
        ("labeled_statement", C::LabeledStatement),
        ("_field_declarator", C::FieldDeclarator),
        ("auto", C::Auto),
        ("__cdecl", C::Cdecl),
        ("type_definition_repeat2", C::TypeDefinitionRepeat2),
        ("==", C::EQEQ),
        ("+=", C::PLUSEQ),
        ("translation_unit_repeat1", C::TranslationUnitRepeat1),
        ("initializer_pair", C::InitializerPair),
        ("_type_specifier", C::TypeSpecifier),
        ("string_literal_repeat1", C::StringLiteralRepeat1),
        ("parenthesized_expression", C::ParenthesizedExpression),
        ("_abstract_declarator", C::AbstractDeclarator),
    ]),
};

impl From<&str> for C {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for C {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x as u8) }
    }
}

// C == u16
impl PartialEq<u16> for C {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == C::from(*x)
    }
}

// u16 == C
impl PartialEq<C> for u16 {
    #[inline(always)]
    fn eq(&self, x: &C) -> bool {
        *x == *self
    }
}
