// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum Rust {
    End = 0,
    Identifier = 1,
    SEMI = 2,
    MacroRulesBANG = 3,
    LPAREN = 4,
    RPAREN = 5,
    LBRACE = 6,
    RBRACE = 7,
    EQGT = 8,
    LBRACK = 9,
    RBRACK = 10,
    COLON = 11,
    DOLLAR = 12,
    TokenRepetitionPatternToken1 = 13,
    PLUS = 14,
    STAR = 15,
    Ident = 16,
    Path = 17,
    Expr = 18,
    Ty = 19,
    Pat = 20,
    Stmt = 21,
    Block = 22,
    Item = 23,
    Meta = 24,
    Tt = 25,
    U8 = 26,
    I8 = 27,
    U16 = 28,
    I16 = 29,
    U32 = 30,
    I32 = 31,
    U64 = 32,
    I64 = 33,
    U128 = 34,
    I128 = 35,
    Isize = 36,
    Usize = 37,
    F32 = 38,
    F64 = 39,
    Bool = 40,
    Str = 41,
    Char = 42,
    NonSpecialTokenToken1 = 43,
    As = 44,
    Async = 45,
    Await = 46,
    Break = 47,
    Const = 48,
    Continue = 49,
    Default = 50,
    Enum = 51,
    Fn = 52,
    For = 53,
    If = 54,
    Impl = 55,
    Let = 56,
    Loop = 57,
    Match = 58,
    Mod = 59,
    Pub = 60,
    Return = 61,
    Static = 62,
    Struct = 63,
    Trait = 64,
    Type = 65,
    Union = 66,
    Unsafe = 67,
    Use = 68,
    Where = 69,
    While = 70,
    HASH = 71,
    BANG = 72,
    EQ = 73,
    COMMA = 74,
    Extern = 75,
    Ref = 76,
    DASHGT = 77,
    QMARK = 78,
    LT = 79,
    GT = 80,
    COLONCOLON = 81,
    UNDERSCORE = 82,
    AMP = 83,
    DOTDOTDOT = 84,
    In = 85,
    SQUOTE = 86,
    Dyn = 87,
    MutableSpecifier = 88,
    DOTDOT = 89,
    DOTDOTEQ = 90,
    DASH = 91,
    AMPAMP = 92,
    PIPEPIPE = 93,
    PIPE = 94,
    CARET = 95,
    EQEQ = 96,
    BANGEQ = 97,
    LTEQ = 98,
    GTEQ = 99,
    LTLT = 100,
    GTGT = 101,
    SLASH = 102,
    PERCENT = 103,
    PLUSEQ = 104,
    DASHEQ = 105,
    STAREQ = 106,
    SLASHEQ = 107,
    PERCENTEQ = 108,
    AMPEQ = 109,
    PIPEEQ = 110,
    CARETEQ = 111,
    LTLTEQ = 112,
    GTGTEQ = 113,
    Else = 114,
    Move = 115,
    DOT = 116,
    AT = 117,
    IntegerLiteral = 118,
    DQUOTE = 119,
    DQUOTE2 = 120,
    CharLiteral = 121,
    EscapeSequence = 122,
    True = 123,
    False = 124,
    LineComment = 125,
    Zelf = 126,
    Super = 127,
    Crate = 128,
    Metavariable = 129,
    StringContent = 130,
    RawStringLiteral = 131,
    FloatLiteral = 132,
    BlockComment = 133,
    SourceFile = 134,
    Statement = 135,
    EmptyStatement = 136,
    ExpressionStatement = 137,
    MacroDefinition = 138,
    MacroRule = 139,
    TokenPattern = 140,
    TokenTreePattern = 141,
    TokenBindingPattern = 142,
    TokenRepetitionPattern = 143,
    FragmentSpecifier = 144,
    TokenTree = 145,
    TokenRepetition = 146,
    AttributeItem = 147,
    InnerAttributeItem = 148,
    MetaItem = 149,
    MetaArguments = 150,
    ModItem = 151,
    ForeignModItem = 152,
    DeclarationList = 153,
    StructItem = 154,
    UnionItem = 155,
    EnumItem = 156,
    EnumVariantList = 157,
    EnumVariant = 158,
    FieldDeclarationList = 159,
    FieldDeclaration = 160,
    OrderedFieldDeclarationList = 161,
    ExternCrateDeclaration = 162,
    ConstItem = 163,
    StaticItem = 164,
    TypeItem = 165,
    FunctionItem = 166,
    FunctionSignatureItem = 167,
    FunctionModifiers = 168,
    WhereClause = 169,
    WherePredicate = 170,
    ImplItem = 171,
    TraitItem = 172,
    AssociatedType = 173,
    TraitBounds = 174,
    HigherRankedTraitBound = 175,
    RemovedTraitBound = 176,
    TypeParameters = 177,
    ConstrainedTypeParameter = 178,
    OptionalTypeParameter = 179,
    LetDeclaration = 180,
    UseDeclaration = 181,
    UseClause = 182,
    ScopedUseList = 183,
    UseList = 184,
    UseAsClause = 185,
    UseWildcard = 186,
    Parameters = 187,
    SelfParameter = 188,
    VariadicParameter = 189,
    Parameter = 190,
    ExternModifier = 191,
    VisibilityModifier = 192,
    Type2 = 193,
    BracketedType = 194,
    QualifiedType = 195,
    Lifetime = 196,
    ArrayType = 197,
    ForLifetimes = 198,
    FunctionType = 199,
    TupleType = 200,
    UnitType = 201,
    GenericFunction = 202,
    GenericType = 203,
    GenericTypeWithTurbofish = 204,
    BoundedType = 205,
    TypeArguments = 206,
    TypeBinding = 207,
    ReferenceType = 208,
    PointerType = 209,
    EmptyType = 210,
    AbstractType = 211,
    DynamicType = 212,
    Expression = 213,
    MacroInvocation = 214,
    ScopedIdentifier = 215,
    ScopedTypeIdentifier = 216,
    ScopedTypeIdentifier2 = 217,
    RangeExpression = 218,
    UnaryExpression = 219,
    TryExpression = 220,
    ReferenceExpression = 221,
    BinaryExpression = 222,
    AssignmentExpression = 223,
    CompoundAssignmentExpr = 224,
    TypeCastExpression = 225,
    ReturnExpression = 226,
    CallExpression = 227,
    Arguments = 228,
    ArrayExpression = 229,
    ParenthesizedExpression = 230,
    TupleExpression = 231,
    UnitExpression = 232,
    StructExpression = 233,
    FieldInitializerList = 234,
    ShorthandFieldInitializer = 235,
    FieldInitializer = 236,
    BaseFieldInitializer = 237,
    IfExpression = 238,
    IfLetExpression = 239,
    ElseTail = 240,
    MatchExpression = 241,
    MatchBlock = 242,
    MatchArm = 243,
    MatchArm2 = 244,
    MatchPattern = 245,
    WhileExpression = 246,
    WhileLetExpression = 247,
    LoopExpression = 248,
    ForExpression = 249,
    ClosureExpression = 250,
    ClosureParameters = 251,
    LoopLabel = 252,
    BreakExpression = 253,
    ContinueExpression = 254,
    IndexExpression = 255,
    AwaitExpression = 256,
    FieldExpression = 257,
    UnsafeBlock = 258,
    AsyncBlock = 259,
    Block2 = 260,
    Pattern = 261,
    TuplePattern = 262,
    SlicePattern = 263,
    TupleStructPattern = 264,
    StructPattern = 265,
    FieldPattern = 266,
    RemainingFieldPattern = 267,
    MutPattern = 268,
    RangePattern = 269,
    RefPattern = 270,
    CapturedPattern = 271,
    ReferencePattern = 272,
    Literal = 273,
    LiteralPattern = 274,
    NegativeLiteral = 275,
    StringLiteral = 276,
    BooleanLiteral = 277,
    SourceFileRepeat1 = 278,
    MacroDefinitionRepeat1 = 279,
    TokenTreePatternRepeat1 = 280,
    TokenTreeRepeat1 = 281,
    MetaArgumentsRepeat1 = 282,
    DeclarationListRepeat1 = 283,
    EnumVariantListRepeat1 = 284,
    EnumVariantListRepeat2 = 285,
    FieldDeclarationListRepeat1 = 286,
    OrderedFieldDeclarationListRepeat1 = 287,
    FunctionModifiersRepeat1 = 288,
    WhereClauseRepeat1 = 289,
    TraitBoundsRepeat1 = 290,
    TypeParametersRepeat1 = 291,
    UseListRepeat1 = 292,
    ParametersRepeat1 = 293,
    ForLifetimesRepeat1 = 294,
    TupleTypeRepeat1 = 295,
    TypeArgumentsRepeat1 = 296,
    ArgumentsRepeat1 = 297,
    ArrayExpressionRepeat1 = 298,
    TupleExpressionRepeat1 = 299,
    FieldInitializerListRepeat1 = 300,
    MatchBlockRepeat1 = 301,
    MatchPatternRepeat1 = 302,
    ClosureParametersRepeat1 = 303,
    TuplePatternRepeat1 = 304,
    StructPatternRepeat1 = 305,
    StringLiteralRepeat1 = 306,
    FieldIdentifier = 307,
    PrimitiveType = 308,
    ShorthandFieldIdentifier = 309,
    TypeIdentifier = 310,
    Error = 311,
}

impl Into<&'static str> for Rust {
    fn into(self) -> &'static str {
        match self {
            Rust::End => "end",
            Rust::Identifier => "identifier",
            Rust::SEMI => ";",
            Rust::MacroRulesBANG => "macro_rules!",
            Rust::LPAREN => "(",
            Rust::RPAREN => ")",
            Rust::LBRACE => "{",
            Rust::RBRACE => "}",
            Rust::EQGT => "=>",
            Rust::LBRACK => "[",
            Rust::RBRACK => "]",
            Rust::COLON => ":",
            Rust::DOLLAR => "$",
            Rust::TokenRepetitionPatternToken1 => "token_repetition_pattern_token1",
            Rust::PLUS => "+",
            Rust::STAR => "*",
            Rust::Ident => "ident",
            Rust::Path => "path",
            Rust::Expr => "expr",
            Rust::Ty => "ty",
            Rust::Pat => "pat",
            Rust::Stmt => "stmt",
            Rust::Block => "block",
            Rust::Item => "item",
            Rust::Meta => "meta",
            Rust::Tt => "tt",
            Rust::U8 => "u8",
            Rust::I8 => "i8",
            Rust::U16 => "u16",
            Rust::I16 => "i16",
            Rust::U32 => "u32",
            Rust::I32 => "i32",
            Rust::U64 => "u64",
            Rust::I64 => "i64",
            Rust::U128 => "u128",
            Rust::I128 => "i128",
            Rust::Isize => "isize",
            Rust::Usize => "usize",
            Rust::F32 => "f32",
            Rust::F64 => "f64",
            Rust::Bool => "bool",
            Rust::Str => "str",
            Rust::Char => "char",
            Rust::NonSpecialTokenToken1 => "_non_special_token_token1",
            Rust::As => "as",
            Rust::Async => "async",
            Rust::Await => "await",
            Rust::Break => "break",
            Rust::Const => "const",
            Rust::Continue => "continue",
            Rust::Default => "default",
            Rust::Enum => "enum",
            Rust::Fn => "fn",
            Rust::For => "for",
            Rust::If => "if",
            Rust::Impl => "impl",
            Rust::Let => "let",
            Rust::Loop => "loop",
            Rust::Match => "match",
            Rust::Mod => "mod",
            Rust::Pub => "pub",
            Rust::Return => "return",
            Rust::Static => "static",
            Rust::Struct => "struct",
            Rust::Trait => "trait",
            Rust::Type => "type",
            Rust::Union => "union",
            Rust::Unsafe => "unsafe",
            Rust::Use => "use",
            Rust::Where => "where",
            Rust::While => "while",
            Rust::HASH => "#",
            Rust::BANG => "!",
            Rust::EQ => "=",
            Rust::COMMA => ",",
            Rust::Extern => "extern",
            Rust::Ref => "ref",
            Rust::DASHGT => "->",
            Rust::QMARK => "?",
            Rust::LT => "<",
            Rust::GT => ">",
            Rust::COLONCOLON => "::",
            Rust::UNDERSCORE => "_",
            Rust::AMP => "&",
            Rust::DOTDOTDOT => "...",
            Rust::In => "in",
            Rust::SQUOTE => "'",
            Rust::Dyn => "dyn",
            Rust::MutableSpecifier => "mutable_specifier",
            Rust::DOTDOT => "..",
            Rust::DOTDOTEQ => "..=",
            Rust::DASH => "-",
            Rust::AMPAMP => "&&",
            Rust::PIPEPIPE => "||",
            Rust::PIPE => "|",
            Rust::CARET => "^",
            Rust::EQEQ => "==",
            Rust::BANGEQ => "!=",
            Rust::LTEQ => "<=",
            Rust::GTEQ => ">=",
            Rust::LTLT => "<<",
            Rust::GTGT => ">>",
            Rust::SLASH => "/",
            Rust::PERCENT => "%",
            Rust::PLUSEQ => "+=",
            Rust::DASHEQ => "-=",
            Rust::STAREQ => "*=",
            Rust::SLASHEQ => "/=",
            Rust::PERCENTEQ => "%=",
            Rust::AMPEQ => "&=",
            Rust::PIPEEQ => "|=",
            Rust::CARETEQ => "^=",
            Rust::LTLTEQ => "<<=",
            Rust::GTGTEQ => ">>=",
            Rust::Else => "else",
            Rust::Move => "move",
            Rust::DOT => ".",
            Rust::AT => "@",
            Rust::IntegerLiteral => "integer_literal",
            Rust::DQUOTE => "\"",
            Rust::DQUOTE2 => "\"",
            Rust::CharLiteral => "char_literal",
            Rust::EscapeSequence => "escape_sequence",
            Rust::True => "true",
            Rust::False => "false",
            Rust::LineComment => "line_comment",
            Rust::Zelf => "self",
            Rust::Super => "super",
            Rust::Crate => "crate",
            Rust::Metavariable => "metavariable",
            Rust::StringContent => "_string_content",
            Rust::RawStringLiteral => "raw_string_literal",
            Rust::FloatLiteral => "float_literal",
            Rust::BlockComment => "block_comment",
            Rust::SourceFile => "source_file",
            Rust::Statement => "_statement",
            Rust::EmptyStatement => "empty_statement",
            Rust::ExpressionStatement => "_expression_statement",
            Rust::MacroDefinition => "macro_definition",
            Rust::MacroRule => "macro_rule",
            Rust::TokenPattern => "_token_pattern",
            Rust::TokenTreePattern => "token_tree_pattern",
            Rust::TokenBindingPattern => "token_binding_pattern",
            Rust::TokenRepetitionPattern => "token_repetition_pattern",
            Rust::FragmentSpecifier => "fragment_specifier",
            Rust::TokenTree => "token_tree",
            Rust::TokenRepetition => "token_repetition",
            Rust::AttributeItem => "attribute_item",
            Rust::InnerAttributeItem => "inner_attribute_item",
            Rust::MetaItem => "meta_item",
            Rust::MetaArguments => "meta_arguments",
            Rust::ModItem => "mod_item",
            Rust::ForeignModItem => "foreign_mod_item",
            Rust::DeclarationList => "declaration_list",
            Rust::StructItem => "struct_item",
            Rust::UnionItem => "union_item",
            Rust::EnumItem => "enum_item",
            Rust::EnumVariantList => "enum_variant_list",
            Rust::EnumVariant => "enum_variant",
            Rust::FieldDeclarationList => "field_declaration_list",
            Rust::FieldDeclaration => "field_declaration",
            Rust::OrderedFieldDeclarationList => "ordered_field_declaration_list",
            Rust::ExternCrateDeclaration => "extern_crate_declaration",
            Rust::ConstItem => "const_item",
            Rust::StaticItem => "static_item",
            Rust::TypeItem => "type_item",
            Rust::FunctionItem => "function_item",
            Rust::FunctionSignatureItem => "function_signature_item",
            Rust::FunctionModifiers => "function_modifiers",
            Rust::WhereClause => "where_clause",
            Rust::WherePredicate => "where_predicate",
            Rust::ImplItem => "impl_item",
            Rust::TraitItem => "trait_item",
            Rust::AssociatedType => "associated_type",
            Rust::TraitBounds => "trait_bounds",
            Rust::HigherRankedTraitBound => "higher_ranked_trait_bound",
            Rust::RemovedTraitBound => "removed_trait_bound",
            Rust::TypeParameters => "type_parameters",
            Rust::ConstrainedTypeParameter => "constrained_type_parameter",
            Rust::OptionalTypeParameter => "optional_type_parameter",
            Rust::LetDeclaration => "let_declaration",
            Rust::UseDeclaration => "use_declaration",
            Rust::UseClause => "_use_clause",
            Rust::ScopedUseList => "scoped_use_list",
            Rust::UseList => "use_list",
            Rust::UseAsClause => "use_as_clause",
            Rust::UseWildcard => "use_wildcard",
            Rust::Parameters => "parameters",
            Rust::SelfParameter => "self_parameter",
            Rust::VariadicParameter => "variadic_parameter",
            Rust::Parameter => "parameter",
            Rust::ExternModifier => "extern_modifier",
            Rust::VisibilityModifier => "visibility_modifier",
            Rust::Type2 => "_type",
            Rust::BracketedType => "bracketed_type",
            Rust::QualifiedType => "qualified_type",
            Rust::Lifetime => "lifetime",
            Rust::ArrayType => "array_type",
            Rust::ForLifetimes => "for_lifetimes",
            Rust::FunctionType => "function_type",
            Rust::TupleType => "tuple_type",
            Rust::UnitType => "unit_type",
            Rust::GenericFunction => "generic_function",
            Rust::GenericType => "generic_type",
            Rust::GenericTypeWithTurbofish => "generic_type_with_turbofish",
            Rust::BoundedType => "bounded_type",
            Rust::TypeArguments => "type_arguments",
            Rust::TypeBinding => "type_binding",
            Rust::ReferenceType => "reference_type",
            Rust::PointerType => "pointer_type",
            Rust::EmptyType => "empty_type",
            Rust::AbstractType => "abstract_type",
            Rust::DynamicType => "dynamic_type",
            Rust::Expression => "_expression",
            Rust::MacroInvocation => "macro_invocation",
            Rust::ScopedIdentifier => "scoped_identifier",
            Rust::ScopedTypeIdentifier => "scoped_type_identifier",
            Rust::ScopedTypeIdentifier2 => "scoped_type_identifier",
            Rust::RangeExpression => "range_expression",
            Rust::UnaryExpression => "unary_expression",
            Rust::TryExpression => "try_expression",
            Rust::ReferenceExpression => "reference_expression",
            Rust::BinaryExpression => "binary_expression",
            Rust::AssignmentExpression => "assignment_expression",
            Rust::CompoundAssignmentExpr => "compound_assignment_expr",
            Rust::TypeCastExpression => "type_cast_expression",
            Rust::ReturnExpression => "return_expression",
            Rust::CallExpression => "call_expression",
            Rust::Arguments => "arguments",
            Rust::ArrayExpression => "array_expression",
            Rust::ParenthesizedExpression => "parenthesized_expression",
            Rust::TupleExpression => "tuple_expression",
            Rust::UnitExpression => "unit_expression",
            Rust::StructExpression => "struct_expression",
            Rust::FieldInitializerList => "field_initializer_list",
            Rust::ShorthandFieldInitializer => "shorthand_field_initializer",
            Rust::FieldInitializer => "field_initializer",
            Rust::BaseFieldInitializer => "base_field_initializer",
            Rust::IfExpression => "if_expression",
            Rust::IfLetExpression => "if_let_expression",
            Rust::ElseTail => "_else_tail",
            Rust::MatchExpression => "match_expression",
            Rust::MatchBlock => "match_block",
            Rust::MatchArm => "match_arm",
            Rust::MatchArm2 => "match_arm",
            Rust::MatchPattern => "match_pattern",
            Rust::WhileExpression => "while_expression",
            Rust::WhileLetExpression => "while_let_expression",
            Rust::LoopExpression => "loop_expression",
            Rust::ForExpression => "for_expression",
            Rust::ClosureExpression => "closure_expression",
            Rust::ClosureParameters => "closure_parameters",
            Rust::LoopLabel => "loop_label",
            Rust::BreakExpression => "break_expression",
            Rust::ContinueExpression => "continue_expression",
            Rust::IndexExpression => "index_expression",
            Rust::AwaitExpression => "await_expression",
            Rust::FieldExpression => "field_expression",
            Rust::UnsafeBlock => "unsafe_block",
            Rust::AsyncBlock => "async_block",
            Rust::Block2 => "block",
            Rust::Pattern => "_pattern",
            Rust::TuplePattern => "tuple_pattern",
            Rust::SlicePattern => "slice_pattern",
            Rust::TupleStructPattern => "tuple_struct_pattern",
            Rust::StructPattern => "struct_pattern",
            Rust::FieldPattern => "field_pattern",
            Rust::RemainingFieldPattern => "remaining_field_pattern",
            Rust::MutPattern => "mut_pattern",
            Rust::RangePattern => "range_pattern",
            Rust::RefPattern => "ref_pattern",
            Rust::CapturedPattern => "captured_pattern",
            Rust::ReferencePattern => "reference_pattern",
            Rust::Literal => "_literal",
            Rust::LiteralPattern => "_literal_pattern",
            Rust::NegativeLiteral => "negative_literal",
            Rust::StringLiteral => "string_literal",
            Rust::BooleanLiteral => "boolean_literal",
            Rust::SourceFileRepeat1 => "source_file_repeat1",
            Rust::MacroDefinitionRepeat1 => "macro_definition_repeat1",
            Rust::TokenTreePatternRepeat1 => "token_tree_pattern_repeat1",
            Rust::TokenTreeRepeat1 => "token_tree_repeat1",
            Rust::MetaArgumentsRepeat1 => "meta_arguments_repeat1",
            Rust::DeclarationListRepeat1 => "declaration_list_repeat1",
            Rust::EnumVariantListRepeat1 => "enum_variant_list_repeat1",
            Rust::EnumVariantListRepeat2 => "enum_variant_list_repeat2",
            Rust::FieldDeclarationListRepeat1 => "field_declaration_list_repeat1",
            Rust::OrderedFieldDeclarationListRepeat1 => "ordered_field_declaration_list_repeat1",
            Rust::FunctionModifiersRepeat1 => "function_modifiers_repeat1",
            Rust::WhereClauseRepeat1 => "where_clause_repeat1",
            Rust::TraitBoundsRepeat1 => "trait_bounds_repeat1",
            Rust::TypeParametersRepeat1 => "type_parameters_repeat1",
            Rust::UseListRepeat1 => "use_list_repeat1",
            Rust::ParametersRepeat1 => "parameters_repeat1",
            Rust::ForLifetimesRepeat1 => "for_lifetimes_repeat1",
            Rust::TupleTypeRepeat1 => "tuple_type_repeat1",
            Rust::TypeArgumentsRepeat1 => "type_arguments_repeat1",
            Rust::ArgumentsRepeat1 => "arguments_repeat1",
            Rust::ArrayExpressionRepeat1 => "array_expression_repeat1",
            Rust::TupleExpressionRepeat1 => "tuple_expression_repeat1",
            Rust::FieldInitializerListRepeat1 => "field_initializer_list_repeat1",
            Rust::MatchBlockRepeat1 => "match_block_repeat1",
            Rust::MatchPatternRepeat1 => "match_pattern_repeat1",
            Rust::ClosureParametersRepeat1 => "closure_parameters_repeat1",
            Rust::TuplePatternRepeat1 => "tuple_pattern_repeat1",
            Rust::StructPatternRepeat1 => "struct_pattern_repeat1",
            Rust::StringLiteralRepeat1 => "string_literal_repeat1",
            Rust::FieldIdentifier => "field_identifier",
            Rust::PrimitiveType => "primitive_type",
            Rust::ShorthandFieldIdentifier => "shorthand_field_identifier",
            Rust::TypeIdentifier => "type_identifier",
            Rust::Error => "ERROR",
        }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, Rust> = ::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (0, 136),
        (0, 0),
        (0, 3),
        (1, 170),
        (0, 80),
        (0, 7),
        (4, 73),
        (0, 0),
        (0, 23),
        (0, 1),
        (0, 17),
        (6, 294),
        (0, 162),
        (3, 163),
        (1, 4),
        (2, 81),
        (0, 10),
        (0, 0),
        (0, 0),
        (0, 5),
        (0, 50),
        (0, 162),
        (0, 6),
        (0, 0),
        (0, 16),
        (1, 1),
        (2, 276),
        (0, 68),
        (0, 56),
        (0, 276),
        (46, 73),
        (5, 3),
        (1, 259),
        (0, 28),
        (0, 69),
        (0, 0),
        (0, 62),
        (9, 133),
        (2, 64),
        (0, 18),
        (13, 195),
        (1, 115),
        (0, 56),
        (9, 192),
        (1, 302),
        (1, 1),
        (0, 18),
        (1, 13),
        (0, 1),
        (0, 123),
        (0, 2),
        (0, 4),
        (11, 68),
        (18, 40),
        (6, 139),
        (0, 164),
        (0, 5),
        (1, 7),
        (10, 184),
        (1, 60),
        (0, 1),
        (1, 66),
    ]),
    entries: ::phf::Slice::Static(&[
        ("false", Rust::False),
        ("field_expression", Rust::FieldExpression),
        ("foreign_mod_item", Rust::ForeignModItem),
        ("captured_pattern", Rust::CapturedPattern),
        ("_pattern", Rust::Pattern),
        ("=", Rust::EQ),
        ("tuple_pattern", Rust::TuplePattern),
        (">>=", Rust::GTGTEQ),
        (")", Rust::RPAREN),
        ("bool", Rust::Bool),
        ("match_expression", Rust::MatchExpression),
        ("^", Rust::CARET),
        ("tuple_expression_repeat1", Rust::TupleExpressionRepeat1),
        ("macro_rules!", Rust::MacroRulesBANG),
        ("primitive_type", Rust::PrimitiveType),
        ("_else_tail", Rust::ElseTail),
        ("type_cast_expression", Rust::TypeCastExpression),
        ("..", Rust::DOTDOT),
        ("#", Rust::HASH),
        ("function_item", Rust::FunctionItem),
        ("if_expression", Rust::IfExpression),
        ("_expression_statement", Rust::ExpressionStatement),
        ("match", Rust::Match),
        ("struct_pattern_repeat1", Rust::StructPatternRepeat1),
        ("match_block_repeat1", Rust::MatchBlockRepeat1),
        ("shorthand_field_identifier", Rust::ShorthandFieldIdentifier),
        ("return", Rust::Return),
        ("_literal", Rust::Literal),
        ("f32", Rust::F32),
        ("field_pattern", Rust::FieldPattern),
        (
            "field_initializer_list_repeat1",
            Rust::FieldInitializerListRepeat1,
        ),
        ("empty_type", Rust::EmptyType),
        ("(", Rust::LPAREN),
        ("crate", Rust::Crate),
        ("super", Rust::Super),
        ("meta", Rust::Meta),
        (
            "shorthand_field_initializer",
            Rust::ShorthandFieldInitializer,
        ),
        ("match_arm", Rust::MatchArm),
        ("macro_definition", Rust::MacroDefinition),
        ("end", Rust::End),
        ("<", Rust::LT),
        ("union_item", Rust::UnionItem),
        ("function_modifiers_repeat1", Rust::FunctionModifiersRepeat1),
        ("identifier", Rust::Identifier),
        ("macro_rule", Rust::MacroRule),
        ("associated_type", Rust::AssociatedType),
        ("*=", Rust::STAREQ),
        ("ref_pattern", Rust::RefPattern),
        ("i32", Rust::I32),
        ("usize", Rust::Usize),
        ("string_literal_repeat1", Rust::StringLiteralRepeat1),
        ("boolean_literal", Rust::BooleanLiteral),
        ("u32", Rust::U32),
        ("^=", Rust::CARETEQ),
        ("::", Rust::COLONCOLON),
        ("index_expression", Rust::IndexExpression),
        ("i16", Rust::I16),
        ("token_binding_pattern", Rust::TokenBindingPattern),
        ("default", Rust::Default),
        ("[", Rust::LBRACK),
        ("_literal_pattern", Rust::LiteralPattern),
        ("%=", Rust::PERCENTEQ),
        ("metavariable", Rust::Metavariable),
        (";", Rust::SEMI),
        ("trait_item", Rust::TraitItem),
        ("macro_definition_repeat1", Rust::MacroDefinitionRepeat1),
        ("empty_statement", Rust::EmptyStatement),
        ("_use_clause", Rust::UseClause),
        ("generic_function", Rust::GenericFunction),
        ("declaration_list_repeat1", Rust::DeclarationListRepeat1),
        ("array_type", Rust::ArrayType),
        ("parameter", Rust::Parameter),
        ("slice_pattern", Rust::SlicePattern),
        ("range_pattern", Rust::RangePattern),
        ("isize", Rust::Isize),
        ("union", Rust::Union),
        ("async", Rust::Async),
        ("for_lifetimes_repeat1", Rust::ForLifetimesRepeat1),
        ("function_modifiers", Rust::FunctionModifiers),
        ("trait_bounds_repeat1", Rust::TraitBoundsRepeat1),
        ("-=", Rust::DASHEQ),
        ("for_expression", Rust::ForExpression),
        ("%", Rust::PERCENT),
        ("source_file", Rust::SourceFile),
        ("_token_pattern", Rust::TokenPattern),
        ("type_identifier", Rust::TypeIdentifier),
        ("enum_variant_list", Rust::EnumVariantList),
        ("const", Rust::Const),
        ("u128", Rust::U128),
        ("stmt", Rust::Stmt),
        ("range_expression", Rust::RangeExpression),
        ("tuple_struct_pattern", Rust::TupleStructPattern),
        ("binary_expression", Rust::BinaryExpression),
        ("as", Rust::As),
        ("type_parameters", Rust::TypeParameters),
        ("+=", Rust::PLUSEQ),
        ("closure_expression", Rust::ClosureExpression),
        ("struct_expression", Rust::StructExpression),
        ("closure_parameters", Rust::ClosureParameters),
        ("abstract_type", Rust::AbstractType),
        ("_non_special_token_token1", Rust::NonSpecialTokenToken1),
        ("let", Rust::Let),
        (">", Rust::GT),
        (",", Rust::COMMA),
        ("parameters", Rust::Parameters),
        ("bounded_type", Rust::BoundedType),
        ("fragment_specifier", Rust::FragmentSpecifier),
        ("unsafe_block", Rust::UnsafeBlock),
        ("reference_type", Rust::ReferenceType),
        ("source_file_repeat1", Rust::SourceFileRepeat1),
        ("type_binding", Rust::TypeBinding),
        ("type", Rust::Type),
        ("match_pattern_repeat1", Rust::MatchPatternRepeat1),
        ("float_literal", Rust::FloatLiteral),
        ("unsafe", Rust::Unsafe),
        ("token_tree_repeat1", Rust::TokenTreeRepeat1),
        ("move", Rust::Move),
        ("i128", Rust::I128),
        ("break_expression", Rust::BreakExpression),
        ("token_repetition_pattern", Rust::TokenRepetitionPattern),
        ("/", Rust::SLASH),
        ("self_parameter", Rust::SelfParameter),
        ("static", Rust::Static),
        ("match_pattern", Rust::MatchPattern),
        ("block_comment", Rust::BlockComment),
        ("trait_bounds", Rust::TraitBounds),
        ("arguments", Rust::Arguments),
        ("enum", Rust::Enum),
        ("i8", Rust::I8),
        ("impl", Rust::Impl),
        (
            "generic_type_with_turbofish",
            Rust::GenericTypeWithTurbofish,
        ),
        ("try_expression", Rust::TryExpression),
        ("arguments_repeat1", Rust::ArgumentsRepeat1),
        ("meta_item", Rust::MetaItem),
        ("where_clause_repeat1", Rust::WhereClauseRepeat1),
        ("type_arguments_repeat1", Rust::TypeArgumentsRepeat1),
        (">>", Rust::GTGT),
        ("if_let_expression", Rust::IfLetExpression),
        ("function_signature_item", Rust::FunctionSignatureItem),
        ("continue_expression", Rust::ContinueExpression),
        ("visibility_modifier", Rust::VisibilityModifier),
        ("type_parameters_repeat1", Rust::TypeParametersRepeat1),
        (
            "ordered_field_declaration_list",
            Rust::OrderedFieldDeclarationList,
        ),
        ("loop", Rust::Loop),
        ("=>", Rust::EQGT),
        ("generic_type", Rust::GenericType),
        ("const_item", Rust::ConstItem),
        ("parameters_repeat1", Rust::ParametersRepeat1),
        ("tuple_pattern_repeat1", Rust::TuplePatternRepeat1),
        ("enum_variant_list_repeat1", Rust::EnumVariantListRepeat1),
        ("removed_trait_bound", Rust::RemovedTraitBound),
        ("$", Rust::DOLLAR),
        ("variadic_parameter", Rust::VariadicParameter),
        ("field_initializer", Rust::FieldInitializer),
        ("...", Rust::DOTDOTDOT),
        ("in", Rust::In),
        ("dyn", Rust::Dyn),
        ("token_tree_pattern", Rust::TokenTreePattern),
        ("|", Rust::PIPE),
        ("return_expression", Rust::ReturnExpression),
        ("macro_invocation", Rust::MacroInvocation),
        ("extern_crate_declaration", Rust::ExternCrateDeclaration),
        ("ERROR", Rust::Error),
        ("fn", Rust::Fn),
        ("tt", Rust::Tt),
        ("!=", Rust::BANGEQ),
        (
            "field_declaration_list_repeat1",
            Rust::FieldDeclarationListRepeat1,
        ),
        ("meta_arguments_repeat1", Rust::MetaArgumentsRepeat1),
        ("field_identifier", Rust::FieldIdentifier),
        ("use", Rust::Use),
        ("continue", Rust::Continue),
        ("{", Rust::LBRACE),
        ("item", Rust::Item),
        ("type_arguments", Rust::TypeArguments),
        ("tuple_type_repeat1", Rust::TupleTypeRepeat1),
        ("ident", Rust::Ident),
        ("!", Rust::BANG),
        ("compound_assignment_expr", Rust::CompoundAssignmentExpr),
        ("u16", Rust::U16),
        ("struct_item", Rust::StructItem),
        ("struct_pattern", Rust::StructPattern),
        ("let_declaration", Rust::LetDeclaration),
        ("tuple_expression", Rust::TupleExpression),
        (
            "ordered_field_declaration_list_repeat1",
            Rust::OrderedFieldDeclarationListRepeat1,
        ),
        ("use_wildcard", Rust::UseWildcard),
        ("if", Rust::If),
        ("token_tree", Rust::TokenTree),
        ("use_declaration", Rust::UseDeclaration),
        ("scoped_identifier", Rust::ScopedIdentifier),
        ("str", Rust::Str),
        ("extern", Rust::Extern),
        ("<=", Rust::LTEQ),
        ("f64", Rust::F64),
        ("line_comment", Rust::LineComment),
        ("call_expression", Rust::CallExpression),
        ("expr", Rust::Expr),
        ("..=", Rust::DOTDOTEQ),
        ("-", Rust::DASH),
        ("}", Rust::RBRACE),
        ("mut_pattern", Rust::MutPattern),
        ("trait", Rust::Trait),
        ("*", Rust::STAR),
        ("integer_literal", Rust::IntegerLiteral),
        ("pointer_type", Rust::PointerType),
        ("&&", Rust::AMPAMP),
        ("string_literal", Rust::StringLiteral),
        ("inner_attribute_item", Rust::InnerAttributeItem),
        ("match_block", Rust::MatchBlock),
        (".", Rust::DOT),
        ("+", Rust::PLUS),
        ("enum_item", Rust::EnumItem),
        ("field_declaration_list", Rust::FieldDeclarationList),
        ("while_let_expression", Rust::WhileLetExpression),
        ("attribute_item", Rust::AttributeItem),
        ("mod_item", Rust::ModItem),
        ("self", Rust::Zelf),
        ("await_expression", Rust::AwaitExpression),
        ("async_block", Rust::AsyncBlock),
        ("where_clause", Rust::WhereClause),
        ("impl_item", Rust::ImplItem),
        ("==", Rust::EQEQ),
        ("scoped_use_list", Rust::ScopedUseList),
        ("meta_arguments", Rust::MetaArguments),
        ("array_expression_repeat1", Rust::ArrayExpressionRepeat1),
        ("parenthesized_expression", Rust::ParenthesizedExpression),
        ("->", Rust::DASHGT),
        ("u8", Rust::U8),
        ("pub", Rust::Pub),
        ("unit_expression", Rust::UnitExpression),
        ("/=", Rust::SLASHEQ),
        ("await", Rust::Await),
        ("\\\"", Rust::DQUOTE),
        ("field_declaration", Rust::FieldDeclaration),
        ("qualified_type", Rust::QualifiedType),
        ("remaining_field_pattern", Rust::RemainingFieldPattern),
        ("&", Rust::AMP),
        (":", Rust::COLON),
        ("enum_variant", Rust::EnumVariant),
        ("true", Rust::True),
        ("@", Rust::AT),
        ("char_literal", Rust::CharLiteral),
        ("bracketed_type", Rust::BracketedType),
        ("<<", Rust::LTLT),
        ("ty", Rust::Ty),
        ("closure_parameters_repeat1", Rust::ClosureParametersRepeat1),
        ("lifetime", Rust::Lifetime),
        ("mod", Rust::Mod),
        (">=", Rust::GTEQ),
        ("||", Rust::PIPEPIPE),
        ("raw_string_literal", Rust::RawStringLiteral),
        ("reference_expression", Rust::ReferenceExpression),
        ("i64", Rust::I64),
        ("mutable_specifier", Rust::MutableSpecifier),
        ("pat", Rust::Pat),
        ("break", Rust::Break),
        ("else", Rust::Else),
        ("_", Rust::UNDERSCORE),
        ("type_item", Rust::TypeItem),
        ("tuple_type", Rust::TupleType),
        ("field_initializer_list", Rust::FieldInitializerList),
        ("block", Rust::Block),
        ("function_type", Rust::FunctionType),
        ("where_predicate", Rust::WherePredicate),
        ("optional_type_parameter", Rust::OptionalTypeParameter),
        ("&=", Rust::AMPEQ),
        ("while", Rust::While),
        ("higher_ranked_trait_bound", Rust::HigherRankedTraitBound),
        ("<<=", Rust::LTLTEQ),
        ("for_lifetimes", Rust::ForLifetimes),
        ("_string_content", Rust::StringContent),
        ("while_expression", Rust::WhileExpression),
        ("reference_pattern", Rust::ReferencePattern),
        ("extern_modifier", Rust::ExternModifier),
        ("where", Rust::Where),
        ("static_item", Rust::StaticItem),
        ("unary_expression", Rust::UnaryExpression),
        ("use_list_repeat1", Rust::UseListRepeat1),
        ("dynamic_type", Rust::DynamicType),
        ("_statement", Rust::Statement),
        ("_expression", Rust::Expression),
        ("char", Rust::Char),
        ("\'", Rust::SQUOTE),
        ("token_tree_pattern_repeat1", Rust::TokenTreePatternRepeat1),
        ("array_expression", Rust::ArrayExpression),
        ("scoped_type_identifier", Rust::ScopedTypeIdentifier),
        ("loop_label", Rust::LoopLabel),
        ("loop_expression", Rust::LoopExpression),
        ("use_list", Rust::UseList),
        ("escape_sequence", Rust::EscapeSequence),
        ("enum_variant_list_repeat2", Rust::EnumVariantListRepeat2),
        ("ref", Rust::Ref),
        ("path", Rust::Path),
        ("negative_literal", Rust::NegativeLiteral),
        ("u64", Rust::U64),
        ("]", Rust::RBRACK),
        ("constrained_type_parameter", Rust::ConstrainedTypeParameter),
        ("struct", Rust::Struct),
        ("unit_type", Rust::UnitType),
        ("?", Rust::QMARK),
        ("use_as_clause", Rust::UseAsClause),
        ("for", Rust::For),
        ("declaration_list", Rust::DeclarationList),
        ("assignment_expression", Rust::AssignmentExpression),
        ("base_field_initializer", Rust::BaseFieldInitializer),
        (
            "token_repetition_pattern_token1",
            Rust::TokenRepetitionPatternToken1,
        ),
        ("token_repetition", Rust::TokenRepetition),
        ("|=", Rust::PIPEEQ),
    ]),
};

impl From<&str> for Rust {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for Rust {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x) }
    }
}

// Rust == u16
impl PartialEq<u16> for Rust {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == Rust::from(*x)
    }
}

// u16 == Rust
impl PartialEq<Rust> for u16 {
    #[inline(always)]
    fn eq(&self, x: &Rust) -> bool {
        *x == *self
    }
}
