// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum Javascript {
    End = 0,
    Identifier = 1,
    HashBangLine = 2,
    Export = 3,
    STAR = 4,
    Default = 5,
    LBRACE = 6,
    COMMA = 7,
    RBRACE = 8,
    As = 9,
    Import = 10,
    From = 11,
    Var = 12,
    Let = 13,
    Const = 14,
    If = 15,
    Else = 16,
    Switch = 17,
    For = 18,
    LPAREN = 19,
    RPAREN = 20,
    Await = 21,
    In = 22,
    Of = 23,
    While = 24,
    Do = 25,
    Try = 26,
    With = 27,
    Break = 28,
    Continue = 29,
    Debugger = 30,
    Return = 31,
    Throw = 32,
    SEMI = 33,
    COLON = 34,
    Case = 35,
    Catch = 36,
    Finally = 37,
    Yield = 38,
    EQ = 39,
    LBRACK = 40,
    RBRACK = 41,
    LT = 42,
    GT = 43,
    SLASH = 44,
    JsxText = 45,
    Identifier2 = 46,
    DOT = 47,
    Class = 48,
    Extends = 49,
    Async = 50,
    Function = 51,
    EQGT = 52,
    New = 53,
    PLUSEQ = 54,
    DASHEQ = 55,
    STAREQ = 56,
    SLASHEQ = 57,
    PERCENTEQ = 58,
    CARETEQ = 59,
    AMPEQ = 60,
    PIPEEQ = 61,
    GTGTEQ = 62,
    GTGTGTEQ = 63,
    LTLTEQ = 64,
    STARSTAREQ = 65,
    DOTDOTDOT = 66,
    QMARK = 67,
    AMPAMP = 68,
    PIPEPIPE = 69,
    GTGT = 70,
    GTGTGT = 71,
    LTLT = 72,
    AMP = 73,
    CARET = 74,
    PIPE = 75,
    PLUS = 76,
    DASH = 77,
    PERCENT = 78,
    STARSTAR = 79,
    LTEQ = 80,
    EQEQ = 81,
    EQEQEQ = 82,
    BANGEQ = 83,
    BANGEQEQ = 84,
    GTEQ = 85,
    Instanceof = 86,
    BANG = 87,
    TILDE = 88,
    Typeof = 89,
    Void = 90,
    Delete = 91,
    PLUSPLUS = 92,
    DASHDASH = 93,
    DQUOTE = 94,
    StringToken1 = 95,
    SQUOTE = 96,
    StringToken2 = 97,
    EscapeSequence = 98,
    Comment = 99,
    BQUOTE = 100,
    DOLLARLBRACE = 101,
    SLASH2 = 102,
    RegexPattern = 103,
    RegexFlags = 104,
    Number = 105,
    Target = 106,
    This = 107,
    Super = 108,
    True = 109,
    False = 110,
    Null = 111,
    Undefined = 112,
    AT = 113,
    Static = 114,
    Get = 115,
    Set = 116,
    AutomaticSemicolon = 117,
    TemplateChars = 118,
    Program = 119,
    ExportStatement = 120,
    ExportClause = 121,
    ImportExportSpecifier = 122,
    Declaration = 123,
    Import2 = 124,
    ImportStatement = 125,
    ImportClause = 126,
    FromClause = 127,
    NamespaceImport = 128,
    NamedImports = 129,
    ExpressionStatement = 130,
    VariableDeclaration = 131,
    LexicalDeclaration = 132,
    VariableDeclarator = 133,
    StatementBlock = 134,
    IfStatement = 135,
    SwitchStatement = 136,
    ForStatement = 137,
    ForInStatement = 138,
    ForHeader = 139,
    WhileStatement = 140,
    DoStatement = 141,
    TryStatement = 142,
    WithStatement = 143,
    BreakStatement = 144,
    ContinueStatement = 145,
    DebuggerStatement = 146,
    ReturnStatement = 147,
    ThrowStatement = 148,
    EmptyStatement = 149,
    LabeledStatement = 150,
    SwitchBody = 151,
    SwitchCase = 152,
    SwitchDefault = 153,
    CatchClause = 154,
    FinallyClause = 155,
    ParenthesizedExpression = 156,
    Expression = 157,
    YieldExpression = 158,
    Object = 159,
    AssignmentPattern = 160,
    Array = 161,
    JsxElement = 162,
    JsxFragment = 163,
    JsxExpression = 164,
    JsxOpeningElement = 165,
    NestedIdentifier = 166,
    JsxNamespaceName = 167,
    JsxClosingElement = 168,
    JsxSelfClosingElement = 169,
    JsxAttribute = 170,
    Class2 = 171,
    ClassDeclaration = 172,
    ClassHeritage = 173,
    Function2 = 174,
    FunctionDeclaration = 175,
    GeneratorFunction = 176,
    GeneratorFunctionDeclaration = 177,
    ArrowFunction = 178,
    CallExpression = 179,
    NewExpression = 180,
    AwaitExpression = 181,
    MemberExpression = 182,
    SubscriptExpression = 183,
    AssignmentExpression = 184,
    AugmentedAssignmentExpression = 185,
    Initializer = 186,
    SpreadElement = 187,
    TernaryExpression = 188,
    BinaryExpression = 189,
    UnaryExpression = 190,
    UpdateExpression = 191,
    SequenceExpression = 192,
    String = 193,
    TemplateString = 194,
    TemplateSubstitution = 195,
    Regex = 196,
    MetaProperty = 197,
    Arguments = 198,
    Decorator = 199,
    MemberExpression2 = 200,
    CallExpression2 = 201,
    ClassBody = 202,
    PublicFieldDefinition = 203,
    FormalParameters = 204,
    RestParameter = 205,
    MethodDefinition = 206,
    Pair = 207,
    PropertyName = 208,
    ComputedPropertyName = 209,
    ProgramRepeat1 = 210,
    ExportStatementRepeat1 = 211,
    ExportClauseRepeat1 = 212,
    NamedImportsRepeat1 = 213,
    VariableDeclarationRepeat1 = 214,
    SwitchBodyRepeat1 = 215,
    ObjectRepeat1 = 216,
    ArrayRepeat1 = 217,
    JsxElementRepeat1 = 218,
    JsxOpeningElementRepeat1 = 219,
    StringRepeat1 = 220,
    StringRepeat2 = 221,
    TemplateStringRepeat1 = 222,
    ClassBodyRepeat1 = 223,
    FormalParametersRepeat1 = 224,
    ArrayPattern = 225,
    ExportSpecifier = 226,
    ImportSpecifier = 227,
    ObjectPattern = 228,
    PropertyIdentifier = 229,
    ShorthandPropertyIdentifier = 230,
    StatementIdentifier = 231,
    Error = 232,
}

impl Into<&'static str> for Javascript {
    fn into(self) -> &'static str {
        match self {
            Javascript::End => "end",
            Javascript::Identifier => "identifier",
            Javascript::HashBangLine => "hash_bang_line",
            Javascript::Export => "export",
            Javascript::STAR => "*",
            Javascript::Default => "default",
            Javascript::LBRACE => "{",
            Javascript::COMMA => ",",
            Javascript::RBRACE => "}",
            Javascript::As => "as",
            Javascript::Import => "import",
            Javascript::From => "from",
            Javascript::Var => "var",
            Javascript::Let => "let",
            Javascript::Const => "const",
            Javascript::If => "if",
            Javascript::Else => "else",
            Javascript::Switch => "switch",
            Javascript::For => "for",
            Javascript::LPAREN => "(",
            Javascript::RPAREN => ")",
            Javascript::Await => "await",
            Javascript::In => "in",
            Javascript::Of => "of",
            Javascript::While => "while",
            Javascript::Do => "do",
            Javascript::Try => "try",
            Javascript::With => "with",
            Javascript::Break => "break",
            Javascript::Continue => "continue",
            Javascript::Debugger => "debugger",
            Javascript::Return => "return",
            Javascript::Throw => "throw",
            Javascript::SEMI => ";",
            Javascript::COLON => ":",
            Javascript::Case => "case",
            Javascript::Catch => "catch",
            Javascript::Finally => "finally",
            Javascript::Yield => "yield",
            Javascript::EQ => "=",
            Javascript::LBRACK => "[",
            Javascript::RBRACK => "]",
            Javascript::LT => "<",
            Javascript::GT => ">",
            Javascript::SLASH => "/",
            Javascript::JsxText => "jsx_text",
            Javascript::Identifier2 => "identifier",
            Javascript::DOT => ".",
            Javascript::Class => "class",
            Javascript::Extends => "extends",
            Javascript::Async => "async",
            Javascript::Function => "function",
            Javascript::EQGT => "=>",
            Javascript::New => "new",
            Javascript::PLUSEQ => "+=",
            Javascript::DASHEQ => "-=",
            Javascript::STAREQ => "*=",
            Javascript::SLASHEQ => "/=",
            Javascript::PERCENTEQ => "%=",
            Javascript::CARETEQ => "^=",
            Javascript::AMPEQ => "&=",
            Javascript::PIPEEQ => "|=",
            Javascript::GTGTEQ => ">>=",
            Javascript::GTGTGTEQ => ">>>=",
            Javascript::LTLTEQ => "<<=",
            Javascript::STARSTAREQ => "**=",
            Javascript::DOTDOTDOT => "...",
            Javascript::QMARK => "?",
            Javascript::AMPAMP => "&&",
            Javascript::PIPEPIPE => "||",
            Javascript::GTGT => ">>",
            Javascript::GTGTGT => ">>>",
            Javascript::LTLT => "<<",
            Javascript::AMP => "&",
            Javascript::CARET => "^",
            Javascript::PIPE => "|",
            Javascript::PLUS => "+",
            Javascript::DASH => "-",
            Javascript::PERCENT => "%",
            Javascript::STARSTAR => "**",
            Javascript::LTEQ => "<=",
            Javascript::EQEQ => "==",
            Javascript::EQEQEQ => "===",
            Javascript::BANGEQ => "!=",
            Javascript::BANGEQEQ => "!==",
            Javascript::GTEQ => ">=",
            Javascript::Instanceof => "instanceof",
            Javascript::BANG => "!",
            Javascript::TILDE => "~",
            Javascript::Typeof => "typeof",
            Javascript::Void => "void",
            Javascript::Delete => "delete",
            Javascript::PLUSPLUS => "++",
            Javascript::DASHDASH => "--",
            Javascript::DQUOTE => "\"",
            Javascript::StringToken1 => "string_token1",
            Javascript::SQUOTE => "'",
            Javascript::StringToken2 => "string_token2",
            Javascript::EscapeSequence => "escape_sequence",
            Javascript::Comment => "comment",
            Javascript::BQUOTE => "`",
            Javascript::DOLLARLBRACE => "${",
            Javascript::SLASH2 => "/",
            Javascript::RegexPattern => "regex_pattern",
            Javascript::RegexFlags => "regex_flags",
            Javascript::Number => "number",
            Javascript::Target => "target",
            Javascript::This => "this",
            Javascript::Super => "super",
            Javascript::True => "true",
            Javascript::False => "false",
            Javascript::Null => "null",
            Javascript::Undefined => "undefined",
            Javascript::AT => "@",
            Javascript::Static => "static",
            Javascript::Get => "get",
            Javascript::Set => "set",
            Javascript::AutomaticSemicolon => "_automatic_semicolon",
            Javascript::TemplateChars => "_template_chars",
            Javascript::Program => "program",
            Javascript::ExportStatement => "export_statement",
            Javascript::ExportClause => "export_clause",
            Javascript::ImportExportSpecifier => "_import_export_specifier",
            Javascript::Declaration => "_declaration",
            Javascript::Import2 => "import",
            Javascript::ImportStatement => "import_statement",
            Javascript::ImportClause => "import_clause",
            Javascript::FromClause => "_from_clause",
            Javascript::NamespaceImport => "namespace_import",
            Javascript::NamedImports => "named_imports",
            Javascript::ExpressionStatement => "expression_statement",
            Javascript::VariableDeclaration => "variable_declaration",
            Javascript::LexicalDeclaration => "lexical_declaration",
            Javascript::VariableDeclarator => "variable_declarator",
            Javascript::StatementBlock => "statement_block",
            Javascript::IfStatement => "if_statement",
            Javascript::SwitchStatement => "switch_statement",
            Javascript::ForStatement => "for_statement",
            Javascript::ForInStatement => "for_in_statement",
            Javascript::ForHeader => "_for_header",
            Javascript::WhileStatement => "while_statement",
            Javascript::DoStatement => "do_statement",
            Javascript::TryStatement => "try_statement",
            Javascript::WithStatement => "with_statement",
            Javascript::BreakStatement => "break_statement",
            Javascript::ContinueStatement => "continue_statement",
            Javascript::DebuggerStatement => "debugger_statement",
            Javascript::ReturnStatement => "return_statement",
            Javascript::ThrowStatement => "throw_statement",
            Javascript::EmptyStatement => "empty_statement",
            Javascript::LabeledStatement => "labeled_statement",
            Javascript::SwitchBody => "switch_body",
            Javascript::SwitchCase => "switch_case",
            Javascript::SwitchDefault => "switch_default",
            Javascript::CatchClause => "catch_clause",
            Javascript::FinallyClause => "finally_clause",
            Javascript::ParenthesizedExpression => "parenthesized_expression",
            Javascript::Expression => "_expression",
            Javascript::YieldExpression => "yield_expression",
            Javascript::Object => "object",
            Javascript::AssignmentPattern => "assignment_pattern",
            Javascript::Array => "array",
            Javascript::JsxElement => "jsx_element",
            Javascript::JsxFragment => "jsx_fragment",
            Javascript::JsxExpression => "jsx_expression",
            Javascript::JsxOpeningElement => "jsx_opening_element",
            Javascript::NestedIdentifier => "nested_identifier",
            Javascript::JsxNamespaceName => "jsx_namespace_name",
            Javascript::JsxClosingElement => "jsx_closing_element",
            Javascript::JsxSelfClosingElement => "jsx_self_closing_element",
            Javascript::JsxAttribute => "jsx_attribute",
            Javascript::Class2 => "class",
            Javascript::ClassDeclaration => "class_declaration",
            Javascript::ClassHeritage => "class_heritage",
            Javascript::Function2 => "function",
            Javascript::FunctionDeclaration => "function_declaration",
            Javascript::GeneratorFunction => "generator_function",
            Javascript::GeneratorFunctionDeclaration => "generator_function_declaration",
            Javascript::ArrowFunction => "arrow_function",
            Javascript::CallExpression => "call_expression",
            Javascript::NewExpression => "new_expression",
            Javascript::AwaitExpression => "await_expression",
            Javascript::MemberExpression => "member_expression",
            Javascript::SubscriptExpression => "subscript_expression",
            Javascript::AssignmentExpression => "assignment_expression",
            Javascript::AugmentedAssignmentExpression => "augmented_assignment_expression",
            Javascript::Initializer => "_initializer",
            Javascript::SpreadElement => "spread_element",
            Javascript::TernaryExpression => "ternary_expression",
            Javascript::BinaryExpression => "binary_expression",
            Javascript::UnaryExpression => "unary_expression",
            Javascript::UpdateExpression => "update_expression",
            Javascript::SequenceExpression => "sequence_expression",
            Javascript::String => "string",
            Javascript::TemplateString => "template_string",
            Javascript::TemplateSubstitution => "template_substitution",
            Javascript::Regex => "regex",
            Javascript::MetaProperty => "meta_property",
            Javascript::Arguments => "arguments",
            Javascript::Decorator => "decorator",
            Javascript::MemberExpression2 => "member_expression",
            Javascript::CallExpression2 => "call_expression",
            Javascript::ClassBody => "class_body",
            Javascript::PublicFieldDefinition => "public_field_definition",
            Javascript::FormalParameters => "formal_parameters",
            Javascript::RestParameter => "rest_parameter",
            Javascript::MethodDefinition => "method_definition",
            Javascript::Pair => "pair",
            Javascript::PropertyName => "_property_name",
            Javascript::ComputedPropertyName => "computed_property_name",
            Javascript::ProgramRepeat1 => "program_repeat1",
            Javascript::ExportStatementRepeat1 => "export_statement_repeat1",
            Javascript::ExportClauseRepeat1 => "export_clause_repeat1",
            Javascript::NamedImportsRepeat1 => "named_imports_repeat1",
            Javascript::VariableDeclarationRepeat1 => "variable_declaration_repeat1",
            Javascript::SwitchBodyRepeat1 => "switch_body_repeat1",
            Javascript::ObjectRepeat1 => "object_repeat1",
            Javascript::ArrayRepeat1 => "array_repeat1",
            Javascript::JsxElementRepeat1 => "jsx_element_repeat1",
            Javascript::JsxOpeningElementRepeat1 => "jsx_opening_element_repeat1",
            Javascript::StringRepeat1 => "string_repeat1",
            Javascript::StringRepeat2 => "string_repeat2",
            Javascript::TemplateStringRepeat1 => "template_string_repeat1",
            Javascript::ClassBodyRepeat1 => "class_body_repeat1",
            Javascript::FormalParametersRepeat1 => "formal_parameters_repeat1",
            Javascript::ArrayPattern => "array_pattern",
            Javascript::ExportSpecifier => "export_specifier",
            Javascript::ImportSpecifier => "import_specifier",
            Javascript::ObjectPattern => "object_pattern",
            Javascript::PropertyIdentifier => "property_identifier",
            Javascript::ShorthandPropertyIdentifier => "shorthand_property_identifier",
            Javascript::StatementIdentifier => "statement_identifier",
            Javascript::Error => "ERROR",
        }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, Javascript> = ::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (1, 189),
        (0, 3),
        (0, 0),
        (0, 16),
        (0, 3),
        (2, 79),
        (0, 187),
        (1, 27),
        (0, 0),
        (2, 201),
        (0, 24),
        (1, 22),
        (0, 3),
        (0, 87),
        (0, 160),
        (0, 16),
        (5, 209),
        (1, 60),
        (0, 0),
        (0, 4),
        (4, 129),
        (1, 155),
        (0, 71),
        (0, 2),
        (6, 37),
        (0, 8),
        (0, 85),
        (0, 14),
        (0, 22),
        (0, 51),
        (2, 1),
        (0, 87),
        (0, 30),
        (2, 30),
        (8, 200),
        (0, 5),
        (0, 11),
        (0, 209),
        (1, 5),
        (0, 0),
        (0, 13),
        (2, 177),
        (0, 160),
        (1, 0),
        (6, 131),
        (0, 83),
    ]),
    entries: ::phf::Slice::Static(&[
        ("function_declaration", Javascript::FunctionDeclaration),
        ("async", Javascript::Async),
        ("string_repeat1", Javascript::StringRepeat1),
        ("+=", Javascript::PLUSEQ),
        ("object", Javascript::Object),
        ("return", Javascript::Return),
        ("jsx_namespace_name", Javascript::JsxNamespaceName),
        ("`", Javascript::BQUOTE),
        ("property_identifier", Javascript::PropertyIdentifier),
        (".", Javascript::DOT),
        ("arguments", Javascript::Arguments),
        ("class", Javascript::Class),
        ("do_statement", Javascript::DoStatement),
        ("typeof", Javascript::Typeof),
        ("get", Javascript::Get),
        ("import", Javascript::Import),
        ("+", Javascript::PLUS),
        ("==", Javascript::EQEQ),
        ("<<", Javascript::LTLT),
        ("ERROR", Javascript::Error),
        ("statement_identifier", Javascript::StatementIdentifier),
        (">>=", Javascript::GTGTEQ),
        ("^=", Javascript::CARETEQ),
        ("statement_block", Javascript::StatementBlock),
        ("identifier", Javascript::Identifier),
        ("if", Javascript::If),
        ("public_field_definition", Javascript::PublicFieldDefinition),
        ("finally_clause", Javascript::FinallyClause),
        ("===", Javascript::EQEQEQ),
        ("new_expression", Javascript::NewExpression),
        ("continue_statement", Javascript::ContinueStatement),
        ("await", Javascript::Await),
        ("if_statement", Javascript::IfStatement),
        ("regex_pattern", Javascript::RegexPattern),
        ("catch", Javascript::Catch),
        ("debugger", Javascript::Debugger),
        (
            "jsx_opening_element_repeat1",
            Javascript::JsxOpeningElementRepeat1,
        ),
        ("switch_default", Javascript::SwitchDefault),
        ("template_string", Javascript::TemplateString),
        ("regex", Javascript::Regex),
        ("import_specifier", Javascript::ImportSpecifier),
        ("import_clause", Javascript::ImportClause),
        ("while_statement", Javascript::WhileStatement),
        ("function", Javascript::Function),
        ("static", Javascript::Static),
        ("variable_declaration", Javascript::VariableDeclaration),
        ("${", Javascript::DOLLARLBRACE),
        ("set", Javascript::Set),
        ("true", Javascript::True),
        ("do", Javascript::Do),
        ("from", Javascript::From),
        ("export_statement", Javascript::ExportStatement),
        ("debugger_statement", Javascript::DebuggerStatement),
        ("yield", Javascript::Yield),
        ("catch_clause", Javascript::CatchClause),
        ("comment", Javascript::Comment),
        ("program_repeat1", Javascript::ProgramRepeat1),
        ("throw_statement", Javascript::ThrowStatement),
        ("while", Javascript::While),
        (":", Javascript::COLON),
        ("decorator", Javascript::Decorator),
        ("?", Javascript::QMARK),
        ("jsx_element_repeat1", Javascript::JsxElementRepeat1),
        (">=", Javascript::GTEQ),
        ("for_in_statement", Javascript::ForInStatement),
        ("switch", Javascript::Switch),
        (
            "shorthand_property_identifier",
            Javascript::ShorthandPropertyIdentifier,
        ),
        ("call_expression", Javascript::CallExpression),
        ("export_clause", Javascript::ExportClause),
        ("for", Javascript::For),
        ("return_statement", Javascript::ReturnStatement),
        ("instanceof", Javascript::Instanceof),
        ("with", Javascript::With),
        ("%", Javascript::PERCENT),
        (">>", Javascript::GTGT),
        ("|", Javascript::PIPE),
        (
            "augmented_assignment_expression",
            Javascript::AugmentedAssignmentExpression,
        ),
        ("unary_expression", Javascript::UnaryExpression),
        ("class_body_repeat1", Javascript::ClassBodyRepeat1),
        ("break", Javascript::Break),
        ("-=", Javascript::DASHEQ),
        ("array", Javascript::Array),
        ("const", Javascript::Const),
        ("_property_name", Javascript::PropertyName),
        ("null", Javascript::Null),
        (
            "parenthesized_expression",
            Javascript::ParenthesizedExpression,
        ),
        ("object_repeat1", Javascript::ObjectRepeat1),
        ("method_definition", Javascript::MethodDefinition),
        ("program", Javascript::Program),
        ("%=", Javascript::PERCENTEQ),
        ("&", Javascript::AMP),
        ("yield_expression", Javascript::YieldExpression),
        ("with_statement", Javascript::WithStatement),
        ("@", Javascript::AT),
        ("sequence_expression", Javascript::SequenceExpression),
        ("var", Javascript::Var),
        ("try_statement", Javascript::TryStatement),
        ("of", Javascript::Of),
        ("extends", Javascript::Extends),
        ("jsx_expression", Javascript::JsxExpression),
        ("jsx_text", Javascript::JsxText),
        ("string", Javascript::String),
        ("\'", Javascript::SQUOTE),
        (">>>=", Javascript::GTGTGTEQ),
        ("&=", Javascript::AMPEQ),
        ("assignment_pattern", Javascript::AssignmentPattern),
        ("namespace_import", Javascript::NamespaceImport),
        ("rest_parameter", Javascript::RestParameter),
        ("_declaration", Javascript::Declaration),
        ("jsx_element", Javascript::JsxElement),
        ("end", Javascript::End),
        ("await_expression", Javascript::AwaitExpression),
        ("class_body", Javascript::ClassBody),
        ("switch_statement", Javascript::SwitchStatement),
        ("_for_header", Javascript::ForHeader),
        ("new", Javascript::New),
        ("labeled_statement", Javascript::LabeledStatement),
        ("continue", Javascript::Continue),
        (
            "export_statement_repeat1",
            Javascript::ExportStatementRepeat1,
        ),
        ("class_declaration", Javascript::ClassDeclaration),
        ("|=", Javascript::PIPEEQ),
        ("else", Javascript::Else),
        ("expression_statement", Javascript::ExpressionStatement),
        ("throw", Javascript::Throw),
        ("*=", Javascript::STAREQ),
        ("string_repeat2", Javascript::StringRepeat2),
        ("arrow_function", Javascript::ArrowFunction),
        ("array_pattern", Javascript::ArrayPattern),
        ("<<=", Javascript::LTLTEQ),
        ("update_expression", Javascript::UpdateExpression),
        ("jsx_attribute", Javascript::JsxAttribute),
        ("...", Javascript::DOTDOTDOT),
        ("_expression", Javascript::Expression),
        ("regex_flags", Javascript::RegexFlags),
        (">>>", Javascript::GTGTGT),
        ("template_substitution", Javascript::TemplateSubstitution),
        ("<", Javascript::LT),
        ("array_repeat1", Javascript::ArrayRepeat1),
        ("generator_function", Javascript::GeneratorFunction),
        (
            "jsx_self_closing_element",
            Javascript::JsxSelfClosingElement,
        ),
        ("finally", Javascript::Finally),
        ("target", Javascript::Target),
        (">", Javascript::GT),
        (
            "generator_function_declaration",
            Javascript::GeneratorFunctionDeclaration,
        ),
        ("[", Javascript::LBRACK),
        ("^", Javascript::CARET),
        ("/", Javascript::SLASH),
        (
            "formal_parameters_repeat1",
            Javascript::FormalParametersRepeat1,
        ),
        ("nested_identifier", Javascript::NestedIdentifier),
        ("jsx_closing_element", Javascript::JsxClosingElement),
        ("}", Javascript::RBRACE),
        ("_automatic_semicolon", Javascript::AutomaticSemicolon),
        ("string_token2", Javascript::StringToken2),
        ("formal_parameters", Javascript::FormalParameters),
        ("-", Javascript::DASH),
        ("number", Javascript::Number),
        ("object_pattern", Javascript::ObjectPattern),
        ("*", Javascript::STAR),
        ("try", Javascript::Try),
        ("named_imports", Javascript::NamedImports),
        ("variable_declarator", Javascript::VariableDeclarator),
        ("binary_expression", Javascript::BinaryExpression),
        ("void", Javascript::Void),
        ("as", Javascript::As),
        ("_template_chars", Javascript::TemplateChars),
        ("this", Javascript::This),
        ("delete", Javascript::Delete),
        ("member_expression", Javascript::MemberExpression),
        (
            "variable_declaration_repeat1",
            Javascript::VariableDeclarationRepeat1,
        ),
        ("computed_property_name", Javascript::ComputedPropertyName),
        ("(", Javascript::LPAREN),
        ("~", Javascript::TILDE),
        ("export_clause_repeat1", Javascript::ExportClauseRepeat1),
        (";", Javascript::SEMI),
        ("subscript_expression", Javascript::SubscriptExpression),
        ("!=", Javascript::BANGEQ),
        ("named_imports_repeat1", Javascript::NamedImportsRepeat1),
        ("let", Javascript::Let),
        ("=>", Javascript::EQGT),
        (")", Javascript::RPAREN),
        ("undefined", Javascript::Undefined),
        ("spread_element", Javascript::SpreadElement),
        ("pair", Javascript::Pair),
        ("--", Javascript::DASHDASH),
        ("ternary_expression", Javascript::TernaryExpression),
        ("!==", Javascript::BANGEQEQ),
        ("switch_body_repeat1", Javascript::SwitchBodyRepeat1),
        ("escape_sequence", Javascript::EscapeSequence),
        ("_from_clause", Javascript::FromClause),
        ("false", Javascript::False),
        ("!", Javascript::BANG),
        ("lexical_declaration", Javascript::LexicalDeclaration),
        ("for_statement", Javascript::ForStatement),
        (",", Javascript::COMMA),
        ("jsx_fragment", Javascript::JsxFragment),
        ("**=", Javascript::STARSTAREQ),
        ("switch_case", Javascript::SwitchCase),
        ("]", Javascript::RBRACK),
        ("case", Javascript::Case),
        ("export", Javascript::Export),
        ("<=", Javascript::LTEQ),
        ("template_string_repeat1", Javascript::TemplateStringRepeat1),
        ("empty_statement", Javascript::EmptyStatement),
        ("export_specifier", Javascript::ExportSpecifier),
        ("string_token1", Javascript::StringToken1),
        ("++", Javascript::PLUSPLUS),
        ("{", Javascript::LBRACE),
        ("default", Javascript::Default),
        ("import_statement", Javascript::ImportStatement),
        ("||", Javascript::PIPEPIPE),
        ("hash_bang_line", Javascript::HashBangLine),
        ("=", Javascript::EQ),
        ("jsx_opening_element", Javascript::JsxOpeningElement),
        ("\\\"", Javascript::DQUOTE),
        ("assignment_expression", Javascript::AssignmentExpression),
        (
            "_import_export_specifier",
            Javascript::ImportExportSpecifier,
        ),
        ("class_heritage", Javascript::ClassHeritage),
        ("break_statement", Javascript::BreakStatement),
        ("**", Javascript::STARSTAR),
        ("in", Javascript::In),
        ("&&", Javascript::AMPAMP),
        ("switch_body", Javascript::SwitchBody),
        ("_initializer", Javascript::Initializer),
        ("/=", Javascript::SLASHEQ),
        ("super", Javascript::Super),
        ("meta_property", Javascript::MetaProperty),
    ]),
};

impl From<&str> for Javascript {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for Javascript {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x as u8) }
    }
}

// Javascript == u16
impl PartialEq<u16> for Javascript {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == Javascript::from(*x)
    }
}

// u16 == Javascript
impl PartialEq<Javascript> for u16 {
    #[inline(always)]
    fn eq(&self, x: &Javascript) -> bool {
        *x == *self
    }
}
