// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum Typescript {
    End = 0,
    Identifier = 1,
    HashBangLine = 2,
    Export = 3,
    STAR = 4,
    Default = 5,
    EQ = 6,
    As = 7,
    Namespace = 8,
    LBRACE = 9,
    COMMA = 10,
    RBRACE = 11,
    Type = 12,
    Typeof = 13,
    Import = 14,
    From = 15,
    Var = 16,
    Let = 17,
    Const = 18,
    If = 19,
    Else = 20,
    Switch = 21,
    For = 22,
    LPAREN = 23,
    RPAREN = 24,
    Await = 25,
    In = 26,
    Of = 27,
    While = 28,
    Do = 29,
    Try = 30,
    With = 31,
    Break = 32,
    Continue = 33,
    Debugger = 34,
    Return = 35,
    Throw = 36,
    SEMI = 37,
    COLON = 38,
    Case = 39,
    Catch = 40,
    Finally = 41,
    Yield = 42,
    LBRACK = 43,
    RBRACK = 44,
    LT = 45,
    GT = 46,
    SLASH = 47,
    DOT = 48,
    Class = 49,
    Async = 50,
    Function = 51,
    EQGT = 52,
    New = 53,
    PLUSEQ = 54,
    DASHEQ = 55,
    STAREQ = 56,
    SLASHEQ = 57,
    PERCENTEQ = 58,
    CARETEQ = 59,
    AMPEQ = 60,
    PIPEEQ = 61,
    GTGTEQ = 62,
    GTGTGTEQ = 63,
    LTLTEQ = 64,
    STARSTAREQ = 65,
    DOTDOTDOT = 66,
    QMARK = 67,
    AMPAMP = 68,
    PIPEPIPE = 69,
    GTGT = 70,
    GTGTGT = 71,
    LTLT = 72,
    AMP = 73,
    CARET = 74,
    PIPE = 75,
    PLUS = 76,
    DASH = 77,
    PERCENT = 78,
    STARSTAR = 79,
    LTEQ = 80,
    EQEQ = 81,
    EQEQEQ = 82,
    BANGEQ = 83,
    BANGEQEQ = 84,
    GTEQ = 85,
    Instanceof = 86,
    BANG = 87,
    TILDE = 88,
    Void = 89,
    Delete = 90,
    PLUSPLUS = 91,
    DASHDASH = 92,
    DQUOTE = 93,
    StringToken1 = 94,
    SQUOTE = 95,
    StringToken2 = 96,
    EscapeSequence = 97,
    Comment = 98,
    BQUOTE = 99,
    DOLLARLBRACE = 100,
    SLASH2 = 101,
    RegexPattern = 102,
    RegexFlags = 103,
    Number = 104,
    Target = 105,
    This = 106,
    Super = 107,
    True = 108,
    False = 109,
    Null = 110,
    Undefined = 111,
    AT = 112,
    Static = 113,
    Abstract = 114,
    Get = 115,
    Set = 116,
    Declare = 117,
    Public = 118,
    Private = 119,
    Protected = 120,
    Module = 121,
    Any = 122,
    Number2 = 123,
    Boolean = 124,
    String = 125,
    Symbol = 126,
    Require = 127,
    Implements = 128,
    Global = 129,
    Interface = 130,
    Extends = 131,
    Enum = 132,
    Readonly = 133,
    Is = 134,
    Keyof = 135,
    LBRACEPIPE = 136,
    PIPERBRACE = 137,
    AutomaticSemicolon = 138,
    TemplateChars = 139,
    Program = 140,
    ExportStatement = 141,
    ExportClause = 142,
    ImportExportSpecifier = 143,
    Declaration = 144,
    Import2 = 145,
    ImportStatement = 146,
    ImportClause = 147,
    FromClause = 148,
    NamespaceImport = 149,
    NamedImports = 150,
    ExpressionStatement = 151,
    VariableDeclaration = 152,
    LexicalDeclaration = 153,
    VariableDeclarator = 154,
    StatementBlock = 155,
    IfStatement = 156,
    SwitchStatement = 157,
    ForStatement = 158,
    ForInStatement = 159,
    ForHeader = 160,
    WhileStatement = 161,
    DoStatement = 162,
    TryStatement = 163,
    WithStatement = 164,
    BreakStatement = 165,
    ContinueStatement = 166,
    DebuggerStatement = 167,
    ReturnStatement = 168,
    ThrowStatement = 169,
    EmptyStatement = 170,
    LabeledStatement = 171,
    SwitchBody = 172,
    SwitchCase = 173,
    SwitchDefault = 174,
    CatchClause = 175,
    FinallyClause = 176,
    ParenthesizedExpression = 177,
    Expression = 178,
    YieldExpression = 179,
    Object = 180,
    AssignmentPattern = 181,
    Array = 182,
    NestedIdentifier = 183,
    Class2 = 184,
    ClassDeclaration = 185,
    ClassHeritage = 186,
    Function2 = 187,
    FunctionDeclaration = 188,
    GeneratorFunction = 189,
    GeneratorFunctionDeclaration = 190,
    ArrowFunction = 191,
    CallSignature = 192,
    CallExpression = 193,
    NewExpression = 194,
    AwaitExpression = 195,
    MemberExpression = 196,
    SubscriptExpression = 197,
    AssignmentExpression = 198,
    AugmentedAssignmentExpression = 199,
    Initializer = 200,
    SpreadElement = 201,
    TernaryExpression = 202,
    BinaryExpression = 203,
    UnaryExpression = 204,
    UpdateExpression = 205,
    SequenceExpression = 206,
    String2 = 207,
    TemplateString = 208,
    TemplateSubstitution = 209,
    Regex = 210,
    MetaProperty = 211,
    Arguments = 212,
    Decorator = 213,
    MemberExpression2 = 214,
    CallExpression2 = 215,
    ClassBody = 216,
    PublicFieldDefinition = 217,
    FormalParameters = 218,
    RestParameter = 219,
    MethodDefinition = 220,
    Pair = 221,
    PropertyName = 222,
    ComputedPropertyName = 223,
    NonNullExpression = 224,
    MethodSignature = 225,
    AbstractMethodSignature = 226,
    FunctionSignature = 227,
    TypeAssertion = 228,
    AsExpression = 229,
    ImportRequireClause = 230,
    ImplementsClause = 231,
    AmbientDeclaration = 232,
    AbstractClassDeclaration = 233,
    Module2 = 234,
    InternalModule = 235,
    Module3 = 236,
    ImportAlias = 237,
    NestedTypeIdentifier = 238,
    InterfaceDeclaration = 239,
    ExtendsClause = 240,
    EnumDeclaration = 241,
    EnumBody = 242,
    EnumAssignment = 243,
    TypeAliasDeclaration = 244,
    AccessibilityModifier = 245,
    RequiredParameter = 246,
    OptionalParameter = 247,
    ParameterName = 248,
    TypeAnnotation = 249,
    Type2 = 250,
    ConstructorType = 251,
    PrimaryType = 252,
    GenericType = 253,
    TypePredicate = 254,
    TypeQuery = 255,
    IndexTypeQuery = 256,
    LookupType = 257,
    MappedTypeClause = 258,
    LiteralType = 259,
    UnaryExpression2 = 260,
    ExistentialType = 261,
    FlowMaybeType = 262,
    ParenthesizedType = 263,
    PredefinedType = 264,
    TypeArguments = 265,
    ObjectType = 266,
    CallSignature2 = 267,
    PropertySignature = 268,
    TypeParameters = 269,
    TypeParameter = 270,
    DefaultType = 271,
    Constraint = 272,
    ConstructSignature = 273,
    IndexSignature = 274,
    ArrayType = 275,
    TupleType = 276,
    UnionType = 277,
    IntersectionType = 278,
    FunctionType = 279,
    ProgramRepeat1 = 280,
    ExportStatementRepeat1 = 281,
    ExportClauseRepeat1 = 282,
    NamedImportsRepeat1 = 283,
    VariableDeclarationRepeat1 = 284,
    SwitchBodyRepeat1 = 285,
    ObjectRepeat1 = 286,
    ArrayRepeat1 = 287,
    StringRepeat1 = 288,
    StringRepeat2 = 289,
    TemplateStringRepeat1 = 290,
    ClassBodyRepeat1 = 291,
    FormalParametersRepeat1 = 292,
    ImplementsClauseRepeat1 = 293,
    ExtendsClauseRepeat1 = 294,
    EnumBodyRepeat1 = 295,
    ObjectTypeRepeat1 = 296,
    TypeParametersRepeat1 = 297,
    ArrayPattern = 298,
    ExportSpecifier = 299,
    ImportSpecifier = 300,
    ObjectPattern = 301,
    PropertyIdentifier = 302,
    ShorthandPropertyIdentifier = 303,
    StatementIdentifier = 304,
    TypeIdentifier = 305,
    Error = 306,
}

impl Into<&'static str> for Typescript {
    fn into(self) -> &'static str {
        match self {
            Typescript::End => "end",
            Typescript::Identifier => "identifier",
            Typescript::HashBangLine => "hash_bang_line",
            Typescript::Export => "export",
            Typescript::STAR => "*",
            Typescript::Default => "default",
            Typescript::EQ => "=",
            Typescript::As => "as",
            Typescript::Namespace => "namespace",
            Typescript::LBRACE => "{",
            Typescript::COMMA => ",",
            Typescript::RBRACE => "}",
            Typescript::Type => "type",
            Typescript::Typeof => "typeof",
            Typescript::Import => "import",
            Typescript::From => "from",
            Typescript::Var => "var",
            Typescript::Let => "let",
            Typescript::Const => "const",
            Typescript::If => "if",
            Typescript::Else => "else",
            Typescript::Switch => "switch",
            Typescript::For => "for",
            Typescript::LPAREN => "(",
            Typescript::RPAREN => ")",
            Typescript::Await => "await",
            Typescript::In => "in",
            Typescript::Of => "of",
            Typescript::While => "while",
            Typescript::Do => "do",
            Typescript::Try => "try",
            Typescript::With => "with",
            Typescript::Break => "break",
            Typescript::Continue => "continue",
            Typescript::Debugger => "debugger",
            Typescript::Return => "return",
            Typescript::Throw => "throw",
            Typescript::SEMI => ";",
            Typescript::COLON => ":",
            Typescript::Case => "case",
            Typescript::Catch => "catch",
            Typescript::Finally => "finally",
            Typescript::Yield => "yield",
            Typescript::LBRACK => "[",
            Typescript::RBRACK => "]",
            Typescript::LT => "<",
            Typescript::GT => ">",
            Typescript::SLASH => "/",
            Typescript::DOT => ".",
            Typescript::Class => "class",
            Typescript::Async => "async",
            Typescript::Function => "function",
            Typescript::EQGT => "=>",
            Typescript::New => "new",
            Typescript::PLUSEQ => "+=",
            Typescript::DASHEQ => "-=",
            Typescript::STAREQ => "*=",
            Typescript::SLASHEQ => "/=",
            Typescript::PERCENTEQ => "%=",
            Typescript::CARETEQ => "^=",
            Typescript::AMPEQ => "&=",
            Typescript::PIPEEQ => "|=",
            Typescript::GTGTEQ => ">>=",
            Typescript::GTGTGTEQ => ">>>=",
            Typescript::LTLTEQ => "<<=",
            Typescript::STARSTAREQ => "**=",
            Typescript::DOTDOTDOT => "...",
            Typescript::QMARK => "?",
            Typescript::AMPAMP => "&&",
            Typescript::PIPEPIPE => "||",
            Typescript::GTGT => ">>",
            Typescript::GTGTGT => ">>>",
            Typescript::LTLT => "<<",
            Typescript::AMP => "&",
            Typescript::CARET => "^",
            Typescript::PIPE => "|",
            Typescript::PLUS => "+",
            Typescript::DASH => "-",
            Typescript::PERCENT => "%",
            Typescript::STARSTAR => "**",
            Typescript::LTEQ => "<=",
            Typescript::EQEQ => "==",
            Typescript::EQEQEQ => "===",
            Typescript::BANGEQ => "!=",
            Typescript::BANGEQEQ => "!==",
            Typescript::GTEQ => ">=",
            Typescript::Instanceof => "instanceof",
            Typescript::BANG => "!",
            Typescript::TILDE => "~",
            Typescript::Void => "void",
            Typescript::Delete => "delete",
            Typescript::PLUSPLUS => "++",
            Typescript::DASHDASH => "--",
            Typescript::DQUOTE => "\"",
            Typescript::StringToken1 => "string_token1",
            Typescript::SQUOTE => "'",
            Typescript::StringToken2 => "string_token2",
            Typescript::EscapeSequence => "escape_sequence",
            Typescript::Comment => "comment",
            Typescript::BQUOTE => "`",
            Typescript::DOLLARLBRACE => "${",
            Typescript::SLASH2 => "/",
            Typescript::RegexPattern => "regex_pattern",
            Typescript::RegexFlags => "regex_flags",
            Typescript::Number => "number",
            Typescript::Target => "target",
            Typescript::This => "this",
            Typescript::Super => "super",
            Typescript::True => "true",
            Typescript::False => "false",
            Typescript::Null => "null",
            Typescript::Undefined => "undefined",
            Typescript::AT => "@",
            Typescript::Static => "static",
            Typescript::Abstract => "abstract",
            Typescript::Get => "get",
            Typescript::Set => "set",
            Typescript::Declare => "declare",
            Typescript::Public => "public",
            Typescript::Private => "private",
            Typescript::Protected => "protected",
            Typescript::Module => "module",
            Typescript::Any => "any",
            Typescript::Number2 => "number",
            Typescript::Boolean => "boolean",
            Typescript::String => "string",
            Typescript::Symbol => "symbol",
            Typescript::Require => "require",
            Typescript::Implements => "implements",
            Typescript::Global => "global",
            Typescript::Interface => "interface",
            Typescript::Extends => "extends",
            Typescript::Enum => "enum",
            Typescript::Readonly => "readonly",
            Typescript::Is => "is",
            Typescript::Keyof => "keyof",
            Typescript::LBRACEPIPE => "{|",
            Typescript::PIPERBRACE => "|}",
            Typescript::AutomaticSemicolon => "_automatic_semicolon",
            Typescript::TemplateChars => "_template_chars",
            Typescript::Program => "program",
            Typescript::ExportStatement => "export_statement",
            Typescript::ExportClause => "export_clause",
            Typescript::ImportExportSpecifier => "_import_export_specifier",
            Typescript::Declaration => "_declaration",
            Typescript::Import2 => "import",
            Typescript::ImportStatement => "import_statement",
            Typescript::ImportClause => "import_clause",
            Typescript::FromClause => "_from_clause",
            Typescript::NamespaceImport => "namespace_import",
            Typescript::NamedImports => "named_imports",
            Typescript::ExpressionStatement => "expression_statement",
            Typescript::VariableDeclaration => "variable_declaration",
            Typescript::LexicalDeclaration => "lexical_declaration",
            Typescript::VariableDeclarator => "variable_declarator",
            Typescript::StatementBlock => "statement_block",
            Typescript::IfStatement => "if_statement",
            Typescript::SwitchStatement => "switch_statement",
            Typescript::ForStatement => "for_statement",
            Typescript::ForInStatement => "for_in_statement",
            Typescript::ForHeader => "_for_header",
            Typescript::WhileStatement => "while_statement",
            Typescript::DoStatement => "do_statement",
            Typescript::TryStatement => "try_statement",
            Typescript::WithStatement => "with_statement",
            Typescript::BreakStatement => "break_statement",
            Typescript::ContinueStatement => "continue_statement",
            Typescript::DebuggerStatement => "debugger_statement",
            Typescript::ReturnStatement => "return_statement",
            Typescript::ThrowStatement => "throw_statement",
            Typescript::EmptyStatement => "empty_statement",
            Typescript::LabeledStatement => "labeled_statement",
            Typescript::SwitchBody => "switch_body",
            Typescript::SwitchCase => "switch_case",
            Typescript::SwitchDefault => "switch_default",
            Typescript::CatchClause => "catch_clause",
            Typescript::FinallyClause => "finally_clause",
            Typescript::ParenthesizedExpression => "parenthesized_expression",
            Typescript::Expression => "_expression",
            Typescript::YieldExpression => "yield_expression",
            Typescript::Object => "object",
            Typescript::AssignmentPattern => "assignment_pattern",
            Typescript::Array => "array",
            Typescript::NestedIdentifier => "nested_identifier",
            Typescript::Class2 => "class",
            Typescript::ClassDeclaration => "class_declaration",
            Typescript::ClassHeritage => "class_heritage",
            Typescript::Function2 => "function",
            Typescript::FunctionDeclaration => "function_declaration",
            Typescript::GeneratorFunction => "generator_function",
            Typescript::GeneratorFunctionDeclaration => "generator_function_declaration",
            Typescript::ArrowFunction => "arrow_function",
            Typescript::CallSignature => "_call_signature",
            Typescript::CallExpression => "call_expression",
            Typescript::NewExpression => "new_expression",
            Typescript::AwaitExpression => "await_expression",
            Typescript::MemberExpression => "member_expression",
            Typescript::SubscriptExpression => "subscript_expression",
            Typescript::AssignmentExpression => "assignment_expression",
            Typescript::AugmentedAssignmentExpression => "augmented_assignment_expression",
            Typescript::Initializer => "_initializer",
            Typescript::SpreadElement => "spread_element",
            Typescript::TernaryExpression => "ternary_expression",
            Typescript::BinaryExpression => "binary_expression",
            Typescript::UnaryExpression => "unary_expression",
            Typescript::UpdateExpression => "update_expression",
            Typescript::SequenceExpression => "sequence_expression",
            Typescript::String2 => "string",
            Typescript::TemplateString => "template_string",
            Typescript::TemplateSubstitution => "template_substitution",
            Typescript::Regex => "regex",
            Typescript::MetaProperty => "meta_property",
            Typescript::Arguments => "arguments",
            Typescript::Decorator => "decorator",
            Typescript::MemberExpression2 => "member_expression",
            Typescript::CallExpression2 => "call_expression",
            Typescript::ClassBody => "class_body",
            Typescript::PublicFieldDefinition => "public_field_definition",
            Typescript::FormalParameters => "formal_parameters",
            Typescript::RestParameter => "rest_parameter",
            Typescript::MethodDefinition => "method_definition",
            Typescript::Pair => "pair",
            Typescript::PropertyName => "_property_name",
            Typescript::ComputedPropertyName => "computed_property_name",
            Typescript::NonNullExpression => "non_null_expression",
            Typescript::MethodSignature => "method_signature",
            Typescript::AbstractMethodSignature => "abstract_method_signature",
            Typescript::FunctionSignature => "function_signature",
            Typescript::TypeAssertion => "type_assertion",
            Typescript::AsExpression => "as_expression",
            Typescript::ImportRequireClause => "import_require_clause",
            Typescript::ImplementsClause => "implements_clause",
            Typescript::AmbientDeclaration => "ambient_declaration",
            Typescript::AbstractClassDeclaration => "abstract_class_declaration",
            Typescript::Module2 => "module",
            Typescript::InternalModule => "internal_module",
            Typescript::Module3 => "_module",
            Typescript::ImportAlias => "import_alias",
            Typescript::NestedTypeIdentifier => "nested_type_identifier",
            Typescript::InterfaceDeclaration => "interface_declaration",
            Typescript::ExtendsClause => "extends_clause",
            Typescript::EnumDeclaration => "enum_declaration",
            Typescript::EnumBody => "enum_body",
            Typescript::EnumAssignment => "enum_assignment",
            Typescript::TypeAliasDeclaration => "type_alias_declaration",
            Typescript::AccessibilityModifier => "accessibility_modifier",
            Typescript::RequiredParameter => "required_parameter",
            Typescript::OptionalParameter => "optional_parameter",
            Typescript::ParameterName => "_parameter_name",
            Typescript::TypeAnnotation => "type_annotation",
            Typescript::Type2 => "_type",
            Typescript::ConstructorType => "constructor_type",
            Typescript::PrimaryType => "_primary_type",
            Typescript::GenericType => "generic_type",
            Typescript::TypePredicate => "type_predicate",
            Typescript::TypeQuery => "type_query",
            Typescript::IndexTypeQuery => "index_type_query",
            Typescript::LookupType => "lookup_type",
            Typescript::MappedTypeClause => "mapped_type_clause",
            Typescript::LiteralType => "literal_type",
            Typescript::UnaryExpression2 => "unary_expression",
            Typescript::ExistentialType => "existential_type",
            Typescript::FlowMaybeType => "flow_maybe_type",
            Typescript::ParenthesizedType => "parenthesized_type",
            Typescript::PredefinedType => "predefined_type",
            Typescript::TypeArguments => "type_arguments",
            Typescript::ObjectType => "object_type",
            Typescript::CallSignature2 => "call_signature",
            Typescript::PropertySignature => "property_signature",
            Typescript::TypeParameters => "type_parameters",
            Typescript::TypeParameter => "type_parameter",
            Typescript::DefaultType => "default_type",
            Typescript::Constraint => "constraint",
            Typescript::ConstructSignature => "construct_signature",
            Typescript::IndexSignature => "index_signature",
            Typescript::ArrayType => "array_type",
            Typescript::TupleType => "tuple_type",
            Typescript::UnionType => "union_type",
            Typescript::IntersectionType => "intersection_type",
            Typescript::FunctionType => "function_type",
            Typescript::ProgramRepeat1 => "program_repeat1",
            Typescript::ExportStatementRepeat1 => "export_statement_repeat1",
            Typescript::ExportClauseRepeat1 => "export_clause_repeat1",
            Typescript::NamedImportsRepeat1 => "named_imports_repeat1",
            Typescript::VariableDeclarationRepeat1 => "variable_declaration_repeat1",
            Typescript::SwitchBodyRepeat1 => "switch_body_repeat1",
            Typescript::ObjectRepeat1 => "object_repeat1",
            Typescript::ArrayRepeat1 => "array_repeat1",
            Typescript::StringRepeat1 => "string_repeat1",
            Typescript::StringRepeat2 => "string_repeat2",
            Typescript::TemplateStringRepeat1 => "template_string_repeat1",
            Typescript::ClassBodyRepeat1 => "class_body_repeat1",
            Typescript::FormalParametersRepeat1 => "formal_parameters_repeat1",
            Typescript::ImplementsClauseRepeat1 => "implements_clause_repeat1",
            Typescript::ExtendsClauseRepeat1 => "extends_clause_repeat1",
            Typescript::EnumBodyRepeat1 => "enum_body_repeat1",
            Typescript::ObjectTypeRepeat1 => "object_type_repeat1",
            Typescript::TypeParametersRepeat1 => "type_parameters_repeat1",
            Typescript::ArrayPattern => "array_pattern",
            Typescript::ExportSpecifier => "export_specifier",
            Typescript::ImportSpecifier => "import_specifier",
            Typescript::ObjectPattern => "object_pattern",
            Typescript::PropertyIdentifier => "property_identifier",
            Typescript::ShorthandPropertyIdentifier => "shorthand_property_identifier",
            Typescript::StatementIdentifier => "statement_identifier",
            Typescript::TypeIdentifier => "type_identifier",
            Typescript::Error => "ERROR",
        }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, Typescript> = ::phf::Map {
    key: 3213172566270843353,
    disps: ::phf::Slice::Static(&[
        (2, 48),
        (0, 40),
        (0, 285),
        (0, 0),
        (0, 215),
        (0, 8),
        (0, 6),
        (1, 47),
        (1, 62),
        (0, 114),
        (0, 8),
        (0, 16),
        (0, 84),
        (0, 19),
        (0, 126),
        (11, 194),
        (0, 13),
        (1, 13),
        (2, 53),
        (5, 101),
        (0, 0),
        (6, 92),
        (0, 0),
        (0, 0),
        (0, 16),
        (1, 289),
        (0, 122),
        (1, 0),
        (4, 115),
        (0, 13),
        (0, 20),
        (0, 0),
        (0, 0),
        (44, 156),
        (0, 72),
        (7, 198),
        (0, 43),
        (0, 2),
        (0, 20),
        (0, 60),
        (1, 53),
        (58, 12),
        (0, 221),
        (0, 53),
        (0, 214),
        (0, 129),
        (1, 103),
        (1, 12),
        (0, 115),
        (13, 190),
        (1, 1),
        (3, 184),
        (0, 183),
        (0, 165),
        (0, 4),
        (0, 16),
        (1, 0),
        (1, 18),
        (0, 152),
    ]),
    entries: ::phf::Slice::Static(&[
        ("[", Typescript::LBRACK),
        ("array_pattern", Typescript::ArrayPattern),
        ("export_clause", Typescript::ExportClause),
        ("property_signature", Typescript::PropertySignature),
        ("arrow_function", Typescript::ArrowFunction),
        ("throw_statement", Typescript::ThrowStatement),
        ("<<", Typescript::LTLT),
        ("implements", Typescript::Implements),
        ("interface_declaration", Typescript::InterfaceDeclaration),
        ("import_specifier", Typescript::ImportSpecifier),
        ("extends_clause", Typescript::ExtendsClause),
        ("_automatic_semicolon", Typescript::AutomaticSemicolon),
        ("formal_parameters", Typescript::FormalParameters),
        ("array_repeat1", Typescript::ArrayRepeat1),
        ("empty_statement", Typescript::EmptyStatement),
        ("flow_maybe_type", Typescript::FlowMaybeType),
        ("^=", Typescript::CARETEQ),
        ("|}", Typescript::PIPERBRACE),
        ("function_type", Typescript::FunctionType),
        ("import_require_clause", Typescript::ImportRequireClause),
        ("function_signature", Typescript::FunctionSignature),
        ("case", Typescript::Case),
        ("string", Typescript::String),
        ("meta_property", Typescript::MetaProperty),
        ("}", Typescript::RBRACE),
        ("**=", Typescript::STARSTAREQ),
        ("\'", Typescript::SQUOTE),
        ("+", Typescript::PLUS),
        ("export_clause_repeat1", Typescript::ExportClauseRepeat1),
        ("import_alias", Typescript::ImportAlias),
        (":", Typescript::COLON),
        ("object_type", Typescript::ObjectType),
        ("?", Typescript::QMARK),
        ("_parameter_name", Typescript::ParameterName),
        ("statement_block", Typescript::StatementBlock),
        ("while", Typescript::While),
        ("_primary_type", Typescript::PrimaryType),
        ("template_string", Typescript::TemplateString),
        ("+=", Typescript::PLUSEQ),
        (
            "variable_declaration_repeat1",
            Typescript::VariableDeclarationRepeat1,
        ),
        ("extends", Typescript::Extends),
        ("call_expression", Typescript::CallExpression),
        ("*", Typescript::STAR),
        ("variable_declarator", Typescript::VariableDeclarator),
        ("type_parameters_repeat1", Typescript::TypeParametersRepeat1),
        ("%=", Typescript::PERCENTEQ),
        ("interface", Typescript::Interface),
        ("type_assertion", Typescript::TypeAssertion),
        ("program", Typescript::Program),
        ("boolean", Typescript::Boolean),
        ("for_in_statement", Typescript::ForInStatement),
        ("=", Typescript::EQ),
        ("identifier", Typescript::Identifier),
        ("labeled_statement", Typescript::LabeledStatement),
        ("string_token2", Typescript::StringToken2),
        ("construct_signature", Typescript::ConstructSignature),
        (
            "parenthesized_expression",
            Typescript::ParenthesizedExpression,
        ),
        ("/=", Typescript::SLASHEQ),
        ("rest_parameter", Typescript::RestParameter),
        (">=", Typescript::GTEQ),
        ("template_substitution", Typescript::TemplateSubstitution),
        ("import_statement", Typescript::ImportStatement),
        ("try_statement", Typescript::TryStatement),
        ("ERROR", Typescript::Error),
        ("!=", Typescript::BANGEQ),
        ("constructor_type", Typescript::ConstructorType),
        ("mapped_type_clause", Typescript::MappedTypeClause),
        ("(", Typescript::LPAREN),
        ("_from_clause", Typescript::FromClause),
        ("&", Typescript::AMP),
        ("\\\"", Typescript::DQUOTE),
        ("string_repeat1", Typescript::StringRepeat1),
        ("const", Typescript::Const),
        ("property_identifier", Typescript::PropertyIdentifier),
        ("do", Typescript::Do),
        ("class_declaration", Typescript::ClassDeclaration),
        ("declare", Typescript::Declare),
        ("^", Typescript::CARET),
        ("decorator", Typescript::Decorator),
        ("enum_body_repeat1", Typescript::EnumBodyRepeat1),
        ("regex_pattern", Typescript::RegexPattern),
        ("with_statement", Typescript::WithStatement),
        ("if", Typescript::If),
        ("arguments", Typescript::Arguments),
        ("try", Typescript::Try),
        ("is", Typescript::Is),
        ("===", Typescript::EQEQEQ),
        ("parenthesized_type", Typescript::ParenthesizedType),
        ("new", Typescript::New),
        ("enum_declaration", Typescript::EnumDeclaration),
        ("&=", Typescript::AMPEQ),
        ("<=", Typescript::LTEQ),
        ("any", Typescript::Any),
        ("readonly", Typescript::Readonly),
        ("from", Typescript::From),
        ("object_repeat1", Typescript::ObjectRepeat1),
        ("namespace", Typescript::Namespace),
        ("finally_clause", Typescript::FinallyClause),
        (">", Typescript::GT),
        ("false", Typescript::False),
        ("_for_header", Typescript::ForHeader),
        ("/", Typescript::SLASH),
        ("private", Typescript::Private),
        ("type_annotation", Typescript::TypeAnnotation),
        ("break_statement", Typescript::BreakStatement),
        ("import", Typescript::Import),
        ("public_field_definition", Typescript::PublicFieldDefinition),
        (".", Typescript::DOT),
        (
            "abstract_class_declaration",
            Typescript::AbstractClassDeclaration,
        ),
        ("class_body_repeat1", Typescript::ClassBodyRepeat1),
        ("internal_module", Typescript::InternalModule),
        (
            "_import_export_specifier",
            Typescript::ImportExportSpecifier,
        ),
        ("string_repeat2", Typescript::StringRepeat2),
        ("!==", Typescript::BANGEQEQ),
        (">>", Typescript::GTGT),
        (">>=", Typescript::GTGTEQ),
        ("async", Typescript::Async),
        ("finally", Typescript::Finally),
        ("required_parameter", Typescript::RequiredParameter),
        ("switch_body_repeat1", Typescript::SwitchBodyRepeat1),
        ("|", Typescript::PIPE),
        ("literal_type", Typescript::LiteralType),
        ("regex", Typescript::Regex),
        ("class_body", Typescript::ClassBody),
        ("import_clause", Typescript::ImportClause),
        ("break", Typescript::Break),
        ("index_signature", Typescript::IndexSignature),
        ("*=", Typescript::STAREQ),
        ("catch", Typescript::Catch),
        ("method_signature", Typescript::MethodSignature),
        ("switch_statement", Typescript::SwitchStatement),
        ("**", Typescript::STARSTAR),
        ("delete", Typescript::Delete),
        ("object_type_repeat1", Typescript::ObjectTypeRepeat1),
        ("yield", Typescript::Yield),
        ("accessibility_modifier", Typescript::AccessibilityModifier),
        ("await_expression", Typescript::AwaitExpression),
        ("enum_assignment", Typescript::EnumAssignment),
        ("variable_declaration", Typescript::VariableDeclaration),
        ("global", Typescript::Global),
        (",", Typescript::COMMA),
        ("...", Typescript::DOTDOTDOT),
        ("type_predicate", Typescript::TypePredicate),
        (
            "shorthand_property_identifier",
            Typescript::ShorthandPropertyIdentifier,
        ),
        ("predefined_type", Typescript::PredefinedType),
        ("computed_property_name", Typescript::ComputedPropertyName),
        ("ternary_expression", Typescript::TernaryExpression),
        ("keyof", Typescript::Keyof),
        ("target", Typescript::Target),
        ("!", Typescript::BANG),
        ("subscript_expression", Typescript::SubscriptExpression),
        ("type_query", Typescript::TypeQuery),
        ("continue_statement", Typescript::ContinueStatement),
        (";", Typescript::SEMI),
        ("assignment_pattern", Typescript::AssignmentPattern),
        ("type_identifier", Typescript::TypeIdentifier),
        ("switch_body", Typescript::SwitchBody),
        ("require", Typescript::Require),
        ("array", Typescript::Array),
        ("object", Typescript::Object),
        ("export_specifier", Typescript::ExportSpecifier),
        ("intersection_type", Typescript::IntersectionType),
        ("function", Typescript::Function),
        ("default", Typescript::Default),
        ("_call_signature", Typescript::CallSignature),
        ("export_statement", Typescript::ExportStatement),
        ("existential_type", Typescript::ExistentialType),
        ("nested_type_identifier", Typescript::NestedTypeIdentifier),
        ("type_parameters", Typescript::TypeParameters),
        ("while_statement", Typescript::WhileStatement),
        ("continue", Typescript::Continue),
        ("hash_bang_line", Typescript::HashBangLine),
        (">>>", Typescript::GTGTGT),
        ("do_statement", Typescript::DoStatement),
        (
            "formal_parameters_repeat1",
            Typescript::FormalParametersRepeat1,
        ),
        ("null", Typescript::Null),
        ("static", Typescript::Static),
        ("lexical_declaration", Typescript::LexicalDeclaration),
        ("throw", Typescript::Throw),
        ("_template_chars", Typescript::TemplateChars),
        ("switch", Typescript::Switch),
        ("enum", Typescript::Enum),
        ("<<=", Typescript::LTLTEQ),
        ("set", Typescript::Set),
        ("${", Typescript::DOLLARLBRACE),
        ("new_expression", Typescript::NewExpression),
        ("{|", Typescript::LBRACEPIPE),
        ("else", Typescript::Else),
        ("for_statement", Typescript::ForStatement),
        ("type_arguments", Typescript::TypeArguments),
        ("constraint", Typescript::Constraint),
        ("for", Typescript::For),
        ("statement_identifier", Typescript::StatementIdentifier),
        ("non_null_expression", Typescript::NonNullExpression),
        ("template_string_repeat1", Typescript::TemplateStringRepeat1),
        ("class_heritage", Typescript::ClassHeritage),
        ("default_type", Typescript::DefaultType),
        (
            "abstract_method_signature",
            Typescript::AbstractMethodSignature,
        ),
        ("ambient_declaration", Typescript::AmbientDeclaration),
        ("sequence_expression", Typescript::SequenceExpression),
        ("end", Typescript::End),
        ("expression_statement", Typescript::ExpressionStatement),
        ("optional_parameter", Typescript::OptionalParameter),
        ("union_type", Typescript::UnionType),
        ("let", Typescript::Let),
        (
            "generator_function_declaration",
            Typescript::GeneratorFunctionDeclaration,
        ),
        (
            "implements_clause_repeat1",
            Typescript::ImplementsClauseRepeat1,
        ),
        ("switch_default", Typescript::SwitchDefault),
        ("typeof", Typescript::Typeof),
        ("++", Typescript::PLUSPLUS),
        ("_initializer", Typescript::Initializer),
        ("function_declaration", Typescript::FunctionDeclaration),
        ("enum_body", Typescript::EnumBody),
        ("symbol", Typescript::Symbol),
        ("tuple_type", Typescript::TupleType),
        ("binary_expression", Typescript::BinaryExpression),
        ("var", Typescript::Var),
        (
            "export_statement_repeat1",
            Typescript::ExportStatementRepeat1,
        ),
        ("member_expression", Typescript::MemberExpression),
        ("yield_expression", Typescript::YieldExpression),
        ("escape_sequence", Typescript::EscapeSequence),
        ("return_statement", Typescript::ReturnStatement),
        ("comment", Typescript::Comment),
        ("regex_flags", Typescript::RegexFlags),
        ("as_expression", Typescript::AsExpression),
        ("class", Typescript::Class),
        ("protected", Typescript::Protected),
        ("this", Typescript::This),
        (
            "augmented_assignment_expression",
            Typescript::AugmentedAssignmentExpression,
        ),
        ("super", Typescript::Super),
        ("number", Typescript::Number),
        ("lookup_type", Typescript::LookupType),
        (")", Typescript::RPAREN),
        ("{", Typescript::LBRACE),
        ("method_definition", Typescript::MethodDefinition),
        ("true", Typescript::True),
        ("extends_clause_repeat1", Typescript::ExtendsClauseRepeat1),
        ("unary_expression", Typescript::UnaryExpression),
        ("update_expression", Typescript::UpdateExpression),
        ("-", Typescript::DASH),
        ("of", Typescript::Of),
        (">>>=", Typescript::GTGTGTEQ),
        ("as", Typescript::As),
        ("|=", Typescript::PIPEEQ),
        ("catch_clause", Typescript::CatchClause),
        ("type", Typescript::Type),
        ("nested_identifier", Typescript::NestedIdentifier),
        ("implements_clause", Typescript::ImplementsClause),
        ("||", Typescript::PIPEPIPE),
        ("%", Typescript::PERCENT),
        ("@", Typescript::AT),
        ("_declaration", Typescript::Declaration),
        ("=>", Typescript::EQGT),
        ("switch_case", Typescript::SwitchCase),
        ("instanceof", Typescript::Instanceof),
        ("with", Typescript::With),
        ("abstract", Typescript::Abstract),
        ("program_repeat1", Typescript::ProgramRepeat1),
        ("`", Typescript::BQUOTE),
        ("await", Typescript::Await),
        ("get", Typescript::Get),
        ("namespace_import", Typescript::NamespaceImport),
        ("debugger_statement", Typescript::DebuggerStatement),
        ("generic_type", Typescript::GenericType),
        ("--", Typescript::DASHDASH),
        ("public", Typescript::Public),
        ("index_type_query", Typescript::IndexTypeQuery),
        ("assignment_expression", Typescript::AssignmentExpression),
        ("]", Typescript::RBRACK),
        ("module", Typescript::Module),
        ("generator_function", Typescript::GeneratorFunction),
        ("==", Typescript::EQEQ),
        ("return", Typescript::Return),
        ("if_statement", Typescript::IfStatement),
        ("undefined", Typescript::Undefined),
        ("type_parameter", Typescript::TypeParameter),
        ("export", Typescript::Export),
        ("pair", Typescript::Pair),
        ("string_token1", Typescript::StringToken1),
        ("in", Typescript::In),
        ("named_imports", Typescript::NamedImports),
        ("&&", Typescript::AMPAMP),
        ("_property_name", Typescript::PropertyName),
        ("debugger", Typescript::Debugger),
        ("type_alias_declaration", Typescript::TypeAliasDeclaration),
        ("array_type", Typescript::ArrayType),
        ("<", Typescript::LT),
        ("_expression", Typescript::Expression),
        ("void", Typescript::Void),
        ("-=", Typescript::DASHEQ),
        ("~", Typescript::TILDE),
        ("object_pattern", Typescript::ObjectPattern),
        ("named_imports_repeat1", Typescript::NamedImportsRepeat1),
        ("spread_element", Typescript::SpreadElement),
    ]),
};

impl From<&str> for Typescript {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for Typescript {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x) }
    }
}

// Typescript == u16
impl PartialEq<u16> for Typescript {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == Typescript::from(*x)
    }
}

// u16 == Typescript
impl PartialEq<Typescript> for u16 {
    #[inline(always)]
    fn eq(&self, x: &Typescript) -> bool {
        *x == *self
    }
}
