// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum Java {
    End = 0,
    Identifier = 1,
    DecimalIntegerLiteral = 2,
    HexIntegerLiteral = 3,
    OctalIntegerLiteral = 4,
    BinaryIntegerLiteral = 5,
    DecimalFloatingPointLiteral = 6,
    HexFloatingPointLiteral = 7,
    True = 8,
    False = 9,
    SQUOTE = 10,
    CharacterLiteralToken1 = 11,
    CharacterLiteralToken2 = 12,
    CharacterLiteralToken3 = 13,
    StringLiteral = 14,
    NullLiteral = 15,
    LPAREN = 16,
    AMP = 17,
    RPAREN = 18,
    EQ = 19,
    PLUSEQ = 20,
    DASHEQ = 21,
    STAREQ = 22,
    SLASHEQ = 23,
    AMPEQ = 24,
    PIPEEQ = 25,
    CARETEQ = 26,
    PERCENTEQ = 27,
    LTLTEQ = 28,
    GTGTEQ = 29,
    GTGTGTEQ = 30,
    GT = 31,
    LT = 32,
    EQEQ = 33,
    GTEQ = 34,
    LTEQ = 35,
    BANGEQ = 36,
    AMPAMP = 37,
    PIPEPIPE = 38,
    PLUS = 39,
    DASH = 40,
    STAR = 41,
    SLASH = 42,
    PIPE = 43,
    CARET = 44,
    PERCENT = 45,
    LTLT = 46,
    GTGT = 47,
    GTGTGT = 48,
    Instanceof = 49,
    DASHGT = 50,
    COMMA = 51,
    QMARK = 52,
    COLON = 53,
    BANG = 54,
    TILDE = 55,
    PLUSPLUS = 56,
    DASHDASH = 57,
    New = 58,
    LBRACK = 59,
    RBRACK = 60,
    DOT = 61,
    Class = 62,
    COLONCOLON = 63,
    Extends = 64,
    SEMI = 65,
    LBRACE = 66,
    RBRACE = 67,
    Assert = 68,
    Switch = 69,
    Case = 70,
    Default = 71,
    Do = 72,
    While = 73,
    Break = 74,
    Continue = 75,
    Return = 76,
    Synchronized = 77,
    Throw = 78,
    Try = 79,
    Catch = 80,
    Finally = 81,
    If = 82,
    Else = 83,
    For = 84,
    AT = 85,
    Open = 86,
    Module = 87,
    Requires = 88,
    Exports = 89,
    To = 90,
    Opens = 91,
    Uses = 92,
    Provides = 93,
    With = 94,
    Transitive = 95,
    Static = 96,
    Package = 97,
    Import = 98,
    Enum = 99,
    Public = 100,
    Protected = 101,
    Private = 102,
    Abstract = 103,
    Final = 104,
    Strictfp = 105,
    Native = 106,
    Transient = 107,
    Volatile = 108,
    Implements = 109,
    ATinterface = 110,
    Interface = 111,
    Byte = 112,
    Short = 113,
    Int = 114,
    Long = 115,
    Char = 116,
    Float = 117,
    Double = 118,
    BooleanType = 119,
    VoidType = 120,
    DOTDOTDOT = 121,
    Throws = 122,
    This = 123,
    Super = 124,
    Comment = 125,
    Program = 126,
    Literal = 127,
    CharacterLiteral = 128,
    Expression = 129,
    CastExpression = 130,
    AssignmentExpression = 131,
    BinaryExpression = 132,
    InstanceofExpression = 133,
    LambdaExpression = 134,
    InferredParameters = 135,
    TernaryExpression = 136,
    UnaryExpression = 137,
    UpdateExpression = 138,
    Primary = 139,
    ArrayCreationExpression = 140,
    DimensionsExpr = 141,
    PrimaryNoNewArray = 142,
    ParenthesizedExpression = 143,
    ClassLiteral = 144,
    ObjectCreationExpression = 145,
    UnqualifiedObjectCreationExpression = 146,
    FieldAccess = 147,
    ArrayAccess = 148,
    MethodInvocation = 149,
    ArgumentList = 150,
    MethodReference = 151,
    TypeArguments = 152,
    Wildcard = 153,
    WildcardBounds = 154,
    Dimensions = 155,
    Block = 156,
    ExpressionStatement = 157,
    LabeledStatement = 158,
    AssertStatement = 159,
    SwitchStatement = 160,
    SwitchBlock = 161,
    SwitchLabel = 162,
    DoStatement = 163,
    BreakStatement = 164,
    ContinueStatement = 165,
    ReturnStatement = 166,
    SynchronizedStatement = 167,
    ThrowStatement = 168,
    TryStatement = 169,
    CatchClause = 170,
    CatchFormalParameter = 171,
    CatchType = 172,
    FinallyClause = 173,
    TryWithResourcesStatement = 174,
    ResourceSpecification = 175,
    Resource = 176,
    IfStatement = 177,
    WhileStatement = 178,
    ForStatement = 179,
    ForInit = 180,
    EnhancedForStatement = 181,
    Annotation = 182,
    MarkerAnnotation = 183,
    Annotation2 = 184,
    AnnotationArgumentList = 185,
    ElementValuePair = 186,
    ElementValue = 187,
    ElementValueArrayInitializer = 188,
    Declaration = 189,
    ModuleDeclaration = 190,
    ModuleDirective = 191,
    RequiresModifier = 192,
    ModuleName = 193,
    PackageDeclaration = 194,
    ImportDeclaration = 195,
    Asterisk = 196,
    EnumDeclaration = 197,
    EnumBodyDeclarations = 198,
    EnumConstant = 199,
    ClassDeclaration = 200,
    Modifiers = 201,
    TypeParameters = 202,
    TypeParameter = 203,
    TypeBound = 204,
    Superclass = 205,
    SuperInterfaces = 206,
    InterfaceTypeList = 207,
    ClassBody = 208,
    StaticInitializer = 209,
    ConstructorDeclaration = 210,
    ConstructorDeclarator = 211,
    ConstructorBody = 212,
    ExplicitConstructorInvocation = 213,
    ScopedIdentifier = 214,
    FieldDeclaration = 215,
    InterfaceDeclaration = 216,
    AnnotationTypeDeclaration = 217,
    AnnotationTypeBody = 218,
    AnnotationTypeMemberDeclaration = 219,
    AnnotationTypeElementDeclaration = 220,
    DefaultValue = 221,
    NormalInterfaceDeclaration = 222,
    ExtendsInterfaces = 223,
    InterfaceBody = 224,
    InterfaceMemberDeclaration = 225,
    ConstantDeclaration = 226,
    VariableDeclaratorList = 227,
    VariableDeclarator = 228,
    VariableDeclaratorId = 229,
    ArrayInitializer = 230,
    Type = 231,
    UnannotatedType = 232,
    AnnotatedType = 233,
    ScopedTypeIdentifier = 234,
    GenericType = 235,
    ArrayType = 236,
    IntegralType = 237,
    FloatingPointType = 238,
    MethodHeader = 239,
    MethodDeclarator = 240,
    FormalParameters = 241,
    FormalParameter = 242,
    ReceiverParameter = 243,
    SpreadParameter = 244,
    Throws2 = 245,
    LocalVariableDeclarationStatement = 246,
    LocalVariableDeclaration = 247,
    MethodDeclaration = 248,
    ProgramRepeat1 = 249,
    CharacterLiteralRepeat1 = 250,
    CastExpressionRepeat1 = 251,
    InferredParametersRepeat1 = 252,
    ArrayCreationExpressionRepeat1 = 253,
    DimensionsExprRepeat1 = 254,
    ClassLiteralRepeat1 = 255,
    ArgumentListRepeat1 = 256,
    TypeArgumentsRepeat1 = 257,
    DimensionsRepeat1 = 258,
    SwitchBlockRepeat1 = 259,
    TryStatementRepeat1 = 260,
    CatchTypeRepeat1 = 261,
    ResourceSpecificationRepeat1 = 262,
    AnnotationArgumentListRepeat1 = 263,
    ElementValueArrayInitializerRepeat1 = 264,
    ModuleDeclarationRepeat1 = 265,
    ModuleDirectiveRepeat1 = 266,
    ModuleDirectiveRepeat2 = 267,
    ModuleDirectiveRepeat3 = 268,
    ImportDeclarationRepeat1 = 269,
    EnumDeclarationRepeat1 = 270,
    EnumBodyDeclarationsRepeat1 = 271,
    ModifiersRepeat1 = 272,
    TypeParametersRepeat1 = 273,
    InterfaceTypeListRepeat1 = 274,
    AnnotationTypeBodyRepeat1 = 275,
    InterfaceBodyRepeat1 = 276,
    VariableDeclaratorListRepeat1 = 277,
    ArrayInitializerRepeat1 = 278,
    FormalParametersRepeat1 = 279,
    TypeIdentifier = 280,
    Error = 281,
}

impl Into<&'static str> for Java {
    fn into(self) -> &'static str {
        match self {
            Java::End => "end",
            Java::Identifier => "identifier",
            Java::DecimalIntegerLiteral => "decimal_integer_literal",
            Java::HexIntegerLiteral => "hex_integer_literal",
            Java::OctalIntegerLiteral => "octal_integer_literal",
            Java::BinaryIntegerLiteral => "binary_integer_literal",
            Java::DecimalFloatingPointLiteral => "decimal_floating_point_literal",
            Java::HexFloatingPointLiteral => "hex_floating_point_literal",
            Java::True => "true",
            Java::False => "false",
            Java::SQUOTE => "'",
            Java::CharacterLiteralToken1 => "character_literal_token1",
            Java::CharacterLiteralToken2 => "character_literal_token2",
            Java::CharacterLiteralToken3 => "character_literal_token3",
            Java::StringLiteral => "string_literal",
            Java::NullLiteral => "null_literal",
            Java::LPAREN => "(",
            Java::AMP => "&",
            Java::RPAREN => ")",
            Java::EQ => "=",
            Java::PLUSEQ => "+=",
            Java::DASHEQ => "-=",
            Java::STAREQ => "*=",
            Java::SLASHEQ => "/=",
            Java::AMPEQ => "&=",
            Java::PIPEEQ => "|=",
            Java::CARETEQ => "^=",
            Java::PERCENTEQ => "%=",
            Java::LTLTEQ => "<<=",
            Java::GTGTEQ => ">>=",
            Java::GTGTGTEQ => ">>>=",
            Java::GT => ">",
            Java::LT => "<",
            Java::EQEQ => "==",
            Java::GTEQ => ">=",
            Java::LTEQ => "<=",
            Java::BANGEQ => "!=",
            Java::AMPAMP => "&&",
            Java::PIPEPIPE => "||",
            Java::PLUS => "+",
            Java::DASH => "-",
            Java::STAR => "*",
            Java::SLASH => "/",
            Java::PIPE => "|",
            Java::CARET => "^",
            Java::PERCENT => "%",
            Java::LTLT => "<<",
            Java::GTGT => ">>",
            Java::GTGTGT => ">>>",
            Java::Instanceof => "instanceof",
            Java::DASHGT => "->",
            Java::COMMA => ",",
            Java::QMARK => "?",
            Java::COLON => ":",
            Java::BANG => "!",
            Java::TILDE => "~",
            Java::PLUSPLUS => "++",
            Java::DASHDASH => "--",
            Java::New => "new",
            Java::LBRACK => "[",
            Java::RBRACK => "]",
            Java::DOT => ".",
            Java::Class => "class",
            Java::COLONCOLON => "::",
            Java::Extends => "extends",
            Java::SEMI => ";",
            Java::LBRACE => "{",
            Java::RBRACE => "}",
            Java::Assert => "assert",
            Java::Switch => "switch",
            Java::Case => "case",
            Java::Default => "default",
            Java::Do => "do",
            Java::While => "while",
            Java::Break => "break",
            Java::Continue => "continue",
            Java::Return => "return",
            Java::Synchronized => "synchronized",
            Java::Throw => "throw",
            Java::Try => "try",
            Java::Catch => "catch",
            Java::Finally => "finally",
            Java::If => "if",
            Java::Else => "else",
            Java::For => "for",
            Java::AT => "@",
            Java::Open => "open",
            Java::Module => "module",
            Java::Requires => "requires",
            Java::Exports => "exports",
            Java::To => "to",
            Java::Opens => "opens",
            Java::Uses => "uses",
            Java::Provides => "provides",
            Java::With => "with",
            Java::Transitive => "transitive",
            Java::Static => "static",
            Java::Package => "package",
            Java::Import => "import",
            Java::Enum => "enum",
            Java::Public => "public",
            Java::Protected => "protected",
            Java::Private => "private",
            Java::Abstract => "abstract",
            Java::Final => "final",
            Java::Strictfp => "strictfp",
            Java::Native => "native",
            Java::Transient => "transient",
            Java::Volatile => "volatile",
            Java::Implements => "implements",
            Java::ATinterface => "@interface",
            Java::Interface => "interface",
            Java::Byte => "byte",
            Java::Short => "short",
            Java::Int => "int",
            Java::Long => "long",
            Java::Char => "char",
            Java::Float => "float",
            Java::Double => "double",
            Java::BooleanType => "boolean_type",
            Java::VoidType => "void_type",
            Java::DOTDOTDOT => "...",
            Java::Throws => "throws",
            Java::This => "this",
            Java::Super => "super",
            Java::Comment => "comment",
            Java::Program => "program",
            Java::Literal => "_literal",
            Java::CharacterLiteral => "character_literal",
            Java::Expression => "_expression",
            Java::CastExpression => "cast_expression",
            Java::AssignmentExpression => "assignment_expression",
            Java::BinaryExpression => "binary_expression",
            Java::InstanceofExpression => "instanceof_expression",
            Java::LambdaExpression => "lambda_expression",
            Java::InferredParameters => "inferred_parameters",
            Java::TernaryExpression => "ternary_expression",
            Java::UnaryExpression => "unary_expression",
            Java::UpdateExpression => "update_expression",
            Java::Primary => "_primary",
            Java::ArrayCreationExpression => "array_creation_expression",
            Java::DimensionsExpr => "dimensions_expr",
            Java::PrimaryNoNewArray => "_primary_no_new_array",
            Java::ParenthesizedExpression => "parenthesized_expression",
            Java::ClassLiteral => "class_literal",
            Java::ObjectCreationExpression => "object_creation_expression",
            Java::UnqualifiedObjectCreationExpression => "_unqualified_object_creation_expression",
            Java::FieldAccess => "field_access",
            Java::ArrayAccess => "array_access",
            Java::MethodInvocation => "method_invocation",
            Java::ArgumentList => "argument_list",
            Java::MethodReference => "method_reference",
            Java::TypeArguments => "type_arguments",
            Java::Wildcard => "wildcard",
            Java::WildcardBounds => "_wildcard_bounds",
            Java::Dimensions => "dimensions",
            Java::Block => "block",
            Java::ExpressionStatement => "expression_statement",
            Java::LabeledStatement => "labeled_statement",
            Java::AssertStatement => "assert_statement",
            Java::SwitchStatement => "switch_statement",
            Java::SwitchBlock => "switch_block",
            Java::SwitchLabel => "switch_label",
            Java::DoStatement => "do_statement",
            Java::BreakStatement => "break_statement",
            Java::ContinueStatement => "continue_statement",
            Java::ReturnStatement => "return_statement",
            Java::SynchronizedStatement => "synchronized_statement",
            Java::ThrowStatement => "throw_statement",
            Java::TryStatement => "try_statement",
            Java::CatchClause => "catch_clause",
            Java::CatchFormalParameter => "catch_formal_parameter",
            Java::CatchType => "catch_type",
            Java::FinallyClause => "finally_clause",
            Java::TryWithResourcesStatement => "try_with_resources_statement",
            Java::ResourceSpecification => "resource_specification",
            Java::Resource => "resource",
            Java::IfStatement => "if_statement",
            Java::WhileStatement => "while_statement",
            Java::ForStatement => "for_statement",
            Java::ForInit => "for_init",
            Java::EnhancedForStatement => "enhanced_for_statement",
            Java::Annotation => "_annotation",
            Java::MarkerAnnotation => "marker_annotation",
            Java::Annotation2 => "annotation",
            Java::AnnotationArgumentList => "annotation_argument_list",
            Java::ElementValuePair => "element_value_pair",
            Java::ElementValue => "_element_value",
            Java::ElementValueArrayInitializer => "element_value_array_initializer",
            Java::Declaration => "_declaration",
            Java::ModuleDeclaration => "module_declaration",
            Java::ModuleDirective => "module_directive",
            Java::RequiresModifier => "requires_modifier",
            Java::ModuleName => "module_name",
            Java::PackageDeclaration => "package_declaration",
            Java::ImportDeclaration => "import_declaration",
            Java::Asterisk => "asterisk",
            Java::EnumDeclaration => "enum_declaration",
            Java::EnumBodyDeclarations => "enum_body_declarations",
            Java::EnumConstant => "enum_constant",
            Java::ClassDeclaration => "class_declaration",
            Java::Modifiers => "modifiers",
            Java::TypeParameters => "type_parameters",
            Java::TypeParameter => "type_parameter",
            Java::TypeBound => "type_bound",
            Java::Superclass => "superclass",
            Java::SuperInterfaces => "super_interfaces",
            Java::InterfaceTypeList => "interface_type_list",
            Java::ClassBody => "class_body",
            Java::StaticInitializer => "static_initializer",
            Java::ConstructorDeclaration => "constructor_declaration",
            Java::ConstructorDeclarator => "constructor_declarator",
            Java::ConstructorBody => "constructor_body",
            Java::ExplicitConstructorInvocation => "explicit_constructor_invocation",
            Java::ScopedIdentifier => "scoped_identifier",
            Java::FieldDeclaration => "field_declaration",
            Java::InterfaceDeclaration => "interface_declaration",
            Java::AnnotationTypeDeclaration => "annotation_type_declaration",
            Java::AnnotationTypeBody => "annotation_type_body",
            Java::AnnotationTypeMemberDeclaration => "annotation_type_member_declaration",
            Java::AnnotationTypeElementDeclaration => "annotation_type_element_declaration",
            Java::DefaultValue => "default_value",
            Java::NormalInterfaceDeclaration => "normal_interface_declaration",
            Java::ExtendsInterfaces => "extends_interfaces",
            Java::InterfaceBody => "interface_body",
            Java::InterfaceMemberDeclaration => "interface_member_declaration",
            Java::ConstantDeclaration => "constant_declaration",
            Java::VariableDeclaratorList => "_variable_declarator_list",
            Java::VariableDeclarator => "variable_declarator",
            Java::VariableDeclaratorId => "_variable_declarator_id",
            Java::ArrayInitializer => "array_initializer",
            Java::Type => "_type",
            Java::UnannotatedType => "_unannotated_type",
            Java::AnnotatedType => "annotated_type",
            Java::ScopedTypeIdentifier => "scoped_type_identifier",
            Java::GenericType => "generic_type",
            Java::ArrayType => "array_type",
            Java::IntegralType => "integral_type",
            Java::FloatingPointType => "floating_point_type",
            Java::MethodHeader => "_method_header",
            Java::MethodDeclarator => "_method_declarator",
            Java::FormalParameters => "formal_parameters",
            Java::FormalParameter => "formal_parameter",
            Java::ReceiverParameter => "receiver_parameter",
            Java::SpreadParameter => "spread_parameter",
            Java::Throws2 => "throws",
            Java::LocalVariableDeclarationStatement => "local_variable_declaration_statement",
            Java::LocalVariableDeclaration => "local_variable_declaration",
            Java::MethodDeclaration => "method_declaration",
            Java::ProgramRepeat1 => "program_repeat1",
            Java::CharacterLiteralRepeat1 => "character_literal_repeat1",
            Java::CastExpressionRepeat1 => "cast_expression_repeat1",
            Java::InferredParametersRepeat1 => "inferred_parameters_repeat1",
            Java::ArrayCreationExpressionRepeat1 => "array_creation_expression_repeat1",
            Java::DimensionsExprRepeat1 => "dimensions_expr_repeat1",
            Java::ClassLiteralRepeat1 => "class_literal_repeat1",
            Java::ArgumentListRepeat1 => "argument_list_repeat1",
            Java::TypeArgumentsRepeat1 => "type_arguments_repeat1",
            Java::DimensionsRepeat1 => "dimensions_repeat1",
            Java::SwitchBlockRepeat1 => "switch_block_repeat1",
            Java::TryStatementRepeat1 => "try_statement_repeat1",
            Java::CatchTypeRepeat1 => "catch_type_repeat1",
            Java::ResourceSpecificationRepeat1 => "resource_specification_repeat1",
            Java::AnnotationArgumentListRepeat1 => "annotation_argument_list_repeat1",
            Java::ElementValueArrayInitializerRepeat1 => "element_value_array_initializer_repeat1",
            Java::ModuleDeclarationRepeat1 => "module_declaration_repeat1",
            Java::ModuleDirectiveRepeat1 => "module_directive_repeat1",
            Java::ModuleDirectiveRepeat2 => "module_directive_repeat2",
            Java::ModuleDirectiveRepeat3 => "module_directive_repeat3",
            Java::ImportDeclarationRepeat1 => "import_declaration_repeat1",
            Java::EnumDeclarationRepeat1 => "enum_declaration_repeat1",
            Java::EnumBodyDeclarationsRepeat1 => "enum_body_declarations_repeat1",
            Java::ModifiersRepeat1 => "modifiers_repeat1",
            Java::TypeParametersRepeat1 => "type_parameters_repeat1",
            Java::InterfaceTypeListRepeat1 => "interface_type_list_repeat1",
            Java::AnnotationTypeBodyRepeat1 => "annotation_type_body_repeat1",
            Java::InterfaceBodyRepeat1 => "interface_body_repeat1",
            Java::VariableDeclaratorListRepeat1 => "_variable_declarator_list_repeat1",
            Java::ArrayInitializerRepeat1 => "array_initializer_repeat1",
            Java::FormalParametersRepeat1 => "formal_parameters_repeat1",
            Java::TypeIdentifier => "type_identifier",
            Java::Error => "ERROR",
        }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, Java> = ::phf::Map {
    key: 732231254413039614,
    disps: ::phf::Slice::Static(&[
        (3, 188),
        (0, 37),
        (0, 95),
        (0, 213),
        (0, 0),
        (0, 90),
        (0, 34),
        (0, 52),
        (0, 73),
        (2, 88),
        (0, 96),
        (0, 7),
        (5, 123),
        (0, 4),
        (0, 34),
        (0, 1),
        (19, 208),
        (1, 0),
        (0, 44),
        (0, 36),
        (17, 146),
        (1, 244),
        (6, 77),
        (0, 22),
        (0, 5),
        (0, 2),
        (0, 206),
        (0, 28),
        (4, 112),
        (0, 2),
        (0, 178),
        (16, 86),
        (0, 198),
        (6, 223),
        (0, 16),
        (0, 0),
        (0, 9),
        (0, 13),
        (0, 195),
        (4, 176),
        (1, 62),
        (1, 11),
        (1, 181),
        (1, 33),
        (0, 31),
        (0, 0),
        (0, 23),
        (1, 111),
        (0, 261),
        (0, 10),
        (15, 125),
        (0, 194),
        (0, 33),
        (108, 168),
        (0, 1),
        (0, 4),
    ]),
    entries: ::phf::Slice::Static(&[
        ("volatile", Java::Volatile),
        ("strictfp", Java::Strictfp),
        ("scoped_identifier", Java::ScopedIdentifier),
        ("case", Java::Case),
        ("requires_modifier", Java::RequiresModifier),
        ("resource_specification", Java::ResourceSpecification),
        ("import", Java::Import),
        ("parenthesized_expression", Java::ParenthesizedExpression),
        ("argument_list_repeat1", Java::ArgumentListRepeat1),
        ("integral_type", Java::IntegralType),
        ("character_literal_repeat1", Java::CharacterLiteralRepeat1),
        ("return_statement", Java::ReturnStatement),
        ("marker_annotation", Java::MarkerAnnotation),
        ("catch_formal_parameter", Java::CatchFormalParameter),
        ("wildcard", Java::Wildcard),
        ("program", Java::Program),
        ("enum_declaration", Java::EnumDeclaration),
        ("_element_value", Java::ElementValue),
        ("public", Java::Public),
        ("asterisk", Java::Asterisk),
        ("method_invocation", Java::MethodInvocation),
        ("^=", Java::CARETEQ),
        (">>=", Java::GTGTEQ),
        ("!=", Java::BANGEQ),
        ("requires", Java::Requires),
        ("import_declaration", Java::ImportDeclaration),
        ("_primary_no_new_array", Java::PrimaryNoNewArray),
        ("array_creation_expression", Java::ArrayCreationExpression),
        ("dimensions_repeat1", Java::DimensionsRepeat1),
        ("class", Java::Class),
        ("synchronized_statement", Java::SynchronizedStatement),
        ("with", Java::With),
        ("<<=", Java::LTLTEQ),
        ("_unannotated_type", Java::UnannotatedType),
        ("/=", Java::SLASHEQ),
        ("=", Java::EQ),
        ("for", Java::For),
        ("type_parameter", Java::TypeParameter),
        ("_type", Java::Type),
        ("dimensions", Java::Dimensions),
        ("binary_expression", Java::BinaryExpression),
        (
            "interface_member_declaration",
            Java::InterfaceMemberDeclaration,
        ),
        ("character_literal_token1", Java::CharacterLiteralToken1),
        ("try_statement_repeat1", Java::TryStatementRepeat1),
        ("enhanced_for_statement", Java::EnhancedForStatement),
        ("switch_statement", Java::SwitchStatement),
        ("?", Java::QMARK),
        ("else", Java::Else),
        ("ERROR", Java::Error),
        ("switch_block", Java::SwitchBlock),
        ("field_declaration", Java::FieldDeclaration),
        ("_variable_declarator_list", Java::VariableDeclaratorList),
        ("break", Java::Break),
        (
            "annotation_type_element_declaration",
            Java::AnnotationTypeElementDeclaration,
        ),
        ("formal_parameters_repeat1", Java::FormalParametersRepeat1),
        ("formal_parameters", Java::FormalParameters),
        ("*", Java::STAR),
        ("default_value", Java::DefaultValue),
        ("module_directive_repeat2", Java::ModuleDirectiveRepeat2),
        ("]", Java::RBRACK),
        ("modifiers", Java::Modifiers),
        (
            "array_creation_expression_repeat1",
            Java::ArrayCreationExpressionRepeat1,
        ),
        ("resource", Java::Resource),
        ("abstract", Java::Abstract),
        ("_method_header", Java::MethodHeader),
        ("dimensions_expr", Java::DimensionsExpr),
        ("~", Java::TILDE),
        ("modifiers_repeat1", Java::ModifiersRepeat1),
        ("block", Java::Block),
        (
            "normal_interface_declaration",
            Java::NormalInterfaceDeclaration,
        ),
        ("hex_floating_point_literal", Java::HexFloatingPointLiteral),
        ("&=", Java::AMPEQ),
        ("method_declaration", Java::MethodDeclaration),
        (
            "_variable_declarator_list_repeat1",
            Java::VariableDeclaratorListRepeat1,
        ),
        ("enum_constant", Java::EnumConstant),
        ("class_literal_repeat1", Java::ClassLiteralRepeat1),
        ("object_creation_expression", Java::ObjectCreationExpression),
        ("-", Java::DASH),
        ("throw", Java::Throw),
        ("%", Java::PERCENT),
        ("throws", Java::Throws),
        ("method_reference", Java::MethodReference),
        (":", Java::COLON),
        ("final", Java::Final),
        ("ternary_expression", Java::TernaryExpression),
        ("_primary", Java::Primary),
        ("(", Java::LPAREN),
        ("catch_clause", Java::CatchClause),
        ("array_initializer", Java::ArrayInitializer),
        ("protected", Java::Protected),
        (".", Java::DOT),
        ("spread_parameter", Java::SpreadParameter),
        ("extends_interfaces", Java::ExtendsInterfaces),
        ("continue", Java::Continue),
        ("enum", Java::Enum),
        ("update_expression", Java::UpdateExpression),
        ("+=", Java::PLUSEQ),
        ("short", Java::Short),
        (
            "annotation_type_body_repeat1",
            Java::AnnotationTypeBodyRepeat1,
        ),
        ("finally_clause", Java::FinallyClause),
        ("return", Java::Return),
        ("extends", Java::Extends),
        ("@interface", Java::ATinterface),
        ("assert", Java::Assert),
        ("==", Java::EQEQ),
        ("instanceof_expression", Java::InstanceofExpression),
        ("char", Java::Char),
        ("local_variable_declaration", Java::LocalVariableDeclaration),
        ("+", Java::PLUS),
        ("import_declaration_repeat1", Java::ImportDeclarationRepeat1),
        ("true", Java::True),
        ("interface_type_list", Java::InterfaceTypeList),
        ("new", Java::New),
        ("module_declaration", Java::ModuleDeclaration),
        ("argument_list", Java::ArgumentList),
        ("cast_expression", Java::CastExpression),
        ("::", Java::COLONCOLON),
        ("catch_type", Java::CatchType),
        ("type_bound", Java::TypeBound),
        ("class_declaration", Java::ClassDeclaration),
        ("unary_expression", Java::UnaryExpression),
        ("provides", Java::Provides),
        ("inferred_parameters", Java::InferredParameters),
        ("throw_statement", Java::ThrowStatement),
        ("switch_label", Java::SwitchLabel),
        ("_expression", Java::Expression),
        (
            "enum_body_declarations_repeat1",
            Java::EnumBodyDeclarationsRepeat1,
        ),
        ("&&", Java::AMPAMP),
        (">>>=", Java::GTGTGTEQ),
        ("_variable_declarator_id", Java::VariableDeclaratorId),
        ("annotated_type", Java::AnnotatedType),
        ("class_body", Java::ClassBody),
        ("_annotation", Java::Annotation),
        ("static_initializer", Java::StaticInitializer),
        ("interface", Java::Interface),
        ("package", Java::Package),
        ("super_interfaces", Java::SuperInterfaces),
        ("!", Java::BANG),
        (
            "annotation_type_declaration",
            Java::AnnotationTypeDeclaration,
        ),
        ("interface_body", Java::InterfaceBody),
        ("finally", Java::Finally),
        ("identifier", Java::Identifier),
        ("try_statement", Java::TryStatement),
        ("floating_point_type", Java::FloatingPointType),
        ("package_declaration", Java::PackageDeclaration),
        ("^", Java::CARET),
        ("this", Java::This),
        ("synchronized", Java::Synchronized),
        ("&", Java::AMP),
        ("superclass", Java::Superclass),
        ("/", Java::SLASH),
        ("to", Java::To),
        ("instanceof", Java::Instanceof),
        ("module_directive_repeat3", Java::ModuleDirectiveRepeat3),
        ("constant_declaration", Java::ConstantDeclaration),
        ("interface_body_repeat1", Java::InterfaceBodyRepeat1),
        (
            "inferred_parameters_repeat1",
            Java::InferredParametersRepeat1,
        ),
        ("do_statement", Java::DoStatement),
        ("module_declaration_repeat1", Java::ModuleDeclarationRepeat1),
        ("catch", Java::Catch),
        ("for_statement", Java::ForStatement),
        ("native", Java::Native),
        ("}", Java::RBRACE),
        ("--", Java::DASHDASH),
        ("constructor_body", Java::ConstructorBody),
        ("while", Java::While),
        ("enum_declaration_repeat1", Java::EnumDeclarationRepeat1),
        ("type_parameters", Java::TypeParameters),
        ("catch_type_repeat1", Java::CatchTypeRepeat1),
        ("while_statement", Java::WhileStatement),
        ("|=", Java::PIPEEQ),
        ("end", Java::End),
        (";", Java::SEMI),
        ("transitive", Java::Transitive),
        (">>>", Java::GTGTGT),
        ("cast_expression_repeat1", Java::CastExpressionRepeat1),
        ("int", Java::Int),
        (
            "_unqualified_object_creation_expression",
            Java::UnqualifiedObjectCreationExpression,
        ),
        ("lambda_expression", Java::LambdaExpression),
        ("comment", Java::Comment),
        ("scoped_type_identifier", Java::ScopedTypeIdentifier),
        ("expression_statement", Java::ExpressionStatement),
        ("array_access", Java::ArrayAccess),
        ("long", Java::Long),
        ("open", Java::Open),
        ("continue_statement", Java::ContinueStatement),
        (">", Java::GT),
        ("_literal", Java::Literal),
        ("assignment_expression", Java::AssignmentExpression),
        ("module_directive", Java::ModuleDirective),
        (
            "resource_specification_repeat1",
            Java::ResourceSpecificationRepeat1,
        ),
        ("switch", Java::Switch),
        ("void_type", Java::VoidType),
        ("module_directive_repeat1", Java::ModuleDirectiveRepeat1),
        ("class_literal", Java::ClassLiteral),
        ("<", Java::LT),
        ("transient", Java::Transient),
        ("[", Java::LBRACK),
        ("false", Java::False),
        ("if_statement", Java::IfStatement),
        ("-=", Java::DASHEQ),
        (")", Java::RPAREN),
        ("super", Java::Super),
        ("element_value_pair", Java::ElementValuePair),
        (">=", Java::GTEQ),
        ("type_arguments_repeat1", Java::TypeArgumentsRepeat1),
        ("variable_declarator", Java::VariableDeclarator),
        ("if", Java::If),
        ("_declaration", Java::Declaration),
        ("%=", Java::PERCENTEQ),
        ("labeled_statement", Java::LabeledStatement),
        ("implements", Java::Implements),
        ("++", Java::PLUSPLUS),
        ("default", Java::Default),
        ("decimal_integer_literal", Java::DecimalIntegerLiteral),
        ("*=", Java::STAREQ),
        ("program_repeat1", Java::ProgramRepeat1),
        ("receiver_parameter", Java::ReceiverParameter),
        ("module", Java::Module),
        ("constructor_declarator", Java::ConstructorDeclarator),
        (
            "interface_type_list_repeat1",
            Java::InterfaceTypeListRepeat1,
        ),
        ("@", Java::AT),
        ("character_literal", Java::CharacterLiteral),
        ("interface_declaration", Java::InterfaceDeclaration),
        ("character_literal_token3", Java::CharacterLiteralToken3),
        ("->", Java::DASHGT),
        ("|", Java::PIPE),
        ("assert_statement", Java::AssertStatement),
        ("exports", Java::Exports),
        ("type_identifier", Java::TypeIdentifier),
        ("break_statement", Java::BreakStatement),
        ("generic_type", Java::GenericType),
        ("string_literal", Java::StringLiteral),
        ("_wildcard_bounds", Java::WildcardBounds),
        ("binary_integer_literal", Java::BinaryIntegerLiteral),
        (
            "decimal_floating_point_literal",
            Java::DecimalFloatingPointLiteral,
        ),
        ("annotation_argument_list", Java::AnnotationArgumentList),
        ("float", Java::Float),
        (
            "annotation_type_member_declaration",
            Java::AnnotationTypeMemberDeclaration,
        ),
        ("for_init", Java::ForInit),
        (
            "explicit_constructor_invocation",
            Java::ExplicitConstructorInvocation,
        ),
        ("octal_integer_literal", Java::OctalIntegerLiteral),
        ("private", Java::Private),
        ("boolean_type", Java::BooleanType),
        ("byte", Java::Byte),
        (
            "element_value_array_initializer_repeat1",
            Java::ElementValueArrayInitializerRepeat1,
        ),
        ("uses", Java::Uses),
        ("type_arguments", Java::TypeArguments),
        ("character_literal_token2", Java::CharacterLiteralToken2),
        (
            "annotation_argument_list_repeat1",
            Java::AnnotationArgumentListRepeat1,
        ),
        ("formal_parameter", Java::FormalParameter),
        (
            "try_with_resources_statement",
            Java::TryWithResourcesStatement,
        ),
        (">>", Java::GTGT),
        ("||", Java::PIPEPIPE),
        (",", Java::COMMA),
        ("type_parameters_repeat1", Java::TypeParametersRepeat1),
        ("field_access", Java::FieldAccess),
        ("<=", Java::LTEQ),
        ("do", Java::Do),
        ("constructor_declaration", Java::ConstructorDeclaration),
        ("annotation_type_body", Java::AnnotationTypeBody),
        ("module_name", Java::ModuleName),
        ("\'", Java::SQUOTE),
        ("{", Java::LBRACE),
        ("static", Java::Static),
        ("array_initializer_repeat1", Java::ArrayInitializerRepeat1),
        ("...", Java::DOTDOTDOT),
        (
            "element_value_array_initializer",
            Java::ElementValueArrayInitializer,
        ),
        (
            "local_variable_declaration_statement",
            Java::LocalVariableDeclarationStatement,
        ),
        ("switch_block_repeat1", Java::SwitchBlockRepeat1),
        ("null_literal", Java::NullLiteral),
        ("_method_declarator", Java::MethodDeclarator),
        ("double", Java::Double),
        ("hex_integer_literal", Java::HexIntegerLiteral),
        ("dimensions_expr_repeat1", Java::DimensionsExprRepeat1),
        ("array_type", Java::ArrayType),
        ("try", Java::Try),
        ("<<", Java::LTLT),
        ("enum_body_declarations", Java::EnumBodyDeclarations),
        ("opens", Java::Opens),
    ]),
};

impl From<&str> for Java {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for Java {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x) }
    }
}

// Java == u16
impl PartialEq<u16> for Java {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == Java::from(*x)
    }
}

// u16 == Java
impl PartialEq<Java> for u16 {
    #[inline(always)]
    fn eq(&self, x: &Java) -> bool {
        *x == *self
    }
}
