// Code generated; DO NOT EDIT.

#[derive(Clone, Debug, PartialEq)]
pub enum Cpp {
    End = 0,
    Identifier = 1,
    Macro = 2,
    LF = 3,
    HASHinclude = 4,
    HASHdefine = 5,
    LPAREN = 6,
    PreprocParamsToken1 = 7,
    DOTDOTDOT = 8,
    COMMA = 9,
    RPAREN = 10,
    HASHif = 11,
    HASHendif = 12,
    HASHifdef = 13,
    HASHifndef = 14,
    HASHelse = 15,
    HASHelif = 16,
    PreprocDirective = 17,
    PreprocArg = 18,
    LPAREN2 = 19,
    Defined = 20,
    BANG = 21,
    TILDE = 22,
    DASH = 23,
    PLUS = 24,
    STAR = 25,
    SLASH = 26,
    PERCENT = 27,
    PIPEPIPE = 28,
    AMPAMP = 29,
    PIPE = 30,
    CARET = 31,
    AMP = 32,
    EQEQ = 33,
    BANGEQ = 34,
    GT = 35,
    GTEQ = 36,
    LTEQ = 37,
    LT = 38,
    LTLT = 39,
    GTGT = 40,
    Cdecl = 41,
    Clrcall = 42,
    Stdcall = 43,
    Fastcall = 44,
    Thiscall = 45,
    Vectorcall = 46,
    WINAPI = 47,
    CALLBACK = 48,
    SEMI = 49,
    Typedef = 50,
    Extern = 51,
    Attribute = 52,
    LBRACE = 53,
    RBRACE = 54,
    LBRACK = 55,
    RBRACK = 56,
    EQ = 57,
    Static = 58,
    Register = 59,
    Inline = 60,
    Const = 61,
    CONST = 62,
    Volatile = 63,
    Restrict = 64,
    Vector = 65,
    Atomic = 66,
    Mutable = 67,
    Explicit = 68,
    Constexpr = 69,
    Signed = 70,
    Unsigned = 71,
    Long = 72,
    Short = 73,
    PrimitiveType = 74,
    Enum = 75,
    Struct = 76,
    Union = 77,
    COLON = 78,
    If = 79,
    Else = 80,
    Switch = 81,
    Case = 82,
    Default = 83,
    While = 84,
    Do = 85,
    For = 86,
    Return = 87,
    Break = 88,
    Continue = 89,
    Goto = 90,
    QMARK = 91,
    STAREQ = 92,
    SLASHEQ = 93,
    PERCENTEQ = 94,
    PLUSEQ = 95,
    DASHEQ = 96,
    LTLTEQ = 97,
    GTGTEQ = 98,
    AMPEQ = 99,
    CARETEQ = 100,
    PIPEEQ = 101,
    DASHDASH = 102,
    PLUSPLUS = 103,
    Sizeof = 104,
    DOT = 105,
    DASHGT = 106,
    NumberLiteral = 107,
    LSQUOTE = 108,
    USQUOTE = 109,
    USQUOTE2 = 110,
    U8SQUOTE = 111,
    SQUOTE = 112,
    CharLiteralToken1 = 113,
    LDQUOTE = 114,
    UDQUOTE = 115,
    UDQUOTE2 = 116,
    U8DQUOTE = 117,
    DQUOTE = 118,
    StringLiteralToken1 = 119,
    EscapeSequence = 120,
    SystemLibString = 121,
    True = 122,
    False = 123,
    Null = 124,
    Comment = 125,
    Class = 126,
    Final = 127,
    Override = 128,
    Virtual = 129,
    Public = 130,
    Private = 131,
    Protected = 132,
    Auto = 133,
    Typename = 134,
    Template = 135,
    GT2 = 136,
    Delete = 137,
    Friend = 138,
    Noexcept = 139,
    Throw = 140,
    Namespace = 141,
    Using = 142,
    Try = 143,
    Catch = 144,
    LBRACKLBRACK = 145,
    RBRACKRBRACK = 146,
    New = 147,
    COLONCOLON = 148,
    OperatorName = 149,
    Nullptr = 150,
    RawStringLiteral = 151,
    TranslationUnit = 152,
    OnlyMacro = 153,
    MacroCall = 154,
    OnlyMacroCall = 155,
    PreprocInclude = 156,
    PreprocDef = 157,
    PreprocFunctionDef = 158,
    PreprocParams = 159,
    PreprocCall = 160,
    PreprocIf = 161,
    PreprocIfdef = 162,
    PreprocElse = 163,
    PreprocElif = 164,
    PreprocIf2 = 165,
    PreprocIfdef2 = 166,
    PreprocElse2 = 167,
    PreprocElif2 = 168,
    LineContinuation = 169,
    PreprocCondition = 170,
    PreprocExpression = 171,
    PreprocParenthesizedExpression = 172,
    PreprocDefined = 173,
    PreprocUnaryExpression = 174,
    PreprocBinaryExpression = 175,
    CallConvention = 176,
    FunctionDefinition = 177,
    Declaration = 178,
    TypeDefinition = 179,
    DeclarationSpecifiers = 180,
    DeclarationSpecifiersNoType = 181,
    LinkageSpecification = 182,
    AttributeSpecifier = 183,
    DeclarationList = 184,
    Declarator = 185,
    FieldDeclarator = 186,
    TypeDeclarator = 187,
    AbstractDeclarator = 188,
    ParenthesizedDeclarator = 189,
    ParenthesizedDeclarator2 = 190,
    ParenthesizedDeclarator3 = 191,
    AbstractParenthesizedDeclarator = 192,
    PointerDeclarator = 193,
    PointerDeclarator2 = 194,
    PointerDeclarator3 = 195,
    AbstractPointerDeclarator = 196,
    FunctionDeclarator = 197,
    FunctionDeclarator2 = 198,
    FunctionDeclarator3 = 199,
    AbstractFunctionDeclarator = 200,
    ArrayDeclarator = 201,
    ArrayDeclarator2 = 202,
    ArrayDeclarator3 = 203,
    AbstractArrayDeclarator = 204,
    InitDeclarator = 205,
    CompoundStatement = 206,
    StorageClassSpecifier = 207,
    TypeQualifier = 208,
    TypeSpecifier = 209,
    SizedTypeSpecifier = 210,
    EnumSpecifier = 211,
    EnumeratorList = 212,
    StructSpecifier = 213,
    UnionSpecifier = 214,
    FieldDeclarationList = 215,
    FieldDeclarationListItem = 216,
    FieldDeclaration = 217,
    BitfieldClause = 218,
    Enumerator = 219,
    ParameterList = 220,
    ParameterDeclaration = 221,
    LabeledStatement = 222,
    ExpressionStatement = 223,
    IfStatement = 224,
    SwitchStatement = 225,
    CompoundStatement2 = 226,
    CaseStatement = 227,
    WhileStatement = 228,
    DoStatement = 229,
    ForStatement = 230,
    ReturnStatement = 231,
    BreakStatement = 232,
    ContinueStatement = 233,
    GotoStatement = 234,
    Expression = 235,
    CommaExpression = 236,
    ConditionalExpression = 237,
    AssignmentExpression = 238,
    PointerExpression = 239,
    UnaryExpression = 240,
    BinaryExpression = 241,
    UpdateExpression = 242,
    CastExpression = 243,
    TypeDescriptor = 244,
    SizeofExpression = 245,
    SubscriptExpression = 246,
    CallExpression = 247,
    ArgumentList = 248,
    FieldExpression = 249,
    CompoundLiteralExpression = 250,
    ParenthesizedExpression = 251,
    InitializerList = 252,
    InitializerPair = 253,
    SubscriptDesignator = 254,
    FieldDesignator = 255,
    CharLiteral = 256,
    ConcatenatedString = 257,
    StringLiteral = 258,
    EmptyDeclaration = 259,
    ClassSpecifier = 260,
    VirtualSpecifier = 261,
    VirtualFunctionSpecifier = 262,
    BaseClassClause = 263,
    DependentType = 264,
    TemplateDeclaration = 265,
    TemplateInstantiation = 266,
    TemplateParameterList = 267,
    TypeParameterDeclaration = 268,
    VariadicTypeParameterDeclaration = 269,
    OptionalTypeParameterDeclaration = 270,
    OptionalParameterDeclaration = 271,
    VariadicParameterDeclaration = 272,
    VariadicDeclarator = 273,
    ReferenceDeclarator = 274,
    FieldInitializerList = 275,
    FieldInitializer = 276,
    FunctionDefinition2 = 277,
    FunctionDefinition3 = 278,
    Declaration2 = 279,
    DefaultMethodClause = 280,
    DeleteMethodClause = 281,
    FriendDeclaration = 282,
    AccessSpecifier = 283,
    ReferenceDeclarator2 = 284,
    ReferenceDeclarator3 = 285,
    AbstractReferenceDeclarator = 286,
    StructuredBindingDeclarator = 287,
    TrailingReturnType = 288,
    Noexcept2 = 289,
    ThrowSpecifier = 290,
    TemplateType = 291,
    TemplateMethod = 292,
    TemplateFunction = 293,
    TemplateArgumentList = 294,
    NamespaceDefinition = 295,
    UsingDeclaration = 296,
    AliasDeclaration = 297,
    ForRangeLoop = 298,
    ThrowStatement = 299,
    TryStatement = 300,
    CatchClause = 301,
    Attribute2 = 302,
    NewExpression = 303,
    NewDeclarator = 304,
    DeleteExpression = 305,
    LambdaExpression = 306,
    LambdaCaptureSpecifier = 307,
    LambdaDefaultCapture = 308,
    DestructorName = 309,
    ScopedFieldIdentifier = 310,
    ScopedIdentifier = 311,
    ScopedTypeIdentifier = 312,
    ScopedNamespaceIdentifier = 313,
    TranslationUnitRepeat1 = 314,
    PreprocParamsRepeat1 = 315,
    PreprocIfInFieldDeclarationListRepeat1 = 316,
    PreprocExpressionRepeat1 = 317,
    FunctionDefinitionRepeat1 = 318,
    DeclarationRepeat1 = 319,
    TypeDefinitionRepeat1 = 320,
    TypeDefinitionRepeat2 = 321,
    DeclarationSpecifiersRepeat1 = 322,
    DeclarationSpecifiersRepeat2 = 323,
    PointerDeclaratorRepeat1 = 324,
    FunctionDeclaratorRepeat1 = 325,
    FunctionDeclaratorRepeat2 = 326,
    AbstractFunctionDeclaratorRepeat1 = 327,
    SizedTypeSpecifierRepeat1 = 328,
    EnumeratorListRepeat1 = 329,
    FieldDeclarationRepeat1 = 330,
    ParameterListRepeat1 = 331,
    SwitchBodyRepeat1 = 332,
    CaseStatementRepeat1 = 333,
    ArgumentListRepeat1 = 334,
    InitializerListRepeat1 = 335,
    InitializerPairRepeat1 = 336,
    ConcatenatedStringRepeat1 = 337,
    StringLiteralRepeat1 = 338,
    BaseClassClauseRepeat1 = 339,
    TemplateParameterListRepeat1 = 340,
    FieldInitializerListRepeat1 = 341,
    StructuredBindingDeclaratorRepeat1 = 342,
    ThrowSpecifierRepeat1 = 343,
    TemplateArgumentListRepeat1 = 344,
    TryStatementRepeat1 = 345,
    AttributeRepeat1 = 346,
    NamespaceIdentifier = 347,
    FieldIdentifier = 348,
    StatementIdentifier = 349,
    TypeIdentifier = 350,
    Error = 351,
    
}

impl Into<&'static str> for Cpp {
    fn into(self) -> &'static str {
        match self {
            Cpp::End => "end",
            Cpp::Identifier => "identifier",
            Cpp::Macro => "macro",
            Cpp::LF => "\n",
            Cpp::HASHinclude => "#include",
            Cpp::HASHdefine => "#define",
            Cpp::LPAREN => "(",
            Cpp::PreprocParamsToken1 => "preproc_params_token1",
            Cpp::DOTDOTDOT => "...",
            Cpp::COMMA => ",",
            Cpp::RPAREN => ")",
            Cpp::HASHif => "#if",
            Cpp::HASHendif => "#endif",
            Cpp::HASHifdef => "#ifdef",
            Cpp::HASHifndef => "#ifndef",
            Cpp::HASHelse => "#else",
            Cpp::HASHelif => "#elif",
            Cpp::PreprocDirective => "preproc_directive",
            Cpp::PreprocArg => "preproc_arg",
            Cpp::LPAREN2 => "(",
            Cpp::Defined => "defined",
            Cpp::BANG => "!",
            Cpp::TILDE => "~",
            Cpp::DASH => "-",
            Cpp::PLUS => "+",
            Cpp::STAR => "*",
            Cpp::SLASH => "/",
            Cpp::PERCENT => "%",
            Cpp::PIPEPIPE => "||",
            Cpp::AMPAMP => "&&",
            Cpp::PIPE => "|",
            Cpp::CARET => "^",
            Cpp::AMP => "&",
            Cpp::EQEQ => "==",
            Cpp::BANGEQ => "!=",
            Cpp::GT => ">",
            Cpp::GTEQ => ">=",
            Cpp::LTEQ => "<=",
            Cpp::LT => "<",
            Cpp::LTLT => "<<",
            Cpp::GTGT => ">>",
            Cpp::Cdecl => "__cdecl",
            Cpp::Clrcall => "__clrcall",
            Cpp::Stdcall => "__stdcall",
            Cpp::Fastcall => "__fastcall",
            Cpp::Thiscall => "__thiscall",
            Cpp::Vectorcall => "__vectorcall",
            Cpp::WINAPI => "WINAPI",
            Cpp::CALLBACK => "CALLBACK",
            Cpp::SEMI => ";",
            Cpp::Typedef => "typedef",
            Cpp::Extern => "extern",
            Cpp::Attribute => "__attribute__",
            Cpp::LBRACE => "{",
            Cpp::RBRACE => "}",
            Cpp::LBRACK => "[",
            Cpp::RBRACK => "]",
            Cpp::EQ => "=",
            Cpp::Static => "static",
            Cpp::Register => "register",
            Cpp::Inline => "inline",
            Cpp::Const => "const",
            Cpp::CONST => "CONST",
            Cpp::Volatile => "volatile",
            Cpp::Restrict => "restrict",
            Cpp::Vector => "vector",
            Cpp::Atomic => "_Atomic",
            Cpp::Mutable => "mutable",
            Cpp::Explicit => "explicit",
            Cpp::Constexpr => "constexpr",
            Cpp::Signed => "signed",
            Cpp::Unsigned => "unsigned",
            Cpp::Long => "long",
            Cpp::Short => "short",
            Cpp::PrimitiveType => "primitive_type",
            Cpp::Enum => "enum",
            Cpp::Struct => "struct",
            Cpp::Union => "union",
            Cpp::COLON => ":",
            Cpp::If => "if",
            Cpp::Else => "else",
            Cpp::Switch => "switch",
            Cpp::Case => "case",
            Cpp::Default => "default",
            Cpp::While => "while",
            Cpp::Do => "do",
            Cpp::For => "for",
            Cpp::Return => "return",
            Cpp::Break => "break",
            Cpp::Continue => "continue",
            Cpp::Goto => "goto",
            Cpp::QMARK => "?",
            Cpp::STAREQ => "*=",
            Cpp::SLASHEQ => "/=",
            Cpp::PERCENTEQ => "%=",
            Cpp::PLUSEQ => "+=",
            Cpp::DASHEQ => "-=",
            Cpp::LTLTEQ => "<<=",
            Cpp::GTGTEQ => ">>=",
            Cpp::AMPEQ => "&=",
            Cpp::CARETEQ => "^=",
            Cpp::PIPEEQ => "|=",
            Cpp::DASHDASH => "--",
            Cpp::PLUSPLUS => "++",
            Cpp::Sizeof => "sizeof",
            Cpp::DOT => ".",
            Cpp::DASHGT => "->",
            Cpp::NumberLiteral => "number_literal",
            Cpp::LSQUOTE => "L'",
            Cpp::USQUOTE => "u'",
            Cpp::USQUOTE2 => "U'",
            Cpp::U8SQUOTE => "u8'",
            Cpp::SQUOTE => "'",
            Cpp::CharLiteralToken1 => "char_literal_token1",
            Cpp::LDQUOTE => "L\"",
            Cpp::UDQUOTE => "u\"",
            Cpp::UDQUOTE2 => "U\"",
            Cpp::U8DQUOTE => "u8\"",
            Cpp::DQUOTE => "\"",
            Cpp::StringLiteralToken1 => "string_literal_token1",
            Cpp::EscapeSequence => "escape_sequence",
            Cpp::SystemLibString => "system_lib_string",
            Cpp::True => "true",
            Cpp::False => "false",
            Cpp::Null => "null",
            Cpp::Comment => "comment",
            Cpp::Class => "class",
            Cpp::Final => "final",
            Cpp::Override => "override",
            Cpp::Virtual => "virtual",
            Cpp::Public => "public",
            Cpp::Private => "private",
            Cpp::Protected => "protected",
            Cpp::Auto => "auto",
            Cpp::Typename => "typename",
            Cpp::Template => "template",
            Cpp::GT2 => ">",
            Cpp::Delete => "delete",
            Cpp::Friend => "friend",
            Cpp::Noexcept => "noexcept",
            Cpp::Throw => "throw",
            Cpp::Namespace => "namespace",
            Cpp::Using => "using",
            Cpp::Try => "try",
            Cpp::Catch => "catch",
            Cpp::LBRACKLBRACK => "[[",
            Cpp::RBRACKRBRACK => "]]",
            Cpp::New => "new",
            Cpp::COLONCOLON => "::",
            Cpp::OperatorName => "operator_name",
            Cpp::Nullptr => "nullptr",
            Cpp::RawStringLiteral => "raw_string_literal",
            Cpp::TranslationUnit => "translation_unit",
            Cpp::OnlyMacro => "only_macro",
            Cpp::MacroCall => "macro_call",
            Cpp::OnlyMacroCall => "only_macro_call",
            Cpp::PreprocInclude => "preproc_include",
            Cpp::PreprocDef => "preproc_def",
            Cpp::PreprocFunctionDef => "preproc_function_def",
            Cpp::PreprocParams => "preproc_params",
            Cpp::PreprocCall => "preproc_call",
            Cpp::PreprocIf => "preproc_if",
            Cpp::PreprocIfdef => "preproc_ifdef",
            Cpp::PreprocElse => "preproc_else",
            Cpp::PreprocElif => "preproc_elif",
            Cpp::PreprocIf2 => "preproc_if",
            Cpp::PreprocIfdef2 => "preproc_ifdef",
            Cpp::PreprocElse2 => "preproc_else",
            Cpp::PreprocElif2 => "preproc_elif",
            Cpp::LineContinuation => "line_continuation",
            Cpp::PreprocCondition => "preproc_condition",
            Cpp::PreprocExpression => "preproc_expression",
            Cpp::PreprocParenthesizedExpression => "preproc_parenthesized_expression",
            Cpp::PreprocDefined => "preproc_defined",
            Cpp::PreprocUnaryExpression => "preproc_unary_expression",
            Cpp::PreprocBinaryExpression => "preproc_binary_expression",
            Cpp::CallConvention => "call_convention",
            Cpp::FunctionDefinition => "function_definition",
            Cpp::Declaration => "declaration",
            Cpp::TypeDefinition => "type_definition",
            Cpp::DeclarationSpecifiers => "_declaration_specifiers",
            Cpp::DeclarationSpecifiersNoType => "_declaration_specifiers_no_type",
            Cpp::LinkageSpecification => "linkage_specification",
            Cpp::AttributeSpecifier => "attribute_specifier",
            Cpp::DeclarationList => "declaration_list",
            Cpp::Declarator => "_declarator",
            Cpp::FieldDeclarator => "_field_declarator",
            Cpp::TypeDeclarator => "_type_declarator",
            Cpp::AbstractDeclarator => "_abstract_declarator",
            Cpp::ParenthesizedDeclarator => "parenthesized_declarator",
            Cpp::ParenthesizedDeclarator2 => "parenthesized_declarator",
            Cpp::ParenthesizedDeclarator3 => "parenthesized_declarator",
            Cpp::AbstractParenthesizedDeclarator => "abstract_parenthesized_declarator",
            Cpp::PointerDeclarator => "pointer_declarator",
            Cpp::PointerDeclarator2 => "pointer_declarator",
            Cpp::PointerDeclarator3 => "pointer_declarator",
            Cpp::AbstractPointerDeclarator => "abstract_pointer_declarator",
            Cpp::FunctionDeclarator => "function_declarator",
            Cpp::FunctionDeclarator2 => "function_declarator",
            Cpp::FunctionDeclarator3 => "function_declarator",
            Cpp::AbstractFunctionDeclarator => "abstract_function_declarator",
            Cpp::ArrayDeclarator => "array_declarator",
            Cpp::ArrayDeclarator2 => "array_declarator",
            Cpp::ArrayDeclarator3 => "array_declarator",
            Cpp::AbstractArrayDeclarator => "abstract_array_declarator",
            Cpp::InitDeclarator => "init_declarator",
            Cpp::CompoundStatement => "compound_statement",
            Cpp::StorageClassSpecifier => "storage_class_specifier",
            Cpp::TypeQualifier => "type_qualifier",
            Cpp::TypeSpecifier => "_type_specifier",
            Cpp::SizedTypeSpecifier => "sized_type_specifier",
            Cpp::EnumSpecifier => "enum_specifier",
            Cpp::EnumeratorList => "enumerator_list",
            Cpp::StructSpecifier => "struct_specifier",
            Cpp::UnionSpecifier => "union_specifier",
            Cpp::FieldDeclarationList => "field_declaration_list",
            Cpp::FieldDeclarationListItem => "_field_declaration_list_item",
            Cpp::FieldDeclaration => "field_declaration",
            Cpp::BitfieldClause => "bitfield_clause",
            Cpp::Enumerator => "enumerator",
            Cpp::ParameterList => "parameter_list",
            Cpp::ParameterDeclaration => "parameter_declaration",
            Cpp::LabeledStatement => "labeled_statement",
            Cpp::ExpressionStatement => "expression_statement",
            Cpp::IfStatement => "if_statement",
            Cpp::SwitchStatement => "switch_statement",
            Cpp::CompoundStatement2 => "compound_statement",
            Cpp::CaseStatement => "case_statement",
            Cpp::WhileStatement => "while_statement",
            Cpp::DoStatement => "do_statement",
            Cpp::ForStatement => "for_statement",
            Cpp::ReturnStatement => "return_statement",
            Cpp::BreakStatement => "break_statement",
            Cpp::ContinueStatement => "continue_statement",
            Cpp::GotoStatement => "goto_statement",
            Cpp::Expression => "_expression",
            Cpp::CommaExpression => "comma_expression",
            Cpp::ConditionalExpression => "conditional_expression",
            Cpp::AssignmentExpression => "assignment_expression",
            Cpp::PointerExpression => "pointer_expression",
            Cpp::UnaryExpression => "unary_expression",
            Cpp::BinaryExpression => "binary_expression",
            Cpp::UpdateExpression => "update_expression",
            Cpp::CastExpression => "cast_expression",
            Cpp::TypeDescriptor => "type_descriptor",
            Cpp::SizeofExpression => "sizeof_expression",
            Cpp::SubscriptExpression => "subscript_expression",
            Cpp::CallExpression => "call_expression",
            Cpp::ArgumentList => "argument_list",
            Cpp::FieldExpression => "field_expression",
            Cpp::CompoundLiteralExpression => "compound_literal_expression",
            Cpp::ParenthesizedExpression => "parenthesized_expression",
            Cpp::InitializerList => "initializer_list",
            Cpp::InitializerPair => "initializer_pair",
            Cpp::SubscriptDesignator => "subscript_designator",
            Cpp::FieldDesignator => "field_designator",
            Cpp::CharLiteral => "char_literal",
            Cpp::ConcatenatedString => "concatenated_string",
            Cpp::StringLiteral => "string_literal",
            Cpp::EmptyDeclaration => "_empty_declaration",
            Cpp::ClassSpecifier => "class_specifier",
            Cpp::VirtualSpecifier => "virtual_specifier",
            Cpp::VirtualFunctionSpecifier => "virtual_function_specifier",
            Cpp::BaseClassClause => "base_class_clause",
            Cpp::DependentType => "dependent_type",
            Cpp::TemplateDeclaration => "template_declaration",
            Cpp::TemplateInstantiation => "template_instantiation",
            Cpp::TemplateParameterList => "template_parameter_list",
            Cpp::TypeParameterDeclaration => "type_parameter_declaration",
            Cpp::VariadicTypeParameterDeclaration => "variadic_type_parameter_declaration",
            Cpp::OptionalTypeParameterDeclaration => "optional_type_parameter_declaration",
            Cpp::OptionalParameterDeclaration => "optional_parameter_declaration",
            Cpp::VariadicParameterDeclaration => "variadic_parameter_declaration",
            Cpp::VariadicDeclarator => "variadic_declarator",
            Cpp::ReferenceDeclarator => "reference_declarator",
            Cpp::FieldInitializerList => "field_initializer_list",
            Cpp::FieldInitializer => "field_initializer",
            Cpp::FunctionDefinition2 => "function_definition",
            Cpp::FunctionDefinition3 => "function_definition",
            Cpp::Declaration2 => "declaration",
            Cpp::DefaultMethodClause => "default_method_clause",
            Cpp::DeleteMethodClause => "delete_method_clause",
            Cpp::FriendDeclaration => "friend_declaration",
            Cpp::AccessSpecifier => "access_specifier",
            Cpp::ReferenceDeclarator2 => "reference_declarator",
            Cpp::ReferenceDeclarator3 => "reference_declarator",
            Cpp::AbstractReferenceDeclarator => "abstract_reference_declarator",
            Cpp::StructuredBindingDeclarator => "structured_binding_declarator",
            Cpp::TrailingReturnType => "trailing_return_type",
            Cpp::Noexcept2 => "noexcept",
            Cpp::ThrowSpecifier => "throw_specifier",
            Cpp::TemplateType => "template_type",
            Cpp::TemplateMethod => "template_method",
            Cpp::TemplateFunction => "template_function",
            Cpp::TemplateArgumentList => "template_argument_list",
            Cpp::NamespaceDefinition => "namespace_definition",
            Cpp::UsingDeclaration => "using_declaration",
            Cpp::AliasDeclaration => "alias_declaration",
            Cpp::ForRangeLoop => "for_range_loop",
            Cpp::ThrowStatement => "throw_statement",
            Cpp::TryStatement => "try_statement",
            Cpp::CatchClause => "catch_clause",
            Cpp::Attribute2 => "attribute",
            Cpp::NewExpression => "new_expression",
            Cpp::NewDeclarator => "new_declarator",
            Cpp::DeleteExpression => "delete_expression",
            Cpp::LambdaExpression => "lambda_expression",
            Cpp::LambdaCaptureSpecifier => "lambda_capture_specifier",
            Cpp::LambdaDefaultCapture => "lambda_default_capture",
            Cpp::DestructorName => "destructor_name",
            Cpp::ScopedFieldIdentifier => "scoped_field_identifier",
            Cpp::ScopedIdentifier => "scoped_identifier",
            Cpp::ScopedTypeIdentifier => "scoped_type_identifier",
            Cpp::ScopedNamespaceIdentifier => "scoped_namespace_identifier",
            Cpp::TranslationUnitRepeat1 => "translation_unit_repeat1",
            Cpp::PreprocParamsRepeat1 => "preproc_params_repeat1",
            Cpp::PreprocIfInFieldDeclarationListRepeat1 => "preproc_if_in_field_declaration_list_repeat1",
            Cpp::PreprocExpressionRepeat1 => "preproc_expression_repeat1",
            Cpp::FunctionDefinitionRepeat1 => "function_definition_repeat1",
            Cpp::DeclarationRepeat1 => "declaration_repeat1",
            Cpp::TypeDefinitionRepeat1 => "type_definition_repeat1",
            Cpp::TypeDefinitionRepeat2 => "type_definition_repeat2",
            Cpp::DeclarationSpecifiersRepeat1 => "_declaration_specifiers_repeat1",
            Cpp::DeclarationSpecifiersRepeat2 => "_declaration_specifiers_repeat2",
            Cpp::PointerDeclaratorRepeat1 => "pointer_declarator_repeat1",
            Cpp::FunctionDeclaratorRepeat1 => "function_declarator_repeat1",
            Cpp::FunctionDeclaratorRepeat2 => "function_declarator_repeat2",
            Cpp::AbstractFunctionDeclaratorRepeat1 => "abstract_function_declarator_repeat1",
            Cpp::SizedTypeSpecifierRepeat1 => "sized_type_specifier_repeat1",
            Cpp::EnumeratorListRepeat1 => "enumerator_list_repeat1",
            Cpp::FieldDeclarationRepeat1 => "field_declaration_repeat1",
            Cpp::ParameterListRepeat1 => "parameter_list_repeat1",
            Cpp::SwitchBodyRepeat1 => "switch_body_repeat1",
            Cpp::CaseStatementRepeat1 => "case_statement_repeat1",
            Cpp::ArgumentListRepeat1 => "argument_list_repeat1",
            Cpp::InitializerListRepeat1 => "initializer_list_repeat1",
            Cpp::InitializerPairRepeat1 => "initializer_pair_repeat1",
            Cpp::ConcatenatedStringRepeat1 => "concatenated_string_repeat1",
            Cpp::StringLiteralRepeat1 => "string_literal_repeat1",
            Cpp::BaseClassClauseRepeat1 => "base_class_clause_repeat1",
            Cpp::TemplateParameterListRepeat1 => "template_parameter_list_repeat1",
            Cpp::FieldInitializerListRepeat1 => "field_initializer_list_repeat1",
            Cpp::StructuredBindingDeclaratorRepeat1 => "structured_binding_declarator_repeat1",
            Cpp::ThrowSpecifierRepeat1 => "throw_specifier_repeat1",
            Cpp::TemplateArgumentListRepeat1 => "template_argument_list_repeat1",
            Cpp::TryStatementRepeat1 => "try_statement_repeat1",
            Cpp::AttributeRepeat1 => "attribute_repeat1",
            Cpp::NamespaceIdentifier => "namespace_identifier",
            Cpp::FieldIdentifier => "field_identifier",
            Cpp::StatementIdentifier => "statement_identifier",
            Cpp::TypeIdentifier => "type_identifier",
            Cpp::Error => "ERROR",
            }
    }
}

#[allow(clippy::unreadable_literal)]
static KEYS: phf::Map<&'static str, Cpp> = ::phf::Map {
    key: 732231254413039614,
    disps: ::phf::Slice::Static(&[
        (0, 18),
        (0, 17),
        (0, 82),
        (0, 267),
        (0, 43),
        (0, 15),
        (0, 129),
        (0, 79),
        (0, 96),
        (0, 5),
        (0, 0),
        (0, 0),
        (0, 3),
        (0, 50),
        (2, 140),
        (0, 0),
        (0, 0),
        (3, 298),
        (0, 19),
        (0, 61),
        (0, 32),
        (0, 11),
        (0, 0),
        (0, 1),
        (0, 120),
        (0, 306),
        (2, 311),
        (1, 255),
        (2, 45),
        (0, 5),
        (0, 15),
        (6, 304),
        (0, 219),
        (0, 74),
        (0, 13),
        (2, 266),
        (0, 18),
        (26, 2),
        (3, 171),
        (0, 11),
        (0, 90),
        (0, 0),
        (0, 0),
        (0, 0),
        (0, 47),
        (1, 0),
        (1, 1),
        (0, 21),
        (0, 256),
        (0, 57),
        (54, 228),
        (4, 64),
        (1, 156),
        (0, 55),
        (1, 46),
        (0, 1),
        (2, 278),
        (1, 279),
        (122, 183),
        (0, 44),
        (0, 179),
        (10, 155),
        (23, 94),
        (20, 222),
        (0, 15),
        (26, 45),
    ]),
    entries: ::phf::Slice::Static(&[
        ("only_macro_call", Cpp::OnlyMacroCall),
        ("sizeof_expression", Cpp::SizeofExpression),
        ("+", Cpp::PLUS),
        ("reference_declarator", Cpp::ReferenceDeclarator),
        ("__stdcall", Cpp::Stdcall),
        ("preproc_function_def", Cpp::PreprocFunctionDef),
        ("field_declaration_repeat1", Cpp::FieldDeclarationRepeat1),
        ("template_argument_list", Cpp::TemplateArgumentList),
        ("abstract_pointer_declarator", Cpp::AbstractPointerDeclarator),
        ("_declaration_specifiers_repeat1", Cpp::DeclarationSpecifiersRepeat1),
        ("char_literal_token1", Cpp::CharLiteralToken1),
        ("#endif", Cpp::HASHendif),
        ("__thiscall", Cpp::Thiscall),
        ("_declaration_specifiers_no_type", Cpp::DeclarationSpecifiersNoType),
        ("labeled_statement", Cpp::LabeledStatement),
        ("throw_specifier_repeat1", Cpp::ThrowSpecifierRepeat1),
        ("field_identifier", Cpp::FieldIdentifier),
        ("preproc_call", Cpp::PreprocCall),
        ("friend", Cpp::Friend),
        ("pointer_expression", Cpp::PointerExpression),
        ("initializer_pair", Cpp::InitializerPair),
        ("<<=", Cpp::LTLTEQ),
        ("/", Cpp::SLASH),
        ("throw", Cpp::Throw),
        ("virtual_function_specifier", Cpp::VirtualFunctionSpecifier),
        ("preproc_condition", Cpp::PreprocCondition),
        ("class_specifier", Cpp::ClassSpecifier),
        ("parameter_list_repeat1", Cpp::ParameterListRepeat1),
        ("_declarator", Cpp::Declarator),
        ("abstract_function_declarator", Cpp::AbstractFunctionDeclarator),
        ("field_declaration_list", Cpp::FieldDeclarationList),
        ("&", Cpp::AMP),
        ("default_method_clause", Cpp::DefaultMethodClause),
        ("linkage_specification", Cpp::LinkageSpecification),
        ("conditional_expression", Cpp::ConditionalExpression),
        ("cast_expression", Cpp::CastExpression),
        ("continue", Cpp::Continue),
        ("catch", Cpp::Catch),
        ("enumerator", Cpp::Enumerator),
        ("sizeof", Cpp::Sizeof),
        ("assignment_expression", Cpp::AssignmentExpression),
        ("parameter_declaration", Cpp::ParameterDeclaration),
        ("false", Cpp::False),
        ("|=", Cpp::PIPEEQ),
        ("_declaration_specifiers_repeat2", Cpp::DeclarationSpecifiersRepeat2),
        ("do_statement", Cpp::DoStatement),
        ("[[", Cpp::LBRACKLBRACK),
        ("enum_specifier", Cpp::EnumSpecifier),
        ("lambda_expression", Cpp::LambdaExpression),
        ("comment", Cpp::Comment),
        ("scoped_field_identifier", Cpp::ScopedFieldIdentifier),
        ("argument_list_repeat1", Cpp::ArgumentListRepeat1),
        ("parenthesized_expression", Cpp::ParenthesizedExpression),
        ("delete", Cpp::Delete),
        ("template_argument_list_repeat1", Cpp::TemplateArgumentListRepeat1),
        ("template_type", Cpp::TemplateType),
        ("static", Cpp::Static),
        ("switch", Cpp::Switch),
        ("operator_name", Cpp::OperatorName),
        ("line_continuation", Cpp::LineContinuation),
        ("preproc_else", Cpp::PreprocElse),
        ("string_literal_token1", Cpp::StringLiteralToken1),
        ("initializer_list_repeat1", Cpp::InitializerListRepeat1),
        ("type_parameter_declaration", Cpp::TypeParameterDeclaration),
        ("const", Cpp::Const),
        ("ERROR", Cpp::Error),
        (">>", Cpp::GTGT),
        ("function_declarator_repeat2", Cpp::FunctionDeclaratorRepeat2),
        ("using", Cpp::Using),
        ("[", Cpp::LBRACK),
        ("destructor_name", Cpp::DestructorName),
        ("++", Cpp::PLUSPLUS),
        ("throw_statement", Cpp::ThrowStatement),
        ("switch_statement", Cpp::SwitchStatement),
        ("#if", Cpp::HASHif),
        ("typename", Cpp::Typename),
        ("preproc_defined", Cpp::PreprocDefined),
        ("]]", Cpp::RBRACKRBRACK),
        ("preproc_def", Cpp::PreprocDef),
        ("inline", Cpp::Inline),
        ("(", Cpp::LPAREN),
        ("enumerator_list", Cpp::EnumeratorList),
        ("template", Cpp::Template),
        ("template_parameter_list_repeat1", Cpp::TemplateParameterListRepeat1),
        ("for", Cpp::For),
        ("enum", Cpp::Enum),
        ("initializer_list", Cpp::InitializerList),
        ("type_identifier", Cpp::TypeIdentifier),
        ("macro_call", Cpp::MacroCall),
        ("\\n", Cpp::LF),
        ("friend_declaration", Cpp::FriendDeclaration),
        ("u8\\\"", Cpp::U8DQUOTE),
        ("return", Cpp::Return),
        ("<<", Cpp::LTLT),
        ("storage_class_specifier", Cpp::StorageClassSpecifier),
        ("new_declarator", Cpp::NewDeclarator),
        ("_field_declarator", Cpp::FieldDeclarator),
        ("comma_expression", Cpp::CommaExpression),
        ("#elif", Cpp::HASHelif),
        ("expression_statement", Cpp::ExpressionStatement),
        ("+=", Cpp::PLUSEQ),
        ("macro", Cpp::Macro),
        ("!=", Cpp::BANGEQ),
        ("WINAPI", Cpp::WINAPI),
        ("field_initializer", Cpp::FieldInitializer),
        ("update_expression", Cpp::UpdateExpression),
        ("pointer_declarator_repeat1", Cpp::PointerDeclaratorRepeat1),
        ("u\\\"", Cpp::UDQUOTE),
        ("preproc_if", Cpp::PreprocIf),
        ("#include", Cpp::HASHinclude),
        ("break_statement", Cpp::BreakStatement),
        ("struct", Cpp::Struct),
        ("volatile", Cpp::Volatile),
        ("only_macro", Cpp::OnlyMacro),
        ("union_specifier", Cpp::UnionSpecifier),
        ("abstract_parenthesized_declarator", Cpp::AbstractParenthesizedDeclarator),
        ("/=", Cpp::SLASHEQ),
        ("abstract_array_declarator", Cpp::AbstractArrayDeclarator),
        ("abstract_function_declarator_repeat1", Cpp::AbstractFunctionDeclaratorRepeat1),
        ("sized_type_specifier_repeat1", Cpp::SizedTypeSpecifierRepeat1),
        ("preproc_parenthesized_expression", Cpp::PreprocParenthesizedExpression),
        ("class", Cpp::Class),
        ("primitive_type", Cpp::PrimitiveType),
        ("vector", Cpp::Vector),
        ("variadic_type_parameter_declaration", Cpp::VariadicTypeParameterDeclaration),
        ("->", Cpp::DASHGT),
        ("null", Cpp::Null),
        ("preproc_arg", Cpp::PreprocArg),
        ("preproc_params_repeat1", Cpp::PreprocParamsRepeat1),
        ("public", Cpp::Public),
        ("private", Cpp::Private),
        ("register", Cpp::Register),
        ("type_definition_repeat1", Cpp::TypeDefinitionRepeat1),
        ("initializer_pair_repeat1", Cpp::InitializerPairRepeat1),
        ("--", Cpp::DASHDASH),
        ("continue_statement", Cpp::ContinueStatement),
        ("alias_declaration", Cpp::AliasDeclaration),
        ("bitfield_clause", Cpp::BitfieldClause),
        ("function_declarator_repeat1", Cpp::FunctionDeclaratorRepeat1),
        ("translation_unit", Cpp::TranslationUnit),
        ("new_expression", Cpp::NewExpression),
        ("::", Cpp::COLONCOLON),
        ("long", Cpp::Long),
        ("u8\'", Cpp::U8SQUOTE),
        ("parenthesized_declarator", Cpp::ParenthesizedDeclarator),
        ("-=", Cpp::DASHEQ),
        ("explicit", Cpp::Explicit),
        ("template_parameter_list", Cpp::TemplateParameterList),
        (".", Cpp::DOT),
        ("#ifdef", Cpp::HASHifdef),
        ("namespace_definition", Cpp::NamespaceDefinition),
        ("base_class_clause", Cpp::BaseClassClause),
        ("escape_sequence", Cpp::EscapeSequence),
        ("?", Cpp::QMARK),
        ("constexpr", Cpp::Constexpr),
        ("protected", Cpp::Protected),
        ("noexcept", Cpp::Noexcept),
        ("_type_specifier", Cpp::TypeSpecifier),
        ("union", Cpp::Union),
        ("try_statement_repeat1", Cpp::TryStatementRepeat1),
        ("template_instantiation", Cpp::TemplateInstantiation),
        ("^", Cpp::CARET),
        ("optional_parameter_declaration", Cpp::OptionalParameterDeclaration),
        ("CONST", Cpp::CONST),
        ("}", Cpp::RBRACE),
        ("else", Cpp::Else),
        ("abstract_reference_declarator", Cpp::AbstractReferenceDeclarator),
        (":", Cpp::COLON),
        ("{", Cpp::LBRACE),
        ("declaration_repeat1", Cpp::DeclarationRepeat1),
        ("auto", Cpp::Auto),
        ("typedef", Cpp::Typedef),
        ("^=", Cpp::CARETEQ),
        ("field_initializer_list", Cpp::FieldInitializerList),
        ("init_declarator", Cpp::InitDeclarator),
        ("#else", Cpp::HASHelse),
        ("#ifndef", Cpp::HASHifndef),
        ("dependent_type", Cpp::DependentType),
        ("parameter_list", Cpp::ParameterList),
        ("try", Cpp::Try),
        ("signed", Cpp::Signed),
        ("array_declarator", Cpp::ArrayDeclarator),
        ("scoped_namespace_identifier", Cpp::ScopedNamespaceIdentifier),
        ("sized_type_specifier", Cpp::SizedTypeSpecifier),
        ("final", Cpp::Final),
        (")", Cpp::RPAREN),
        ("virtual", Cpp::Virtual),
        ("override", Cpp::Override),
        ("declaration", Cpp::Declaration),
        ("throw_specifier", Cpp::ThrowSpecifier),
        (">=", Cpp::GTEQ),
        ("pointer_declarator", Cpp::PointerDeclarator),
        ("subscript_expression", Cpp::SubscriptExpression),
        ("preproc_params_token1", Cpp::PreprocParamsToken1),
        ("system_lib_string", Cpp::SystemLibString),
        ("L\\\"", Cpp::LDQUOTE),
        ("concatenated_string_repeat1", Cpp::ConcatenatedStringRepeat1),
        ("switch_body_repeat1", Cpp::SwitchBodyRepeat1),
        ("trailing_return_type", Cpp::TrailingReturnType),
        ("default", Cpp::Default),
        ("_field_declaration_list_item", Cpp::FieldDeclarationListItem),
        ("attribute_repeat1", Cpp::AttributeRepeat1),
        ("identifier", Cpp::Identifier),
        ("u\'", Cpp::USQUOTE),
        ("field_declaration", Cpp::FieldDeclaration),
        ("unsigned", Cpp::Unsigned),
        ("number_literal", Cpp::NumberLiteral),
        ("!", Cpp::BANG),
        ("==", Cpp::EQEQ),
        ("__clrcall", Cpp::Clrcall),
        ("while", Cpp::While),
        ("preproc_binary_expression", Cpp::PreprocBinaryExpression),
        ("template_method", Cpp::TemplateMethod),
        ("declaration_list", Cpp::DeclarationList),
        ("namespace", Cpp::Namespace),
        ("case_statement_repeat1", Cpp::CaseStatementRepeat1),
        (",", Cpp::COMMA),
        ("]", Cpp::RBRACK),
        ("%=", Cpp::PERCENTEQ),
        ("struct_specifier", Cpp::StructSpecifier),
        ("subscript_designator", Cpp::SubscriptDesignator),
        ("optional_type_parameter_declaration", Cpp::OptionalTypeParameterDeclaration),
        ("for_statement", Cpp::ForStatement),
        ("\\\"", Cpp::DQUOTE),
        ("statement_identifier", Cpp::StatementIdentifier),
        ("unary_expression", Cpp::UnaryExpression),
        ("_Atomic", Cpp::Atomic),
        ("|", Cpp::PIPE),
        ("__attribute__", Cpp::Attribute),
        ("case_statement", Cpp::CaseStatement),
        ("||", Cpp::PIPEPIPE),
        ("short", Cpp::Short),
        ("CALLBACK", Cpp::CALLBACK),
        ("nullptr", Cpp::Nullptr),
        ("=", Cpp::EQ),
        ("while_statement", Cpp::WhileStatement),
        ("preproc_elif", Cpp::PreprocElif),
        ("field_expression", Cpp::FieldExpression),
        ("structured_binding_declarator_repeat1", Cpp::StructuredBindingDeclaratorRepeat1),
        ("field_designator", Cpp::FieldDesignator),
        ("preproc_expression", Cpp::PreprocExpression),
        ("__fastcall", Cpp::Fastcall),
        ("string_literal_repeat1", Cpp::StringLiteralRepeat1),
        ("<=", Cpp::LTEQ),
        ("_empty_declaration", Cpp::EmptyDeclaration),
        ("case", Cpp::Case),
        ("preproc_include", Cpp::PreprocInclude),
        ("concatenated_string", Cpp::ConcatenatedString),
        ("function_definition_repeat1", Cpp::FunctionDefinitionRepeat1),
        ("binary_expression", Cpp::BinaryExpression),
        ("enumerator_list_repeat1", Cpp::EnumeratorListRepeat1),
        (">>=", Cpp::GTGTEQ),
        ("variadic_declarator", Cpp::VariadicDeclarator),
        ("end", Cpp::End),
        ("do", Cpp::Do),
        ("type_definition_repeat2", Cpp::TypeDefinitionRepeat2),
        (">", Cpp::GT),
        ("__cdecl", Cpp::Cdecl),
        ("<", Cpp::LT),
        (";", Cpp::SEMI),
        ("#define", Cpp::HASHdefine),
        ("compound_statement", Cpp::CompoundStatement),
        ("delete_expression", Cpp::DeleteExpression),
        ("string_literal", Cpp::StringLiteral),
        ("raw_string_literal", Cpp::RawStringLiteral),
        ("access_specifier", Cpp::AccessSpecifier),
        ("defined", Cpp::Defined),
        ("try_statement", Cpp::TryStatement),
        ("function_declarator", Cpp::FunctionDeclarator),
        ("preproc_expression_repeat1", Cpp::PreprocExpressionRepeat1),
        ("__vectorcall", Cpp::Vectorcall),
        ("restrict", Cpp::Restrict),
        ("function_definition", Cpp::FunctionDefinition),
        ("virtual_specifier", Cpp::VirtualSpecifier),
        ("field_initializer_list_repeat1", Cpp::FieldInitializerListRepeat1),
        ("type_definition", Cpp::TypeDefinition),
        ("~", Cpp::TILDE),
        ("L\'", Cpp::LSQUOTE),
        ("structured_binding_declarator", Cpp::StructuredBindingDeclarator),
        ("lambda_capture_specifier", Cpp::LambdaCaptureSpecifier),
        ("...", Cpp::DOTDOTDOT),
        ("if", Cpp::If),
        ("call_expression", Cpp::CallExpression),
        ("catch_clause", Cpp::CatchClause),
        ("template_declaration", Cpp::TemplateDeclaration),
        ("argument_list", Cpp::ArgumentList),
        ("&=", Cpp::AMPEQ),
        ("*=", Cpp::STAREQ),
        ("new", Cpp::New),
        ("break", Cpp::Break),
        ("for_range_loop", Cpp::ForRangeLoop),
        ("_abstract_declarator", Cpp::AbstractDeclarator),
        ("char_literal", Cpp::CharLiteral),
        ("&&", Cpp::AMPAMP),
        ("using_declaration", Cpp::UsingDeclaration),
        ("preproc_params", Cpp::PreprocParams),
        ("call_convention", Cpp::CallConvention),
        ("template_function", Cpp::TemplateFunction),
        ("type_qualifier", Cpp::TypeQualifier),
        ("return_statement", Cpp::ReturnStatement),
        ("scoped_type_identifier", Cpp::ScopedTypeIdentifier),
        ("_declaration_specifiers", Cpp::DeclarationSpecifiers),
        ("preproc_if_in_field_declaration_list_repeat1", Cpp::PreprocIfInFieldDeclarationListRepeat1),
        ("true", Cpp::True),
        ("preproc_directive", Cpp::PreprocDirective),
        ("*", Cpp::STAR),
        ("-", Cpp::DASH),
        ("mutable", Cpp::Mutable),
        ("lambda_default_capture", Cpp::LambdaDefaultCapture),
        ("goto_statement", Cpp::GotoStatement),
        ("goto", Cpp::Goto),
        ("translation_unit_repeat1", Cpp::TranslationUnitRepeat1),
        ("extern", Cpp::Extern),
        ("scoped_identifier", Cpp::ScopedIdentifier),
        ("_expression", Cpp::Expression),
        ("preproc_ifdef", Cpp::PreprocIfdef),
        ("_type_declarator", Cpp::TypeDeclarator),
        ("delete_method_clause", Cpp::DeleteMethodClause),
        ("namespace_identifier", Cpp::NamespaceIdentifier),
        ("variadic_parameter_declaration", Cpp::VariadicParameterDeclaration),
        ("\'", Cpp::SQUOTE),
        ("base_class_clause_repeat1", Cpp::BaseClassClauseRepeat1),
        ("if_statement", Cpp::IfStatement),
        ("attribute_specifier", Cpp::AttributeSpecifier),
        ("compound_literal_expression", Cpp::CompoundLiteralExpression),
        ("type_descriptor", Cpp::TypeDescriptor),
        ("%", Cpp::PERCENT),
        ("preproc_unary_expression", Cpp::PreprocUnaryExpression),
    ]),
};

impl From<&str> for Cpp {
    #[inline(always)]
    fn from(key: &str) -> Self {
        KEYS.get(key).unwrap().clone()
    }
}

impl From<u16> for Cpp {
    #[inline(always)]
    fn from(x: u16) -> Self {
        unsafe { std::mem::transmute(x) }
    }
}

// Cpp == u16
impl PartialEq<u16> for Cpp {
    #[inline(always)]
    fn eq(&self, x: &u16) -> bool {
        *self == Cpp::from(*x)
    }
}

// u16 == Cpp
impl PartialEq<Cpp> for u16 {
    #[inline(always)]
    fn eq(&self, x: &Cpp) -> bool {
        *x == *self
    }
}